### Odds 2015

In [7]:
import pandas as pd
apuestas_2015 = pd.read_clipboard(header=None, names=['SONG','BET365','UNIBET','YOU_WIN','BOYLE_SPORTS','CORAL',
                                                     'SKY_BET','BET_VICTOR','TITAN_BET','PAF','BETFAIR_SPORT',
                                                     'SPORTING_BET','INTE_TOPS','PADDY_POWER','BET_FRED','BETWAY',
                                                     'STAN_JAMES','BWIN','MATCH_BOOK','BETFAIR_EXCHANG'])
apuestas_2015

,SONG,BET365,UNIBET,YOU_WIN,BOYLE_SPORTS,CORAL,SKY_BET,BET_VICTOR,TITAN_BET,PAF,BETFAIR_SPORT,SPORTING_BET,INTE_TOPS,PADDY_POWER,BET_FRED,BETWAY,STAN_JAMES,BWIN,MATCH_BOOK,BETFAIR_EXCHANG
0,Sweden Måns Zelmerlöw - Heroes,2.1,2.0,2.38,2.25,2.1,2.10,2.1,2.1,2.25,2.1,2,2.25,2.0,2.0,2.1,2.25,1.00,2.21,2.20
1,Russia Polina Gagarina - A Million Voices,3.75,4.5,4.00,3.75,4.5,3.75,4.0,4.0,3.50,4.0,4,4.00,4.0,4.5,4.0,3.50,4.75,5.16,4.99
2,Italy Il Volo - Grande Amore,5,6.0,5.00,5.00,5.5,5.50,6.0,5.5,5.00,6.0,5,4.25,5.5,6.5,4.5,4.50,5.00,6.74,6.51
3,Belgium Loïc Nottet - Rhythm Inside,11,12.0,9.00,12.00,9.0,10.00,12.0,10.0,7.50,8.0,11,7.00,9.0,13.0,8.0,5.00,15.00,18.00,18.00
4,Australia Guy Sebastian - Tonight Again,11,12.0,9.00,11.00,10.0,11.00,13.0,10.0,10.00,11.0,11,9.00,10.0,13.0,11.0,9.00,13.00,16.00,17.00
5,Estonia Born & Rästa - Goodbye to Yesterday,19,24.0,34.00,23.00,21.0,21.00,19.0,21.0,29.00,17.0,21,23.00,17.0,26.0,26.0,15.00,21.00,27.00,27.00
6,Serbia Bojana Stamenov - Beauty Never Lies,34,30.0,41.00,26.00,26.0,34.00,34.0,29.0,29.00,26.0,34,29.00,26.0,41.0,34.0,21.00,26.00,51.00,52.00
7,Norway Mørland & Scarlett - A Monster Like Me,34,30.0,41.00,34.00,41.0,41.00,41.0,41.0,26.00,41.0,41,29.00,29.0,51.0,34.0,34.00,NaN,70.00,62.00
8,Latvia Aminata Savadogo - Love Injected,41,51.0,34.00,41.00,51.0,41.00,41.0,34.0,51.00,51.0,41,34.00,41.0,67.0,34.0,34.00,NaN,150.00,143.00
9,Israel Nadav Guedj - Golden Boy,67,51.0,67.00,81.00,41.0,67.00,46.0,51.0,51.00,29.0,67,51.00,41.0,67.0,51.0,41.00,34.00,NaN,133.00
10,Azerbaijan Elnur Hüseynov - Hour Of The Wolf,67,34.0,67.00,41.00,67.0,51.00,67.0,67.0,34.00,67.0,41,51.00,51.0,67.0,51.0,41.00,51.00,100.00,105.00
11,Spain Edurne - Amanecer,81,34.0,81.00,51.00,67.0,81.00,67.0,67.0,34.00,81.0,67,51.00,81.0,67.0,67.0,51.00,51.00,NaN,181.00
12,Slovenia Maraaya - Here for You,81,51.0,81.00,67.00,81.0,67.00,67.0,81.0,51.00,81.0,67,51.00,67.0,67.0,67.0,51.00,67.00,199.00,200.00
13,Georgia Nina Sublatti - Warrior,101,81.0,151.00,67.00,101.0,101.00,101.0,81.0,81.00,81.0,101,81.00,67.0,101.0,81.0,51.00,67.00,199.00,285.00
14,United Kingdom Velvet - Still in Love with You,151,101.0,151.00,126.00,41.0,126.00,81.0,81.0,101.00,81.0,81,81.00,41.0,101.0,101.0,67.00,101.00,298.00,304.00
15,Greece M. Elena Kyriakou - One Last Breath,151,81.0,126.00,101.00,126.0,101.00,126.0,126.0,81.00,101.0,101,101.00,81.0,101.0,101.0,101.00,101.00,NaN,703.00
16,Romania Voltaj - De La Capăt / All Over Again,151,126.0,151.00,101.00,151.0,101.00,101.0,126.0,126.00,101.0,101,126.00,101.0,101.0,126.0,101.00,101.00,NaN,789.00
17,Armenia Genealogy - Face The Shadow,151,101.0,151.00,176.00,151.0,151.00,151.0,151.0,101.00,101.0,101,126.00,101.0,101.0,126.0,126.00,101.00,199.00,228.00
18,Albania Elhaida Dani - I'm Alive,151,101.0,126.00,126.00,101.0,151.00,101.0,126.0,101.00,101.0,101,101.00,101.0,101.0,101.0,101.00,101.00,496.00,950.00
19,Cyprus Karayiannis - One Thing I Should Have ...,151,126.0,151.00,101.00,151.0,126.00,126.0,126.0,126.00,126.0,101,101.00,101.0,101.0,101.0,101.00,101.00,496.00,713.00
20,Hungary Boggie - Wars For Nothing,151,101.0,126.00,126.00,126.0,126.00,151.0,126.0,101.00,101.0,101,101.00,101.0,101.0,126.0,81.00,201.00,496.00,589.00
21,France Lisa Angell - N’oubliez pas,151,126.0,126.00,176.00,151.0,126.00,126.0,126.0,126.00,101.0,101,126.00,151.0,101.0,126.0,101.00,201.00,496.00,694.00
22,Lithuania Monika & Vaidas - This Time,201,151.0,201.00,151.00,201.0,151.00,151.0,151.0,151.00,101.0,101,126.00,101.0,101.0,126.0,101.00,101.00,496.00,950.00
23,Poland M. Kuszyńska - In The Name Of Love,251,251.0,251.00,151.00,251.0,201.00,151.0,151.0,251.00,126.0,201,151.00,101.0,101.0,151.0,151.00,101.00,NaN,903.00
24,Austria The Makemakes - I Am Yours,251,201.0,251.00,151.00,251.0,151.00,126.0,151.0,201.00,101.0,151,151.00,151.0,101.0,151.0,101.00,101.00,496.00,950.00
25,Montenegro Knez - Adio,201,101.0,251.00,151.00,251.0,251.00,201.0,126.0,101.00,126.0,201,151.00,151.0,101.0,151.0,176.00,101.00,496.00,950.00
26,Germany Ann Sophie - Black Smoke,"251,00",201.0,201.00,201.00,251.0,201.00,251.0,151.0,201.00,151.0,151,151.00,201.0,101.0,151.0,126.00,NaN,496.00,950.00

In [8]:
paises_dobleword = {'North':'North Macedonia','The':'The Netherlands','Bosnia':'Bosnia and Herzegovina',
                    'United':'United Kingdom','Czech':'Czech Republic','Serbia':'Serbia and Montenegro',
                    'San':'San Marino'}

In [9]:
dict_codes = {  "Albania":10,
                "Andorra":11,
                "Armenia":12,
                "Australia":13,
                "Austria":14,
                "Azerbaijan":15,
                "Belarus":16,
                "Belgium":17,
                "Bosnia and Herzegovina":18,
                "Bulgaria":19,
                "Croatia":20,
                "Cyprus":21,
                "Czech Republic":22,
                "Denmark":23,
                "Estonia":24,
                "Finland":25,
                "France":26,
                "Georgia":27,
                "Germany":28,
                "Greece":29,
                "Hungary":30,
                "Iceland":31,
                "Ireland":32,
                "Israel":33,
                "Italy":34,
                "Latvia":35,
                "Lithuania":36,
                "Malta":37,
                "Moldova":38,
                "Monaco":39,
                "Montenegro":40,
                "North Macedonia":41,
                "Norway":42,
                "Poland":43,
                "Portugal":44,
                "Romania":45,
                "Russia":46,
                "San Marino":47,
                "Serbia":48,
                "Serbia and Montenegro":49,
                "Slovakia":50,
                "Slovenia":51,
                "Spain":52,
                "Sweden":53,
                "Switzerland":54,
                "The Netherlands":55,
                "Netherlands":55,
                "Turkey":56,
                "Ukraine":57,
                "United Kingdom":58
}

In [10]:
lista_corregida = []
for song in apuestas_2015['SONG']:

    if (str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]) in paises_dobleword:
        lista_corregida.append(paises_dobleword[(str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0])])
    else:
        lista_corregida.append((str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]))
        
apuestas_2015['country'] = lista_corregida

In [11]:
codigo = []
for pais in apuestas_2015['country']:
    codigo.append(int(str(dict_codes[pais])+'2015'))
apuestas_2015['codigo'] = codigo

In [12]:
apuestas_2015.columns

Index(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'BETFAIR_EXCHANG', 'country',
       'codigo'],
      dtype='object')

In [13]:
ap15_bets = apuestas_2015[['BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'BETFAIR_EXCHANG']]

In [14]:
apuestas_2015['bet_mean'] = list(ap15_bets.mean(axis=1))

C:\Users\Usuario\AppData\Local\Temp\ipykernel_14728\2393030016.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  apuestas_2015['bet_mean'] = list(ap15_bets.mean(axis=1))

In [15]:
apuestas_2015.drop(['BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'BETFAIR_EXCHANG', 'SONG'], axis=1, inplace=True)

In [16]:
apuestas_2015

                  country  codigo    bet_mean
0                  Sweden  532015    2.077222
1                  Russia  462015    4.161111
2                   Italy  342015    5.444444
3                 Belgium  172015   10.750000
4               Australia  132015   11.444444
5                 Estonia  242015   22.888889
6   Serbia and Montenegro  492015   32.722222
7                  Norway  422015   40.352941
8                  Latvia  352015   55.235294
9                  Israel  332015   57.000000
10             Azerbaijan  152015   58.500000
11                  Spain  522015   69.352941
12               Slovenia  512015   81.277778
13                Georgia  272015  104.333333
14         United Kingdom  582015  114.666667
15                 Greece  292015  138.764706
16                Romania  452015  154.705882
17                Armenia  122015  135.722222
18                Albania  102015  177.055556
19                 Cyprus  212015  170.833333
20                Hungary  302015  165.611111
21                 France  262015  182.277778
22              Lithuania  362015  200.666667
23                 Poland  432015  214.352941
24                Austria  142015  218.722222
25             Montenegro  402015  224.277778
26                Germany  282015  243.294118

### Odds 2016

In [39]:
apuestas_2016 = pd.read_clipboard(header=None, names=['SONG','BET365','UNIBET','YOU_WIN','BOYLE_SPORTS','CORAL',
                                                     'SKY_BET','BET_VICTOR','TITAN_BET','PAF','BETFAIR_SPORT',
                                                     'SPORTING_BET','INTE_TOPS','PADDY_POWER','BET_FRED','BETWAY',
                                                     'STAN_JAMES','BWIN','MATCH_BOOK','BETFAIR_EXCHANG','OTHER'])
apuestas_2016

,SONG,BET365,UNIBET,YOU_WIN,BOYLE_SPORTS,CORAL,SKY_BET,BET_VICTOR,TITAN_BET,PAF,...,SPORTING_BET,INTE_TOPS,PADDY_POWER,BET_FRED,BETWAY,STAN_JAMES,BWIN,MATCH_BOOK,BETFAIR_EXCHANG,OTHER
0,Russia Sergey Lazarev - You Are the Only One,1.90,1.4,1.53,1.4,1.3,1.75,1.57,1.85,1.44,...,1.36,1.5,1.85,1.75,1.75,1.36,2.00,2.0,2.10,2.04
1,Australia Dami Im - Sound of Silence,2.75,6.0,5.50,4.5,6.0,2.90,4.50,2.57,5.00,...,5.00,4.5,2.85,2.90,2.85,5.50,2.88,2.8,2.62,2.79
2,Ukraine Jamala - 1944,10.00,17.0,17.00,19.0,26.0,15.00,13.00,10.00,10.00,...,19.00,13.0,11.00,15.00,10.00,17.00,15.00,15.0,9.00,19.00
3,Sweden Frans - If I Were Sorry,17.00,21.0,15.00,23.0,34.0,18.00,34.00,23.00,19.00,...,15.00,21.0,17.00,18.00,19.00,19.00,26.00,21.0,17.00,40.00
4,France Amir - J'ai Cherché,17.00,34.0,26.00,51.0,51.0,16.00,34.00,15.00,21.00,...,29.00,26.0,18.00,16.00,17.00,21.00,26.00,19.0,15.00,32.00
5,Armenia Iveta Mukuchyan - LoveWave,34.00,51.0,34.00,67.0,101.0,31.00,41.00,41.00,29.00,...,51.00,26.0,30.00,31.00,26.00,26.00,41.00,34.0,41.00,71.00
6,Malta Ira Losco - Walk on Water,29.00,41.0,51.00,67.0,67.0,36.00,51.00,41.00,41.00,...,51.00,34.0,25.00,36.00,34.00,67.00,34.00,34.0,26.00,52.00
7,Bulgaria Poli Genova - If Love Was a Crime,81.00,26.0,34.00,67.0,34.0,81.00,51.00,101.00,34.00,...,34.00,41.0,100.00,81.00,101.00,26.00,101.00,101.0,126.00,238.00
8,United Kingdom J. & Jake - You're Not Alone,51.00,41.0,81.00,101.0,126.0,81.00,26.00,151.00,81.00,...,67.00,67.0,60.00,81.00,51.00,34.00,34.00,101.0,41.00,143.00
9,Spain Barei - Say Yay!,151.00,17.0,17.00,21.0,26.0,151.00,9.00,151.00,17.00,...,13.00,19.0,100.00,151.00,101.00,19.00,101.00,101.0,101.00,342.00
10,Netherlands Douwe Bob - Slow Down,51.00,81.0,41.00,201.0,201.0,36.00,151.00,71.00,151.00,...,81.00,101.0,55.00,36.00,51.00,67.00,67.00,51.0,51.00,133.00
11,Austria Zoë - Loin d'ici,81.00,151.0,101.00,126.0,151.0,67.00,151.00,101.00,67.00,...,101.00,101.0,80.00,67.00,67.00,51.00,81.00,51.0,67.00,190.00
12,Latvia Justs - Heartbeat,67.00,151.0,251.00,201.0,201.0,67.00,101.00,71.00,151.00,...,101.00,67.0,65.00,67.00,67.00,41.00,101.00,67.0,67.00,124.00
13,Belgium Laura Tesoro - What's the Pressure,67.00,101.0,201.00,201.0,201.0,51.00,201.00,101.00,151.00,...,81.00,101.0,65.00,51.00,51.00,67.00,101.00,67.0,51.00,190.00
14,Italy F. Michielin - No Degree of Separation,67.00,151.0,201.00,201.0,201.0,51.00,251.00,71.00,151.00,...,101.00,101.0,65.00,51.00,51.00,101.00,101.00,67.0,51.00,190.00
15,Cyprus Minus One - Alter Ego,151.00,67.0,101.00,126.0,101.0,151.00,151.00,101.00,67.00,...,81.00,67.0,150.00,151.00,126.00,67.00,101.00,101.0,151.00,285.00
16,Israel Hovi Star - Made of Stars,81.00,126.0,251.00,201.0,201.0,81.00,151.00,101.00,151.00,...,101.00,101.0,80.00,81.00,67.00,67.00,101.00,101.0,67.00,352.00
17,Poland Michał Szpak - Color of Your Life,126.00,101.0,251.00,201.0,251.0,126.00,201.00,201.00,201.00,...,151.00,151.0,100.00,126.00,101.00,101.00,101.00,101.0,101.00,390.00
18,Lithuania Montell - I've Been Waiting for Thi...,151.00,151.0,201.00,201.0,201.0,151.00,81.00,301.00,151.00,...,101.00,151.0,150.00,151.00,151.00,101.00,101.00,101.0,151.00,703.00
19,Serbia Sanja Vučić ZAA - Goodbye (Shelter),101.00,501.0,501.00,201.0,201.0,101.00,501.00,151.00,151.00,...,126.00,151.0,100.00,101.00,81.00,101.00,101.00,67.0,67.00,428.00
20,Azerbaijan Samra - Miracle,201.00,501.0,501.00,251.0,251.0,101.00,251.00,151.00,201.00,...,151.00,201.0,200.00,101.00,201.00,201.00,101.00,101.0,101.00,665.00
21,Hungary Freddie - Pioneer,201.00,501.0,501.00,301.0,201.0,151.00,501.00,201.00,301.00,...,201.00,201.0,200.00,151.00,151.00,201.00,101.00,101.0,151.00,950.00
22,Croatia Nina Kraljić - Lighthouse,201.00,501.0,501.00,251.0,201.0,201.00,501.00,151.00,301.00,...,251.00,251.0,200.00,201.00,201.00,151.00,101.00,101.0,201.00,798.00
23,Georgia Kocharov & Georgian Lolitaz - Midnigh...,251.00,251.0,501.00,301.0,201.0,251.00,301.00,301.00,201.00,...,251.00,201.0,225.00,251.00,201.00,201.00,101.00,301.0,201.00,950.00
24,Czech Republic Gabriela Gunčíková - I Stand,201.00,501.0,501.00,301.0,251.0,201.00,501.00,301.00,301.00,...,301.00,251.0,200.00,201.00,201.00,201.00,101.00,101.0,201.00,950.00
25,Germany Jamie-Lee Kriewitz - Ghost,251.00,501.0,501.00,251.0,501.0,301.00,201.00,301.00,251.00,...,301.00,251.0,230.00,301.00,151.00,201.00,101.00,101.0,201.00,504.00

In [40]:
lista_corregida = []
for song in apuestas_2016['SONG']:

    if (str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]) in paises_dobleword:
        lista_corregida.append(paises_dobleword[(str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0])])
    else:
        lista_corregida.append((str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]))
        
apuestas_2016['country'] = lista_corregida

In [41]:
lista_corregida = []
for pais in apuestas_2016['country']:
    if pais == 'Netherlans':
        lista_corregida.append('The Netherlans')
    else:
        lista_corregida.append(pais)
apuestas_2016['country'] = lista_corregida

In [42]:
codigo = []
for pais in apuestas_2016['country']:
    codigo.append(int(str(dict_codes[pais])+'2016'))
apuestas_2016['codigo'] = codigo

In [43]:
apuestas_2016.columns

Index(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'BETFAIR_EXCHANG', 'OTHER',
       'country', 'codigo'],
      dtype='object')

In [44]:
ap16_bets = apuestas_2016[['BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'BETFAIR_EXCHANG', 'OTHER']]

In [45]:
apuestas_2016['bet_mean'] = list(ap16_bets.mean(axis=1))

In [46]:
apuestas_2016.drop(['BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'BETFAIR_EXCHANG', 'OTHER', 'SONG'], axis=1, inplace=True)

In [47]:
apuestas_2016

                  country  codigo  bet_mean
0                  Russia  462016    1.6825
1               Australia  132016    3.8605
2                 Ukraine  572016   14.4375
3                  Sweden  532016   21.6500
4                  France  262016   24.9500
5                 Armenia  122016   41.8500
6                   Malta  372016   42.4000
7                Bulgaria  192016   76.9500
8          United Kingdom  582016   73.7000
9                   Spain  522016   86.4500
10            Netherlands  552016   86.6500
11                Austria  142016   96.5500
12                 Latvia  352016  104.7500
13                Belgium  172016  108.3500
14                  Italy  342016  114.7500
15                 Cyprus  212016  123.3500
16                 Israel  332016  127.6500
17                 Poland  432016  161.6500
18              Lithuania  362016  181.0500
19  Serbia and Montenegro  492016  191.6500
20             Azerbaijan  152016  232.9000
21                Hungary  302016  274.6500
22                Croatia  202016  273.5500
23                Georgia  272016  284.6500
24         Czech Republic  222016  299.6500
25                Germany  282016  283.6000

### 2017

In [110]:
apuestas_2017 = pd.read_clipboard(header=None, names=['SONG','BET365','UNIBET','YOU_WIN','BOYLE_SPORTS','CORAL',
                                                     'SKY_BET','BET_VICTOR','TITAN_BET','PAF','BETFAIR_SPORT',
                                                     'SPORTING_BET','INTE_TOPS','PADDY_POWER','BET_FRED','BETWAY',
                                                     'STAN_JAMES','BWIN','MATCH_BOOK'])
apuestas_2017

,SONG,BET365,UNIBET,YOU_WIN,BOYLE_SPORTS,CORAL,SKY_BET,BET_VICTOR,TITAN_BET,PAF,BETFAIR_SPORT,SPORTING_BET,INTE_TOPS,PADDY_POWER,BET_FRED,BETWAY,STAN_JAMES,BWIN,MATCH_BOOK
0,Bulgaria Kristian Kostov - Beautiful Mess,2.37,2.75,2.2,2.5,2.75,2.4,2.50,2.63,2.8,2.50,2.75,3.00,3.00,2.75,2.75,2.75,3.50,2.84
1,Portugal Salvador Sobral - Amar Pelos Dois,2.62,2.91,2.4,2.9,2.87,2.4,2.75,2.63,3.1,2.75,2.87,2.60,2.75,3.00,2.90,2.75,2.38,3.05
2,Italy Francesco Gabbani - Occidentali's Karma,6.50,8.00,7.0,8.0,9.00,7.5,7.50,8.00,8.0,7.50,9.00,2.75,3.00,8.00,7.00,7.00,2.88,9.00
3,Belgium Blanche - City Lights,6.50,8.00,7.0,7.0,6.50,7.0,6.50,7.00,6.5,6.50,6.50,15.00,17.00,7.00,7.00,6.00,15.00,10.00
4,Romania Ilinca feat. Alex Florea - Yodel It!,19.00,19.00,17.0,18.0,15.00,20.0,17.00,17.00,17.0,17.00,15.00,34.00,26.00,13.00,26.00,17.00,26.00,23.00
5,Sweden Robin Bengtsson - I Can't Go On,26.00,26.00,26.0,22.0,17.00,30.0,17.00,26.00,17.0,17.00,17.00,26.00,21.00,21.00,26.00,26.00,31.00,36.00
6,Croatia Jacques Houdek - My Friend,51.00,26.00,51.0,40.0,26.00,40.0,34.00,51.00,29.0,34.00,26.00,51.00,51.00,26.00,51.00,41.00,61.00,75.00
7,United Kingdom Jones - Never Give Up on You,67.00,51.00,67.0,50.0,51.00,50.0,29.00,51.00,51.0,29.00,51.00,29.00,26.00,21.00,51.00,67.00,51.00,95.00
8,Moldova Sunstroke Project - Hey Mamma,67.00,41.00,51.0,50.0,26.00,50.0,41.00,51.00,34.0,41.00,26.00,81.00,51.00,21.00,67.00,51.00,61.00,100.00
9,France Alma - Requiem,151.00,67.00,101.0,75.0,101.00,50.0,201.00,201.00,101.0,201.00,101.00,67.00,81.00,51.00,51.00,101.00,67.00,340.00
10,Armenia Artsvik - Fly With Me,201.00,81.00,151.0,125.0,101.00,50.0,101.00,201.00,101.0,101.00,101.00,67.00,81.00,101.00,67.00,101.00,51.00,500.00
11,Norway Jowst - Grab the Moment,101.00,67.00,101.0,75.0,101.00,70.0,151.00,151.00,101.0,151.00,101.00,201.00,151.00,101.00,101.00,101.00,76.00,310.00
12,Netherlands OG3NE - Lights And Shadows,301.00,41.00,201.0,75.0,151.00,150.0,201.00,151.00,101.0,201.00,151.00,81.00,101.00,101.00,67.00,101.00,101.00,350.00
13,Australia Isaiah - Don't Come Easy,301.00,101.00,151.0,200.0,201.00,100.0,151.00,201.00,101.0,151.00,201.00,126.00,101.00,101.00,101.00,101.00,151.00,710.00
14,Denmark Anja - Where I Am,301.00,81.00,301.0,60.0,201.00,100.0,251.00,201.00,201.0,251.00,201.00,126.00,101.00,101.00,101.00,151.00,NaN,670.00
15,Azerbaijan Dihaj - Skeletons,251.00,151.00,251.0,200.0,201.00,100.0,201.00,251.00,251.0,201.00,201.00,126.00,126.00,101.00,101.00,151.00,101.00,500.00
16,Hungary Joci Pápai - Origo,401.00,81.00,301.0,200.0,201.00,150.0,201.00,301.00,201.0,201.00,201.00,116.00,151.00,101.00,67.00,126.00,101.00,800.00
17,Germany Levina - Perfect Life,501.00,301.00,126.0,350.0,201.00,400.0,151.00,201.00,101.0,151.00,201.00,151.00,151.00,101.00,101.00,151.00,151.00,430.00
18,Poland Kasia Moś - Flashlight,401.00,301.00,301.0,350.0,301.00,250.0,201.00,201.00,201.0,201.00,301.00,201.00,101.00,101.00,101.00,251.00,151.00,640.00
19,Greece Demy - This is Love,501.00,151.00,251.0,300.0,251.00,300.0,251.00,251.00,201.0,251.00,251.00,251.00,201.00,101.00,101.00,251.00,201.00,600.00
20,Austria Nathan Trent - Running On Air,501.00,301.00,251.0,250.0,251.00,300.0,301.00,201.00,201.0,301.00,251.00,201.00,101.00,101.00,101.00,201.00,251.00,650.00
21,Belarus Naviband - Historyja majho žyccia,501.00,301.00,401.0,300.0,251.00,300.0,201.00,201.00,251.0,201.00,251.00,251.00,201.00,101.00,101.00,201.00,201.00,1000.00
22,Cyprus Hovig - Gravity,601.00,501.00,151.0,350.0,151.00,300.0,301.00,201.00,101.0,301.00,151.00,351.00,201.00,101.00,201.00,201.00,201.00,730.00
23,Ukraine O.Torvald - Time,751.00,501.00,201.0,400.0,301.00,400.0,301.00,301.00,501.0,301.00,301.00,251.00,201.00,101.00,101.00,201.00,201.00,700.00
24,Israel Imri Ziv - I Feel Alive,1001.00,201.00,501.0,400.0,251.00,500.0,401.00,301.00,351.0,401.00,251.00,201.00,101.00,101.00,101.00,251.00,201.00,1000.00
25,Spain Manel Navarro - Do It for Your Lover,1001.00,501.00,301.0,500.0,501.00,500.0,251.00,251.00,501.0,251.00,501.00,401.00,201.00,101.00,301.00,301.00,501.00,1000.00

In [111]:
lista_corregida = []
for song in apuestas_2017['SONG']:

    if (str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]) in paises_dobleword:
        lista_corregida.append(paises_dobleword[(str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0])])
    else:
        lista_corregida.append((str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]))
        
apuestas_2017['country'] = lista_corregida

In [112]:
lista_corregida = []
for pais in apuestas_2017['country']:
    if pais == 'Netherlans':
        lista_corregida.append('The Netherlans')
    else:
        lista_corregida.append(pais)
apuestas_2017['country'] = lista_corregida

In [113]:
codigo = []
for pais in apuestas_2017['country']:
    codigo.append(int(str(dict_codes[pais])+'2017'))
apuestas_2017['codigo'] = codigo

In [114]:
apuestas_2017.columns

Index(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'country', 'codigo'],
      dtype='object')

In [116]:
ap17_bets = apuestas_2017[['BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK']]

In [117]:
apuestas_2017['bet_mean'] = list(ap17_bets.mean(axis=1))

In [118]:
apuestas_2017.drop(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK'], axis=1, inplace=True)

In [119]:
apuestas_2017

           country  codigo    bet_mean
0         Bulgaria  192017    2.707778
1         Portugal  442017    2.757222
2            Italy  342017    6.979444
3          Belgium  172017    8.444444
4          Romania  452017   19.777778
5           Sweden  532017   23.777778
6          Croatia  202017   42.444444
7   United Kingdom  582017   49.277778
8          Moldova  382017   50.555556
9           France  262017  117.111111
10         Armenia  122017  126.777778
11          Norway  422017  122.833333
12     Netherlands  552017  145.888889
13       Australia  132017  180.555556
14         Denmark  232017  199.941176
15      Azerbaijan  152017  192.500000
16         Hungary  302017  216.722222
17         Germany  282017  217.777778
18          Poland  432017  253.055556
19          Greece  292017  259.166667
20         Austria  142017  261.944444
21         Belarus  162017  289.722222
22          Cyprus  212017  283.055556
23         Ukraine  572017  334.166667
24          Israel  332017  361.944444
25           Spain  522017  436.944444

### 2018

In [121]:
apuestas_2018 = pd.read_clipboard(header=None, names=['SONG','BET365','UNIBET','YOU_WIN','BOYLE_SPORTS','CORAL',
                                                     'SKY_BET','BET_VICTOR','TITAN_BET','PAF','BETFAIR_SPORT',
                                                     'SPORTING_BET','INTE_TOPS','PADDY_POWER','BET_FRED','BETWAY',
                                                     'STAN_JAMES','BWIN', 'other'])
apuestas_2018

,SONG,BET365,UNIBET,YOU_WIN,BOYLE_SPORTS,CORAL,SKY_BET,BET_VICTOR,TITAN_BET,PAF,BETFAIR_SPORT,SPORTING_BET,INTE_TOPS,PADDY_POWER,BET_FRED,BETWAY,STAN_JAMES,BWIN,other
0,Cyprus Eleni Foureira - Fuego,2.00,2.15,2.2,2.25,2.0,2.25,2.1,2.1,2.20,2.25,2.20,2.10,2.25,2.20,2.2,2.38,2.32,2.84
1,Israel Netta - Toy,3.25,3.60,3.5,3.25,3.4,3.25,3.2,3.1,3.25,3.25,3.25,3.75,3.50,3.25,4.0,3.25,3.75,3.05
2,Germany M. Schulte - You Let Me Walk Alone,7.50,8.50,6.5,7.00,7.5,8.00,7.0,8.0,6.50,8.00,6.50,23.00,6.50,7.00,26.0,8.00,8.40,9.00
3,Ireland Ryan O'Shaughnessy - Together,17.00,19.00,13.0,15.00,17.0,18.00,15.0,18.0,12.00,18.00,12.00,8.00,15.00,15.00,8.0,15.00,19.00,10.00
4,Estonia Elina Nechayeva - La Forza,34.00,26.00,26.0,21.00,26.0,33.00,26.0,25.0,26.00,33.00,26.00,31.00,34.00,21.00,29.0,26.00,38.00,23.00
5,Sweden Benjamin Ingrosso - Dance You Off,41.00,40.00,41.0,34.00,51.0,36.00,41.0,35.0,34.00,36.00,34.00,21.00,34.00,29.00,26.0,34.00,48.00,36.00
6,Lithuania I. Zasimauskaitė - When We're Old,51.00,55.00,41.0,41.00,34.0,41.00,41.0,30.0,34.00,41.00,34.00,23.00,41.00,41.00,21.0,41.00,70.00,75.00
7,United Kingdom SuRie - Storm,51.00,41.00,34.0,21.00,51.0,31.00,41.0,50.0,19.00,31.00,19.00,201.00,11.00,29.00,51.0,17.00,60.00,95.00
8,Norway Rybak - That's How You Write a Song,81.00,60.00,81.0,41.00,67.0,41.00,41.0,35.0,51.00,41.00,51.00,29.00,51.00,41.00,34.0,67.00,100.00,100.00
9,France Madame Monsieur - Mercy,101.00,60.00,51.0,67.00,51.0,51.00,67.0,50.0,51.00,51.00,51.00,16.00,41.00,51.00,17.0,67.00,65.00,340.00
10,Italy Meta & Moro - Non Mi Avete Fatto Niente,101.00,70.00,41.0,81.00,67.0,71.00,81.0,25.0,51.00,71.00,51.00,23.00,51.00,41.00,21.0,51.00,140.00,500.00
11,Australia Jessica Mauboy - We Got Love,101.00,75.00,67.0,51.00,101.0,61.00,71.0,75.0,29.00,61.00,29.00,39.00,51.00,51.00,51.0,67.00,120.00,310.00
12,Finland Saara Aalto - Monsters,101.00,50.00,101.0,51.00,101.0,61.00,67.0,50.0,67.00,61.00,67.00,51.00,81.00,51.00,41.0,67.00,150.00,350.00
13,Czech Republic Mikolas Josef - Lie To Me,101.00,75.00,81.0,67.00,67.0,51.00,76.0,70.0,67.00,51.00,67.00,51.00,51.00,67.00,51.0,101.00,110.00,710.00
14,Moldova DoReDos - My Lucky Day,101.00,65.00,101.0,101.00,101.0,51.00,101.0,50.0,67.00,51.00,67.00,51.00,81.00,51.00,51.0,67.00,140.00,670.00
15,Bulgaria Equinox - Bones,201.00,120.00,151.0,67.00,67.0,86.00,126.0,100.0,101.00,86.00,101.00,51.00,101.00,67.00,51.0,67.00,230.00,500.00
16,Denmark Rasmussen - Higher Ground,201.00,130.00,151.0,126.00,101.0,51.00,101.0,65.0,126.00,51.00,126.00,67.00,101.00,67.00,67.0,67.00,200.00,800.00
17,Hungary AWS - Viszlát Nyár,176.00,130.00,151.0,101.00,101.0,76.00,151.0,90.0,101.00,76.00,101.00,67.00,101.00,81.00,67.0,101.00,300.00,430.00
18,Netherlands Waylon - Outlaw In 'Em,201.00,150.00,151.0,151.00,201.0,76.00,151.0,150.0,126.00,76.00,126.00,126.00,101.00,101.00,151.0,101.00,190.00,640.00
19,Austria Cesár Sampson - Nobody But You,301.00,150.00,251.0,101.00,101.0,71.00,126.0,125.0,151.00,71.00,151.00,101.00,151.00,126.00,151.0,101.00,250.00,600.00
20,Ukraine Mélovin - Under the Ladder,401.00,240.00,501.0,101.00,201.0,101.00,81.0,150.0,201.00,101.00,201.00,126.00,251.00,126.00,101.0,101.00,830.00,650.00
21,Spain Amaia & Alfred - Tu Canción,501.00,220.00,501.0,151.00,201.0,101.00,201.0,125.0,151.00,101.00,151.00,101.00,251.00,151.00,151.0,101.00,1000.00,1000.00
22,Portugal Cláudia Pascoal - O Jardim,751.00,300.00,501.0,201.00,301.0,201.00,201.0,250.0,201.00,201.00,201.00,151.00,251.00,251.00,151.0,101.00,650.00,730.00
23,Albania Eugent Bushpepa - Mall,501.00,500.00,501.0,301.00,301.0,151.00,201.0,400.0,201.00,151.00,201.00,201.00,251.00,151.00,201.0,101.00,770.00,700.00
24,"Slovenia Lea Sirk - Hvala, ne!",1001.00,350.00,501.0,301.00,301.0,201.00,401.0,200.0,301.00,201.00,301.00,301.00,251.00,301.00,201.0,101.00,850.00,1000.00
25,Serbia Sanja Ilić & Balkanika - Nova Deca,1001.00,500.00,501.0,501.00,301.0,201.00,301.0,500.0,151.00,201.00,151.00,401.00,251.00,301.00,201.0,101.00,1000.00,1000.00

In [122]:
apuestas_2018.columns

Index(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'other'],
      dtype='object')

In [123]:
lista_corregida = []
for song in apuestas_2018['SONG']:

    if (str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]) in paises_dobleword:
        lista_corregida.append(paises_dobleword[(str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0])])
    else:
        lista_corregida.append((str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]))
        
apuestas_2018['country'] = lista_corregida

In [124]:
lista_corregida = []
for pais in apuestas_2018['country']:
    if pais == 'Netherlans':
        lista_corregida.append('The Netherlans')
    else:
        lista_corregida.append(pais)
apuestas_2018['country'] = lista_corregida

In [125]:
codigo = []
for pais in apuestas_2018['country']:
    codigo.append(int(str(dict_codes[pais])+'2018'))
apuestas_2018['codigo'] = codigo

In [127]:
ap18_bets = apuestas_2018[['BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'other']]

In [128]:
apuestas_2018['bet_mean'] = list(ap18_bets.mean(axis=1))

In [129]:
apuestas_2018.drop(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'other'], axis=1, inplace=True)

In [130]:
apuestas_2018

                  country  codigo    bet_mean
0                  Cyprus  212018    2.221667
1                  Israel  332018    3.380556
2                 Germany  282018    9.383333
3                 Ireland  322018   14.666667
4                 Estonia  242018   28.000000
5                  Sweden  532018   36.166667
6               Lithuania  362018   41.944444
7          United Kingdom  582018   47.388889
8                  Norway  422018   56.222222
9                  France  262018   69.333333
10                  Italy  342018   85.388889
11              Australia  132018   78.333333
12                Finland  252018   87.111111
13         Czech Republic  222018  106.333333
14                Moldova  382018  109.277778
15               Bulgaria  192018  126.277778
16                Denmark  232018  144.333333
17                Hungary  302018  133.388889
18            Netherlands  552018  164.944444
19                Austria  142018  171.055556
20                Ukraine  572018  248.000000
21                  Spain  522018  286.611111
22               Portugal  442018  310.777778
23                Albania  102018  321.333333
24               Slovenia  512018  392.444444
25  Serbia and Montenegro  492018  420.222222

### 2019

In [131]:
apuestas_2019 = pd.read_clipboard(header=None, names=['SONG','BET365','UNIBET','YOU_WIN','BOYLE_SPORTS','CORAL',
                                                     'SKY_BET','BET_VICTOR','TITAN_BET','PAF','BETFAIR_SPORT',
                                                     'SPORTING_BET','INTE_TOPS','PADDY_POWER','BET_FRED','BETWAY',
                                                     'STAN_JAMES','BWIN','MATCH_BOOK'])
apuestas_2019

,SONG,BET365,UNIBET,YOU_WIN,BOYLE_SPORTS,CORAL,SKY_BET,BET_VICTOR,TITAN_BET,PAF,BETFAIR_SPORT,SPORTING_BET,INTE_TOPS,PADDY_POWER,BET_FRED,BETWAY,STAN_JAMES,BWIN,MATCH_BOOK
0,Netherlands Duncan Laurence - Arcade,1.5,1.63,1.55,1.5,1.5,1.55,1.65,1.55,1.5,1.57,1.71,1.44,1.57,1.57,3.5,1.57,1.5,1.66
1,Italy Mahmood - Soldi,5.0,8.00,8.00,6.0,8.0,9.00,17.00,6.00,8.0,7.00,19.00,8.00,6.00,6.00,15.0,9.00,8.0,10.00
2,Switzerland Luca Hänni - She Got Me,6.0,13.00,11.00,6.0,11.0,7.50,8.00,8.00,11.0,9.00,8.00,7.00,8.50,8.50,21.0,11.00,10.0,14.00
3,Australia Kate Miller-Heidke - Zero Gravity,11.0,14.00,13.00,10.0,13.0,9.00,5.00,13.00,15.0,11.00,7.00,8.00,10.00,10.00,17.0,11.00,15.0,14.00
4,Sweden John Lundvik - Too Late for Love,15.0,17.00,15.00,17.0,15.0,21.00,11.00,15.00,21.0,15.00,12.00,14.00,19.00,19.00,5.0,21.00,21.0,19.00
5,Norway KEiiNO - Spirit in the Sky,34.0,25.00,21.00,21.0,21.0,26.00,26.00,20.00,26.0,26.00,26.00,14.00,17.00,17.00,101.0,21.00,9.0,40.00
6,Azerbaijan Chingiz - Truth,34.0,33.00,51.00,34.0,51.0,31.00,26.00,20.00,41.0,21.00,23.00,25.00,34.00,34.00,9.0,51.00,34.0,48.00
7,Russia Sergey Lazarev - Scream,41.0,50.00,51.00,34.0,51.0,26.00,19.00,45.00,67.0,41.00,26.00,25.00,51.00,51.00,8.0,51.00,51.0,60.00
8,Iceland Hatari - Hatrið mun sigra,51.0,40.00,51.00,51.0,51.0,51.00,19.00,35.00,51.0,67.00,19.00,25.00,81.00,81.00,26.0,51.00,67.0,80.00
9,France Bilal Hassani - Roi,67.0,75.00,51.00,51.0,51.0,51.00,34.00,60.00,67.0,81.00,34.00,25.00,101.00,101.00,5.0,51.00,67.0,95.00
10,Denmark Leonora - Love Is Forever,151.0,100.00,151.00,81.0,151.0,101.00,126.00,100.00,101.0,67.00,101.00,25.00,34.00,34.00,101.0,51.00,51.0,190.00
11,Cyprus Tamta - Replay,151.0,110.00,101.00,101.0,101.0,126.00,151.00,100.00,101.0,67.00,126.00,25.00,51.00,51.00,41.0,51.00,101.0,190.00
12,Estonia Victor Crone - Storm,151.0,110.00,81.00,151.0,81.0,101.00,301.00,100.00,251.0,101.00,251.00,25.00,81.00,81.00,151.0,51.00,101.0,180.00
13,Spain Miki - La Venda,251.0,180.00,151.00,151.0,151.0,176.00,151.00,125.00,101.0,151.00,126.00,50.00,101.00,101.00,81.0,101.00,101.0,290.00
14,North Macedonia Tamara Todevska - Proud,501.0,200.00,151.00,81.0,151.0,151.00,201.00,150.00,251.0,201.00,151.00,100.00,126.00,126.00,81.0,101.00,101.0,430.00
15,Czech Republic L. Malawi - Friend of a Friend,501.0,180.00,151.00,201.0,151.0,176.00,201.00,150.00,151.0,151.00,151.00,50.00,126.00,126.00,81.0,101.00,201.0,460.00
16,Malta Michela - Chameleon,501.0,250.00,151.00,201.0,151.0,201.00,126.00,150.00,101.0,201.00,81.00,100.00,201.00,201.00,17.0,101.00,151.0,820.00
17,Greece Katerine Duska - Better Love,501.0,220.00,151.00,201.0,151.0,251.00,151.00,150.00,151.0,251.00,126.00,50.00,201.00,201.00,41.0,101.00,101.0,750.00
18,Serbia Nevena Božović - Kruna,751.0,250.00,151.00,301.0,151.0,176.00,201.00,200.00,251.0,201.00,151.00,50.00,201.00,201.00,151.0,101.00,101.0,1000.00
19,United Kingdom Michael Rice - Bigger Than Us,501.0,350.00,251.00,201.0,251.0,501.00,201.00,200.00,251.0,251.00,151.00,50.00,101.00,101.00,67.0,101.00,151.0,800.00
20,Slovenia Zala Kralj & Gašper Šantl - Sebi,751.0,300.00,151.00,301.0,151.0,501.00,201.00,200.00,251.0,201.00,251.00,100.00,201.00,201.00,101.0,101.00,251.0,1000.00
21,Belarus Zena - Like It,751.0,300.00,201.00,301.0,201.0,301.00,301.00,200.00,251.0,201.00,251.00,250.00,201.00,201.00,201.0,101.00,151.0,700.00
22,Israel Kobi Marimi - Home,751.0,350.00,301.00,301.0,301.0,251.00,301.00,300.00,251.0,251.00,251.00,250.00,151.00,151.00,201.0,101.00,251.0,930.00
23,Albania Jonida Maliqi - Ktheju Tokës,1001.0,350.00,251.00,301.0,251.0,501.00,301.00,300.00,251.0,251.00,251.00,250.00,201.00,201.00,151.0,101.00,201.0,1000.00
24,Germany S!sters - Sister,751.0,400.00,501.00,301.0,501.0,501.00,301.00,400.00,251.0,201.00,251.00,100.00,151.00,151.00,201.0,101.00,251.0,1000.00
25,San Marino Serhat - Say Na Na Na,751.0,400.00,501.00,301.0,501.0,501.00,301.00,400.00,251.0,251.00,251.00,100.00,201.00,201.00,201.0,101.00,251.0,1000.00

In [132]:
lista_corregida = []
for song in apuestas_2019['SONG']:

    if (str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]) in paises_dobleword:
        lista_corregida.append(paises_dobleword[(str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0])])
    else:
        lista_corregida.append((str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]))
        
apuestas_2019['country'] = lista_corregida

In [133]:
lista_corregida = []
for pais in apuestas_2019['country']:
    if pais == 'Netherlans':
        lista_corregida.append('The Netherlans')
    else:
        lista_corregida.append(pais)
apuestas_2019['country'] = lista_corregida

In [134]:
codigo = []
for pais in apuestas_2019['country']:
    codigo.append(int(str(dict_codes[pais])+'2019'))
apuestas_2019['codigo'] = codigo

In [135]:
apuestas_2019.columns

Index(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'country', 'codigo'],
      dtype='object')

In [136]:
ap19_bets = apuestas_2019[['UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK']]

In [137]:
apuestas_2019['bet_mean'] = list(ap19_bets.mean(axis=1))

In [138]:
apuestas_2019.drop(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN','MATCH_BOOK'], axis=1, inplace=True)

In [139]:
apuestas_2019

                  country  codigo    bet_mean
0             Netherlands  552019    1.677647
1                   Italy  342019    9.294118
2             Switzerland  542019   10.147059
3               Australia  132019   11.470588
4                  Sweden  532019   16.294118
5                  Norway  422019   26.882353
6              Azerbaijan  152019   33.294118
7                  Russia  462019   41.588235
8                 Iceland  312019   49.764706
9                  France  262019   58.823529
10                Denmark  232019   92.058824
11                 Cyprus  212019   93.764706
12                Estonia  242019  129.294118
13                  Spain  522019  134.588235
14        North Macedonia  412019  161.941176
15         Czech Republic  222019  165.176471
16                  Malta  372019  188.470588
17                 Greece  292019  191.058824
18  Serbia and Montenegro  492019  225.764706
19         United Kingdom  582019  234.058824
20               Slovenia  512019  262.529412
21                Belarus  162019  253.705882
22                 Israel  332019  287.823529
23                Albania  102019  300.764706
24                Germany  282019  327.235294
25             San Marino  472019  336.058824

### 2021

In [140]:
apuestas_2021 = pd.read_clipboard(header=None, names=['SONG','BET365','UNIBET','YOU_WIN','BOYLE_SPORTS','CORAL',
                                                     'SKY_BET','BET_VICTOR','TITAN_BET','PAF','BETFAIR_SPORT',
                                                     'SPORTING_BET','INTE_TOPS','PADDY_POWER','BET_FRED','BETWAY',
                                                     'STAN_JAMES','BWIN','MATCH_BOOK','other'])
apuestas_2021

,SONG,BET365,UNIBET,YOU_WIN,BOYLE_SPORTS,CORAL,SKY_BET,BET_VICTOR,TITAN_BET,PAF,BETFAIR_SPORT,SPORTING_BET,INTE_TOPS,PADDY_POWER,BET_FRED,BETWAY,STAN_JAMES,BWIN,MATCH_BOOK,other
0,Italy Måneskin - Zitti e buoni,3.25,3.25,2.75,3.5,3.40,2.65,3.35,3.25,2.8,2.80,3.0,3.0,3.25,3.55,3.4,3.5,3.5,3.24,3.6
1,France Barbara Pravi - Voilà,3.25,3.25,4.50,4.0,3.00,4.30,3.85,3.50,4.5,4.25,4.5,3.5,3.25,3.95,4.0,3.5,4.0,4.50,4.1
2,Malta Destiny - Je Me Casse,5.00,5.00,5.50,5.0,4.75,5.10,5.00,4.50,6.0,6.00,5.5,5.0,4.50,5.30,5.0,5.0,4.5,5.00,5.3
3,Ukraine Go_A - Shum,17.00,18.00,8.00,17.0,12.00,12.00,17.00,11.00,8.0,8.00,8.0,12.0,11.00,19.00,13.0,17.0,15.0,26.00,19.0
4,Finland Blind Channel - Dark Side,15.00,11.00,21.00,13.0,11.00,8.50,8.00,11.00,16.0,14.00,26.0,10.0,9.00,16.00,13.0,9.0,11.0,67.00,16.0
5,Switzerland Gjon's Tears - Tout l'univers,17.00,18.00,11.00,17.0,21.00,15.00,18.00,15.00,11.0,11.00,12.0,16.0,17.00,19.00,19.0,13.0,17.0,19.00,19.0
6,Iceland Daði & Gagnamagnið - 10 Years,17.00,21.00,17.00,17.0,21.00,18.00,20.00,15.00,16.0,16.00,19.0,16.0,21.00,18.00,17.0,17.0,17.0,13.00,19.0
7,Lithuania The Roop - Discoteque,41.00,51.00,61.00,41.0,41.00,34.00,40.00,34.00,61.0,49.00,67.0,50.0,41.00,46.00,34.0,26.0,34.0,34.00,55.0
8,Sweden Tusse - Voices,41.00,51.00,91.00,41.0,41.00,50.00,35.00,26.00,56.0,56.00,67.0,25.0,41.00,50.00,26.0,17.0,26.0,67.00,50.0
9,San Marino Senhit feat. Flo Rida - Adrenalina,67.00,81.00,67.00,81.0,81.00,65.00,60.00,51.00,46.0,46.00,67.0,50.0,41.00,90.00,34.0,81.0,34.0,26.00,100.0
10,Norway TIX - Fallen Angel,67.00,81.00,126.00,67.0,51.00,50.00,55.00,51.00,81.0,49.00,101.0,50.0,67.00,90.00,67.0,34.0,51.0,101.00,90.0
11,Portugal Black Mamba - Love Is On My Side,101.00,81.00,51.00,101.0,81.00,45.00,40.00,101.00,41.0,41.00,51.0,75.0,81.00,130.00,67.0,101.0,51.0,151.00,100.0
12,Bulgaria Victoria - Growing Up Is Getting Old,101.00,101.00,101.00,101.0,101.00,90.00,85.00,67.00,61.0,61.00,67.0,75.0,81.00,150.00,41.0,101.0,101.0,17.00,150.0
13,Cyprus Elena Tsagrinou - El Diablo,151.00,151.00,111.00,151.0,101.00,80.00,100.00,101.00,61.0,61.00,67.0,75.0,126.00,180.00,81.0,51.0,101.0,11.00,220.0
14,Azerbaijan Efendi - Mata Hari,101.00,126.00,201.00,101.0,126.00,150.00,200.00,151.00,126.0,126.00,101.0,100.0,101.00,140.00,81.0,151.0,101.0,101.00,130.0
15,Greece Stefania - Last Dance,201.00,151.00,201.00,151.0,151.00,150.00,150.00,151.00,126.0,126.00,101.0,75.0,176.00,260.00,151.0,151.0,101.0,67.00,290.0
16,Russia Manizha - Russian Woman,251.00,151.00,201.00,251.0,126.00,150.00,200.00,201.00,126.0,126.00,101.0,100.0,151.00,290.00,151.0,151.0,101.0,51.00,370.0
17,Serbia Hurricane - Loco Loco,501.00,201.00,151.00,351.0,201.00,150.00,200.00,201.00,151.0,111.00,101.0,100.0,251.00,300.00,151.0,101.0,101.0,301.00,470.0
18,Israel Eden Alene - Set Me Free,501.00,251.00,301.00,351.0,251.00,250.00,300.00,251.00,251.0,251.00,101.0,100.0,251.00,300.00,201.0,101.0,101.0,101.00,730.0
19,Netherlands J. Macrooy - Birth Of A New Age,201.00,501.00,501.00,251.0,401.00,300.00,500.00,251.00,401.0,401.00,501.0,250.0,251.00,280.00,151.0,101.0,126.0,501.00,370.0
20,Belgium Hooverphonic - The Wrong Place,751.00,251.00,501.00,601.0,301.00,300.00,350.00,501.00,401.0,401.00,301.0,100.0,251.00,500.00,201.0,251.0,126.0,101.00,1000.0
21,United Kingdom James Newman - Embers,751.00,501.00,301.00,601.0,751.00,500.00,500.00,251.00,301.0,301.00,501.0,100.0,201.00,500.00,67.0,101.0,101.0,151.00,1000.0
22,Moldova Natalia Gordienko - Sugar,751.00,501.00,501.00,601.0,501.00,250.00,500.00,501.00,401.0,401.00,301.0,100.0,251.00,500.00,201.0,301.0,126.0,101.00,1000.0
23,Germany Jendrik - I Don't Feel Hate,501.00,501.00,501.00,351.0,751.00,400.00,500.00,201.00,501.0,451.00,501.0,250.0,401.00,300.00,251.0,301.0,126.0,151.00,640.0
24,Spain Blas Cantó - Voy A Quedarme,751.00,501.00,501.00,601.0,751.00,350.00,500.00,501.00,501.0,501.00,501.0,250.0,251.00,500.00,251.0,501.0,126.0,501.00,1000.0
25,Albania Anxhela Peristeri - Karma,751.00,501.00,501.00,601.0,501.00,250.00,500.00,501.00,501.0,501.00,501.0,250.0,501.00,500.00,251.0,1001.0,126.0,501.00,1000.0

In [141]:
lista_corregida = []
for song in apuestas_2021['SONG']:

    if (str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]) in paises_dobleword:
        lista_corregida.append(paises_dobleword[(str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0])])
    else:
        lista_corregida.append((str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]))
        
apuestas_2021['country'] = lista_corregida

In [142]:
lista_corregida = []
for pais in apuestas_2021['country']:
    if pais == 'Netherlans':
        lista_corregida.append('The Netherlans')
    else:
        lista_corregida.append(pais)
apuestas_2021['country'] = lista_corregida

In [143]:
lista_corregida = []
for pais in apuestas_2021['country']:
    if pais == '"':
        lista_corregida.append('Switzerland')
    else:
        lista_corregida.append(pais)
apuestas_2021['country'] = lista_corregida

In [144]:
codigo = []
for pais in apuestas_2021['country']:
    codigo.append(int(str(dict_codes[pais])+'2021'))
apuestas_2021['codigo'] = codigo

In [145]:
apuestas_2021.columns

Index(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'other', 'country', 'codigo'],
      dtype='object')

In [146]:
ap21_bets = apuestas_2021[['BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'other']]

In [147]:
apuestas_2021['bet_mean'] = list(ap21_bets.mean(axis=1))

In [148]:
apuestas_2021.drop(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'other'], axis=1, inplace=True)

In [149]:
apuestas_2021

                  country  codigo    bet_mean
0                   Italy  342021    3.212632
1                  France  262021    3.878947
2                   Malta  372021    5.102632
3                 Ukraine  572021   14.105263
4                 Finland  252021   16.078947
5             Switzerland  542021   16.052632
6                 Iceland  312021   17.631579
7               Lithuania  362021   44.210526
8                  Sweden  532021   45.105263
9              San Marino  472021   61.473684
10                 Norway  422021   69.947368
11               Portugal  442021   78.421053
12               Bulgaria  192021   86.947368
13                 Cyprus  212021  104.210526
14             Azerbaijan  152021  127.052632
15                 Greece  292021  154.210526
16                 Russia  462021  171.000000
17  Serbia and Montenegro  492021  215.473684
18                 Israel  332021  260.210526
19            Netherlands  552021  328.368421
20                Belgium  172021  378.368421
21         United Kingdom  582021  393.684211
22                Moldova  382021  409.947368
23                Germany  282021  398.894737
24                  Spain  522021  491.526316
25                Albania  102021  512.578947

### 2022

In [151]:
apuestas_2022 = pd.read_clipboard(header=None, names=['SONG','BET365','UNIBET','YOU_WIN','BOYLE_SPORTS','CORAL',
                                                     'SKY_BET','BET_VICTOR','TITAN_BET','PAF','BETFAIR_SPORT',
                                                     'SPORTING_BET','INTE_TOPS','PADDY_POWER','BET_FRED','BETWAY',
                                                     'STAN_JAMES','BWIN','MATCH_BOOK'])
apuestas_2022

,SONG,BET365,UNIBET,YOU_WIN,BOYLE_SPORTS,CORAL,SKY_BET,BET_VICTOR,TITAN_BET,PAF,BETFAIR_SPORT,SPORTING_BET,INTE_TOPS,PADDY_POWER,BET_FRED,BETWAY,STAN_JAMES,BWIN,MATCH_BOOK
0,Ukraine Kalush Orchestra - Stefania,1.25,1.22,1.29,1.25,1.34,1.33,1.30,1.22,1.29,1.25,1.25,1.34,1.29,1.3,1.3,2.20,1.3,1.34
1,Sweden Cornelia Jakobs - Hold Me Closer,5.00,5.10,7.25,6.50,6.00,7.00,4.33,6.50,8.00,5.50,5.50,7.60,7.00,4.3,4.3,6.50,5.0,8.00
2,Spain Chanel - SloMo,10.00,13.00,13.00,15.00,13.00,8.00,10.00,11.00,15.00,14.00,10.00,19.00,11.00,10.0,10.0,31.00,10.0,18.00
3,United Kingdom Sam Ryder - Space Man,13.00,15.00,8.75,13.00,15.00,13.00,15.00,15.00,7.00,10.00,11.00,22.00,12.00,12.0,12.0,18.00,15.0,25.00
4,Italy Mahmood & Blanco - Brividi,41.00,51.00,14.00,34.00,37.00,34.00,26.00,40.00,15.00,23.00,41.00,55.00,34.00,41.0,41.0,4.33,34.0,55.00
5,Norway Subwoolfer - Give That Wolf a Banana,101.00,101.00,73.00,67.00,81.00,101.00,21.00,65.00,67.00,23.00,41.00,200.00,67.00,41.0,41.0,21.00,67.0,210.00
6,Poland Ochman - River,101.00,101.00,58.00,67.00,81.00,67.00,67.00,100.00,51.00,81.00,51.00,300.00,81.00,67.0,67.0,21.00,51.0,300.00
7,Serbia Konstrakta - In Corpore Sano,67.00,101.00,51.00,101.00,131.00,81.00,126.00,65.00,51.00,51.00,51.00,300.00,81.00,41.0,41.0,81.00,67.0,300.00
8,Greece Amanda Tenfjord - Die Together,101.00,101.00,69.00,101.00,101.00,67.00,151.00,100.00,51.00,56.00,81.00,260.00,81.00,67.0,67.0,17.00,101.0,270.00
9,Moldova Z. şi Zdub & A. Brothers - Trenuleţul,151.00,81.00,101.00,51.00,81.00,81.00,81.00,150.00,67.00,71.00,67.00,230.00,51.00,67.0,67.0,151.00,101.0,160.00
10,Netherlands S10 - De Diepte,101.00,101.00,76.00,101.00,131.00,101.00,151.00,100.00,151.00,101.00,81.00,300.00,151.00,67.0,67.0,41.00,101.0,380.00
11,Finland The Rasmus - Jezebel,501.00,201.00,251.00,151.00,201.00,126.00,81.00,200.00,251.00,176.00,226.00,500.00,201.00,81.0,81.0,101.00,101.0,600.00
12,Estonia Stefan - Hope,251.00,201.00,301.00,101.00,171.00,251.00,201.00,250.00,301.00,201.00,101.00,500.00,101.00,101.0,101.0,151.00,NaN,470.00
13,Australia Sheldon Riley - Not the Same,501.00,226.00,200.00,101.00,151.00,126.00,151.00,200.00,251.00,201.00,226.00,500.00,301.00,201.0,201.0,61.00,101.0,620.00
14,Czech Republic We Are Domi - Lights Off,501.00,301.00,301.00,501.00,301.00,201.00,401.00,250.00,151.00,226.00,126.00,500.00,301.00,201.0,201.0,301.00,101.0,1000.00
15,"Portugal Maro - Saudade, saudade",501.00,301.00,301.00,501.00,201.00,251.00,201.00,250.00,301.00,301.00,251.00,500.00,301.00,251.0,251.0,71.00,301.0,1000.00
16,Armenia Rosa Linn - Snap,501.00,301.00,301.00,501.00,301.00,251.00,201.00,250.00,301.00,251.00,251.00,500.00,301.00,251.0,251.0,101.00,NaN,970.00
17,Germany Malik Harris - Rockstars,501.00,301.00,201.00,201.00,501.00,301.00,401.00,250.00,501.00,201.00,201.00,500.00,251.00,301.0,301.0,201.00,301.0,600.00
18,France Alvan & Ahez - Fulenn,751.00,251.00,351.00,501.00,251.00,251.00,301.00,300.00,301.00,251.00,251.00,500.00,301.00,301.0,301.0,76.00,301.0,1000.00
19,Azerbaijan Nadir Rustamli - Fade To Black,501.00,351.00,351.00,501.00,301.00,501.00,401.00,300.00,301.00,251.00,301.00,500.00,301.00,301.0,301.0,101.00,NaN,1000.00
20,Iceland Systur - Með hækkandi sól,1001.00,351.00,351.00,501.00,351.00,501.00,301.00,300.00,301.00,251.00,301.00,500.00,301.00,301.0,301.0,201.00,NaN,1000.00
21,Romania WRS - Llámame,1001.00,501.00,601.00,501.00,301.00,301.00,401.00,250.00,201.00,301.00,301.00,500.00,301.00,301.0,301.0,301.00,301.0,1000.00
22,Switzerland Marius Bear - Boys Do Cry,1001.00,351.00,401.00,501.00,301.00,401.00,401.00,500.00,401.00,226.00,301.00,500.00,301.00,401.0,401.0,81.00,NaN,1000.00
23,Belgium Jérémie Makiese - Miss You,1001.00,401.00,401.00,501.00,301.00,501.00,401.00,500.00,501.00,201.00,301.00,500.00,301.00,401.0,401.0,81.00,301.0,1000.00
24,Lithuania Monika Liu - Sentimentai,1001.00,501.00,451.00,501.00,301.00,301.00,301.00,300.00,501.00,301.00,501.00,500.00,301.00,401.0,401.0,501.00,NaN,1000.00

In [152]:
lista_corregida = []
for song in apuestas_2022['SONG']:

    if (str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]) in paises_dobleword:
        lista_corregida.append(paises_dobleword[(str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0])])
    else:
        lista_corregida.append((str(song.split(" ")).replace('\\xa0'," ").replace("'", '').strip('][').split(', ')[0].strip().split(" ")[0]))
        
apuestas_2022['country'] = lista_corregida

In [153]:
lista_corregida = []
for pais in apuestas_2022['country']:
    if pais == 'Netherlans':
        lista_corregida.append('The Netherlans')
    else:
        lista_corregida.append(pais)
apuestas_2022['country'] = lista_corregida

In [154]:
lista_corregida = []
for pais in apuestas_2022['country']:
    if pais == '"':
        lista_corregida.append('Switzerland')
    else:
        lista_corregida.append(pais)
apuestas_2022['country'] = lista_corregida

In [155]:
codigo = []
for pais in apuestas_2022['country']:
    codigo.append(int(str(dict_codes[pais])+'2022'))
apuestas_2022['codigo'] = codigo

In [156]:
apuestas_2022.columns

Index(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK', 'country', 'codigo'],
      dtype='object')

In [158]:
ap22_bets = apuestas_2022[['BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK']]

In [159]:
apuestas_2022['bet_mean'] = list(ap22_bets.mean(axis=1))

In [160]:
apuestas_2022.drop(['SONG', 'BET365', 'UNIBET', 'YOU_WIN', 'BOYLE_SPORTS', 'CORAL',
       'SKY_BET', 'BET_VICTOR', 'TITAN_BET', 'PAF', 'BETFAIR_SPORT',
       'SPORTING_BET', 'INTE_TOPS', 'PADDY_POWER', 'BET_FRED', 'BETWAY',
       'STAN_JAMES', 'BWIN', 'MATCH_BOOK'], axis=1, inplace=True)

In [161]:
apuestas_2022

                  country  codigo    bet_mean
0                 Ukraine  572022    1.336667
1                  Sweden  532022    6.076667
2                   Spain  522022   13.388889
3          United Kingdom  582022   13.986111
4                   Italy  342022   34.462778
5                  Norway  422022   77.111111
6                  Poland  432022   95.111111
7   Serbia and Montenegro  492022   99.277778
8                  Greece  292022  102.333333
9                 Moldova  382022  100.500000
10            Netherlands  552022  127.888889
11                Finland  252022  223.888889
12                Estonia  242022  220.823529
13              Australia  132022  239.944444
14         Czech Republic  222022  325.833333
15               Portugal  442022  335.277778
16                Armenia  122022  340.235294
17                Germany  282022  334.166667
18                 France  262022  363.333333
19             Azerbaijan  152022  386.117647
20                Iceland  312022  418.470588
21                Romania  452022  425.833333
22            Switzerland  542022  439.352941
23                Belgium  172022  444.166667
24              Lithuania  362022  474.352941

In [165]:
apuestas_2015.to_excel('../Apuestas_2015.xlsx')
apuestas_2016.to_excel('../Apuestas_2016.xlsx')
apuestas_2017.to_excel('../Apuestas_2017.xlsx')
apuestas_2018.to_excel('../Apuestas_2018.xlsx')
apuestas_2019.to_excel('../Apuestas_2019.xlsx')
apuestas_2021.to_excel('../Apuestas_2021.xlsx')
apuestas_2022.to_excel('../Apuestas_2022.xlsx')

### Encantramos anteriores a 2015

### 2002

In [222]:
import pandas as pd

apuestas_2002 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2002

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,5/1,🇩🇪 Germany,Corinna May – I Can’t Live Without Music,21st
1,2,6/1,🇸🇪 Sweden,Afro-dite – Never Let It Go,8th
2,3,7/1,🇪🇪 Estonia,Sahlene – Runaway,3rd
3,4,9/1,🇬🇧 United Kingdom,Jessica Garlick – Come Back,3rd
4,5,10/1,🇧🇪 Belgium,Sergio & The Ladies – Sister,13th
5,6,12/1,🇦🇹 Austria,Manuel Ortega – Say A Word,18th
6,7,12/1,🇫🇷 France,Sandrine François – Il faut du temps,5th
7,8,14/1,🇨🇾 Cyprus,One – Gimme,6th
8,9,14/1,🇩🇰 Denmark,Malene – Tell Me Who You Are,24th
9,10,14/1,🇱🇻 Latvia,Marie N – I Wanna,1st
10,11,14/1,🇸🇮 Slovenia,Sestre – Samo ljubezen,13th
11,12,14/1,🇪🇸 Spain,Rosa – Europe’s Living A Celebration,7th
12,13,16/1,🇭🇷 Croatia,Vesna Pisarović – Everything I Want,11th
13,14,16/1,🇲🇹 Malta,Ira Losco – 7th Wonder,2nd
14,15,16/1,🇷🇺 Russia,Prime Minister – Northern Girl,10th

In [223]:
apuestas_2002['country'] = [pais.split(" ")[1] for pais in apuestas_2002['COUNTRY']]

lista_corregida = []
for pais in apuestas_2002['country']:
    if pais == 'Netherlans':
        lista_corregida.append('The Netherlans')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    else:
        lista_corregida.append(pais)
apuestas_2002['country'] = lista_corregida

codigo = []
for pais in apuestas_2002['country']:
    codigo.append(int(str(dict_codes[pais])+'2002'))
apuestas_2002['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2002['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2002['bet_mean'] = lista_corregida

apuestas_2002.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2002

           country  codigo  bet_mean
0          Germany  282002       6.0
1           Sweden  532002       7.0
2          Estonia  242002       8.0
3   United Kingdom  582002      10.0
4          Belgium  172002      11.0
5          Austria  142002      13.0
6           France  262002      13.0
7           Cyprus  212002      15.0
8          Denmark  232002      15.0
9           Latvia  352002      15.0
10        Slovenia  512002      15.0
11           Spain  522002      15.0
12         Croatia  202002      17.0
13           Malta  372002      17.0
14          Russia  462002      17.0

### 2003

In [236]:
apuestas_2003 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2003

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,7/2,🇷🇺 Russia,"t.A.t.u. – Ne ver’, ne boysia",3rd
1,2,8/1,🇩🇪 Germany,Lou – Let’s Get Happy,11th
2,3,8/1,🇱🇻 Latvia,F.L.Y. – Hello From Mars,24th
3,4,8/1,🇪🇸 Spain,Beth – Dime,8th
4,5,8/1,🇸🇪 Sweden,Fame – Give Me Your Love,5th
5,6,9/1,🇬🇧 United Kingdom,Jemini – Cry Baby,26th
6,7,14/1,🇮🇪 Ireland,Mickey Harte – We’ve Got The World,11th
7,8,14/1,🇳🇱 Netherlands,Esther Hart – One More Night,13th
8,9,16/1,🇪🇪 Estonia,Ruffus – Eighties Coming Back,21st
9,10,16/1,🇫🇷 France,Louisa Baïleche – Monts et merveilles,18th
10,11,16/1,🇮🇸 Iceland,Birgitta – Open Your Heart,8th
11,12,20/1,🇳🇴 Norway,Jostein Hasselgård – I’m Not Afraid To Move On,4th
12,13,20/1,🇷🇴 Romania,Nicola – Don’t Break My Heart,10th
13,14,25/1,🇧🇦 Bosnia & Herzegovina,Mija Martina – Ne brini,16th
14,15,25/1,🇬🇷 Greece,Mando – Never Let You Go,17th

In [239]:
apuestas_2003['country'] = [pais.split(" ")[1] for pais in apuestas_2003['COUNTRY']]

lista_corregida = []
for pais in apuestas_2003['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')
    else:
        lista_corregida.append(pais)
apuestas_2003['country'] = lista_corregida

codigo = []
for pais in apuestas_2003['country']:
    codigo.append(int(str(dict_codes[pais])+'2003'))
apuestas_2003['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2003['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2003['bet_mean'] = lista_corregida

apuestas_2003.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2003

KeyError: 'COUNTRY'

### 2004

In [238]:
apuestas_2004 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2004

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,6/1,🇸🇪 Sweden,Lena Philipsson – It Hurts,5th
1,2,10/1,🇧🇪 Belgium,Xandee – 1 Life,22nd
2,3,10/1,🇨🇾 Cyprus,Lisa Andreas – Stronger Every Minute,5th
3,4,10/1,🇩🇪 Germany,Max – Can’t Wait Until Tonight,8th
4,5,10/1,🇷🇸🇲🇪 Serbia & Montenegro,Željko Joksimović & Ad-Hoc Orchestra – Lane moje,2nd
5,6,12/1,🇬🇷 Greece,Sakis Rouvas – Shake It,3rd
6,7,12/1,🇲🇹 Malta,Julie & Ludwig – On Again… Off Again,12th
7,8,12/1,🇷🇺 Russia,Julia Savicheva – Believe Me,11th
8,9,12/1,🇹🇷 Turkey,Athena – For Real,4th
9,10,14/1,🇮🇪 Ireland,Chris Doran – If My World Stopped Turning,22nd
10,11,16/1,🇩🇰 Denmark,Tomas Thordarson – Shame On You,SF (13th)
11,12,16/1,🇫🇮 Finland,Jari Sillanpää – Takes 2 To Tango,SF (14th)
12,13,16/1,🇪🇸 Spain,Ramón – Para llenarme de ti,10th
13,14,16/1,🇺🇦 Ukraine,Ruslana – Wild Dances,1st
14,15,20/1,🇫🇷 France,Jonatan Cerrada – À chaque pas,15th

In [241]:
apuestas_2004['country'] = [pais.split(" ")[1] for pais in apuestas_2004['COUNTRY']]

lista_corregida = []
for pais in apuestas_2004['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')    
    else:
        lista_corregida.append(pais)
apuestas_2004['country'] = lista_corregida

codigo = []
for pais in apuestas_2004['country']:
    codigo.append(int(str(dict_codes[pais])+'2004'))
apuestas_2004['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2004['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2004['bet_mean'] = lista_corregida

apuestas_2004.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2004

                  country  codigo  bet_mean
0                  Sweden  532004       7.0
1                 Belgium  172004      11.0
2                  Cyprus  212004      11.0
3                 Germany  282004      11.0
4   Serbia and Montenegro  492004      11.0
5                  Greece  292004      13.0
6                   Malta  372004      13.0
7                  Russia  462004      13.0
8                  Turkey  562004      13.0
9                 Ireland  322004      15.0
10                Denmark  232004      17.0
11                Finland  252004      17.0
12                  Spain  522004      17.0
13                Ukraine  572004      17.0
14                 France  262004      21.0

### 2005

In [242]:
apuestas_2005 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2005

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,11/4,🇬🇷 Greece,Helena Paparizou – My Number One,1st
1,2,11/2,🇳🇴 Norway,Wig Wam – In My Dreams,9th
2,3,9/1,🇭🇺 Hungary,"NOX – Forogj, világ",12th
3,4,9/1,🇮🇸 Iceland,Selma – If I Had Your Love,SF (16th)
4,5,9/1,🇨🇭 Switzerland,Vanilla Ninja – Cool Vibes,8th
5,6,12/1,🇲🇹 Malta,Chiara – Angel,2nd
6,7,16/1,🇧🇦 Bosnia & Herzegovina,Feminnem – Call Me,14th
7,8,20/1,🇧🇾 Belarus,Angelica Agurbash – Love Me Tonight,SF (13th)
8,9,20/1,🇪🇪 Estonia,Suntribe – Let’s Get Loud,SF (20th)
9,10,20/1,🇳🇱 Netherlands,Glennis Grace – My Impossible Dream,SF (14th)
10,11,20/1,🇬🇧 United Kingdom,Javine – Touch My Fire,22nd
11,12,25/1,🇨🇾 Cyprus,Constantinos Christoforou – Ela Ela,18th
12,13,25/1,🇱🇹 Lithuania,Laura & The Lovers – Little By Little,SF (25th)
13,14,25/1,🇸🇪 Sweden,Martin Stenmarck – Las Vegas,19th
14,15,33/1,🇩🇰 Denmark,Jakob Sveistrup – Talking To You,9th

In [244]:
apuestas_2005['country'] = [pais.split(" ")[1] for pais in apuestas_2005['COUNTRY']]

lista_corregida = []
for pais in apuestas_2005['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')    
    else:
        lista_corregida.append(pais)
apuestas_2005['country'] = lista_corregida

codigo = []
for pais in apuestas_2005['country']:
    codigo.append(int(str(dict_codes[pais])+'2005'))
apuestas_2005['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2005['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2005['bet_mean'] = lista_corregida

apuestas_2005.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2005

                   country  codigo  bet_mean
0                   Greece  292005      3.75
1                   Norway  422005      6.50
2                  Hungary  302005     10.00
3                  Iceland  312005     10.00
4              Switzerland  542005     10.00
5                    Malta  372005     13.00
6   Bosnia and Herzegovina  182005     17.00
7                  Belarus  162005     21.00
8                  Estonia  242005     21.00
9          The Netherlands  552005     21.00
10          United Kingdom  582005     21.00
11                  Cyprus  212005     26.00
12               Lithuania  362005     26.00
13                  Sweden  532005     26.00
14                 Denmark  232005     34.00

### 2006

In [245]:
apuestas_2006 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2006

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,2/1,🇬🇷 Greece,Anna Vissi – Everything,9th
1,2,7/1,🇷🇴 Romania,Mihai Trăistariu – Tornerò,4th
2,3,8/1,🇸🇪 Sweden,Carola – Invincible,5th
3,4,12/1,🇧🇪 Belgium,Kate Ryan – Je t’adore,SF (12th)
4,5,12/1,🇧🇦 Bosnia & Herzegovina,Hari Mata Hari – Lejla,3rd
5,6,12/1,🇬🇧 United Kingdom,Daz Sampson – Teenage Life,19th
6,7,14/1,🇩🇪 Germany,Texas Lightning – No No Never,14th
7,8,14/1,🇳🇴 Norway,Christine Guldbrandsen – Alvedansen,14th
8,9,14/1,🇨🇭 Switzerland,six4one – If We All Give A Little,16th
9,10,16/1,🇭🇷 Croatia,Severina – Moja štikla,12th
10,11,20/1,🇲🇰 F.Y.R. Macedonia,Elena Risteska – Ninanajna,12th
11,12,22/1,🇫🇮 Finland,Lordi – Hard Rock Hallelujah,1st
12,13,25/1,🇩🇰 Denmark,Sidsel Ben Semmane – Twist Of Love,18th
13,14,25/1,🇮🇸 Iceland,Silvía Night – Congratulations,SF (13th)
14,15,25/1,🇲🇹 Malta,Fabrizio Faniello – I Do,24th

In [247]:
apuestas_2006['country'] = [pais.split(" ")[1] for pais in apuestas_2006['COUNTRY']]

lista_corregida = []
for pais in apuestas_2006['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')
    elif pais == 'F.Y.R.':
        lista_corregida.append('North Macedonia')
    else:
        lista_corregida.append(pais)
apuestas_2006['country'] = lista_corregida

codigo = []
for pais in apuestas_2006['country']:
    codigo.append(int(str(dict_codes[pais])+'2006'))
apuestas_2006['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2006['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2006['bet_mean'] = lista_corregida

apuestas_2006.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2006

                   country  codigo  bet_mean
0                   Greece  292006       3.0
1                  Romania  452006       8.0
2                   Sweden  532006       9.0
3                  Belgium  172006      13.0
4   Bosnia and Herzegovina  182006      13.0
5           United Kingdom  582006      13.0
6                  Germany  282006      15.0
7                   Norway  422006      15.0
8              Switzerland  542006      15.0
9                  Croatia  202006      17.0
10         North Macedonia  412006      21.0
11                 Finland  252006      23.0
12                 Denmark  232006      26.0
13                 Iceland  312006      26.0
14                   Malta  372006      26.0

### 2007

In [248]:
apuestas_2007 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2007

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,5/1,🇨🇭 Switzerland,DJ Bobo – Vampires Are Alive,SF (20th)
1,2,7/1,🇸🇪 Sweden,The Ark – The Worrying Kind,18th
2,3,8/1,🇷🇸 Serbia,Marija Šerifović – Molitva,1st
3,4,8/1,🇧🇾 Belarus,Koldun – Work Your Magic,6th
4,5,11/1,🇺🇦 Ukraine,Verka Serduchka – Dancing Lasha Tumbai,2nd
5,6,11/1,🇧🇬 Bulgaria,Elitsa Todorova and Stoyan Yankoulov – Water,5th
6,7,12/1,🇷🇺 Russia,Serebro – Song #1,3rd
7,8,14/1,🇬🇷 Greece,Sarbel – Yassou Maria,7th
8,9,16/1,🇷🇴 Romania,"Todomondo – Liubi, Liubi, I Love You",13th
9,10,16/1,🇨🇾 Cyprus,"Evridiki – Comme ci, Comme ça",SF (15th)
10,11,20/1,🇸🇮 Slovenia,Alenka Gotar – Cvet Z Juga,15th
11,12,20/1,🇬🇧 United Kingdom,Scooch – Flying The Flag (For You),22nd
12,13,20/1,🇲🇹 Malta,Olivia Lewis – Vertigo,SF (25th)
13,14,25/1,🇱🇻 Latvia,Bonaparti.lv – Questa Notte,16th
14,15,25/1,🇪🇸 Spain,D’NASH – I Love You Mi Vida,20th

In [249]:
apuestas_2007['country'] = [pais.split(" ")[1] for pais in apuestas_2007['COUNTRY']]

lista_corregida = []
for pais in apuestas_2007['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')
    elif pais == 'F.Y.R.':
        lista_corregida.append('North Macedonia')
    else:
        lista_corregida.append(pais)
apuestas_2007['country'] = lista_corregida

codigo = []
for pais in apuestas_2006['country']:
    codigo.append(int(str(dict_codes[pais])+'2007'))
apuestas_2007['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2007['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2007['bet_mean'] = lista_corregida

apuestas_2007.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2007

                  country  codigo  bet_mean
0             Switzerland  292007       6.0
1                  Sweden  452007       8.0
2   Serbia and Montenegro  532007       9.0
3                 Belarus  172007       9.0
4                 Ukraine  182007      12.0
5                Bulgaria  582007      12.0
6                  Russia  282007      13.0
7                  Greece  422007      15.0
8                 Romania  542007      17.0
9                  Cyprus  202007      17.0
10               Slovenia  412007      21.0
11         United Kingdom  252007      21.0
12                  Malta  232007      21.0
13                 Latvia  312007      26.0
14                  Spain  372007      26.0

### 2008

In [250]:
apuestas_2008 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2008

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,7/2,🇷🇺 Russia,Dima Bilan – Believe,1st
1,2,9/2,🇷🇸 Serbia,Jelena Tomašević feat. Bora Dugić – Oro,6th
2,3,5/1,🇮🇪 Ireland,Dustin The Turkey – Irelande Douze Pointe,SF (15th)
3,4,11/2,🇦🇲 Armenia,"Sirusho – Qele, Qele",4th
4,5,7/1,🇺🇦 Ukraine,Ani Lorak – Shady Lady,2nd
5,6,9/1,🇸🇪 Sweden,Charlotte Perrelli – Hero,18th
6,7,18/1,🇧🇬 Bulgaria,"Deep Zone and Balthazar – DJ, Take Me Away",SF (11th)
7,8,20/1,🇬🇷 Greece,Kalomira – Secret Combination,3rd
8,9,20/1,🇪🇸 Spain,Rodolfo Chikilicuatre – Baila El Chiki-Chiki,16th
9,10,22/1,🇫🇷 France,Sébastian Tellier – Divine,19th
10,11,25/1,🇧🇦 Bosnia & Herzegovina,Laka – Pokušaj,10th
11,12,25/1,🇱🇻 Latvia,Pirates Of The Sea – Wolves Of The Sea,12th
12,13,25/1,🇹🇷 Turkey,Mor ve Ötesi – Deli,7th
13,14,25/1,🇨🇭 Switzerland,Paolo Meneguzzi – Era Stupendo,SF (13th)
14,15,25/1,🇷🇴 Romania,Nico and Vlad – Pe-o Margine de Lume,20th

In [251]:
apuestas_2008['country'] = [pais.split(" ")[1] for pais in apuestas_2008['COUNTRY']]

lista_corregida = []
for pais in apuestas_2008['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')
    elif pais == 'F.Y.R.':
        lista_corregida.append('North Macedonia')
    else:
        lista_corregida.append(pais)
apuestas_2008['country'] = lista_corregida

codigo = []
for pais in apuestas_2008['country']:
    codigo.append(int(str(dict_codes[pais])+'2008'))
apuestas_2008['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2008['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2008['bet_mean'] = lista_corregida

apuestas_2008.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2008

                   country  codigo  bet_mean
0                   Russia  462008       4.5
1    Serbia and Montenegro  492008       5.5
2                  Ireland  322008       6.0
3                  Armenia  122008       6.5
4                  Ukraine  572008       8.0
5                   Sweden  532008      10.0
6                 Bulgaria  192008      19.0
7                   Greece  292008      21.0
8                    Spain  522008      21.0
9                   France  262008      23.0
10  Bosnia and Herzegovina  182008      26.0
11                  Latvia  352008      26.0
12                  Turkey  562008      26.0
13             Switzerland  542008      26.0
14                 Romania  452008      26.0

### 2009

In [252]:
apuestas_2009 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2009

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,6/4,🇳🇴 Norway,Alexander Rybak – Fairytale,1st
1,2,9/2,🇬🇷 Greece,Sakis Rouvas – This Is Our Night,7th
2,3,8/1,🇹🇷 Turkey,Hadise – Düm Tek Tek,4th
3,4,8/1,🇲🇪 Montenegro,Andrea Demirović – Just Get Out Of My Life,SF (11th)
4,5,10/1,🇦🇿 Azerbaijan,AySel and Arash – Always,3rd
5,6,12/1,🇸🇪 Sweden,Malena Ernman – La Voix,21st
6,7,14/1,🇲🇹 Malta,Chiara – What If We?,22nd
7,8,18/1,🇬🇧 United Kingdom,Jade Ewen – It’s My Time,5th
8,9,25/1,🇪🇪 Estonia,Urban Symphony – Rändajad,6th
9,10,25/1,🇧🇦 Bosnia & Herzegovina,Regina – Bistra Voda,9th
10,11,25/1,🇫🇷 France,Patricia Kaas – Et S’il Fallait Le Faire,8th
11,12,25/1,🇪🇸 Spain,Soraya – La Noche Es Para Mí (The Night Is For...,24th
12,13,25/1,🇷🇺 Russia,Anastasiya Prikhodko – Mamo,11th
13,14,33/1,🇫🇮 Finland,Waldo’s People – Lose Control,25th
14,15,33/1,🇮🇸 Iceland,Yohanna – Is It True?,2nd

In [253]:
apuestas_2009['country'] = [pais.split(" ")[1] for pais in apuestas_2009['COUNTRY']]

lista_corregida = []
for pais in apuestas_2009['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')
    elif pais == 'F.Y.R.':
        lista_corregida.append('North Macedonia')
    else:
        lista_corregida.append(pais)
apuestas_2009['country'] = lista_corregida

codigo = []
for pais in apuestas_2009['country']:
    codigo.append(int(str(dict_codes[pais])+'2009'))
apuestas_2009['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2009['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2009['bet_mean'] = lista_corregida

apuestas_2009.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2009

                   country  codigo  bet_mean
0                   Norway  422009       2.5
1                   Greece  292009       5.5
2                   Turkey  562009       9.0
3               Montenegro  402009       9.0
4               Azerbaijan  152009      11.0
5                   Sweden  532009      13.0
6                    Malta  372009      15.0
7           United Kingdom  582009      19.0
8                  Estonia  242009      26.0
9   Bosnia and Herzegovina  182009      26.0
10                  France  262009      26.0
11                   Spain  522009      26.0
12                  Russia  462009      26.0
13                 Finland  252009      34.0
14                 Iceland  312009      34.0

In [254]:
apuestas_2010 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2010

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,11/4,🇩🇪 Germany,Lena – Satellite,1st
1,2,7/2,🇦🇿 Azerbaijan,Safura – Drip Drop,5th
2,3,8/1,🇮🇱 Israel,Harel Skaat – Milim,14th
3,4,12/1,🇩🇰 Denmark,Chanée & N’evergreen – In A Moment Like This,4th
4,5,14/1,🇦🇲 Armenia,Eva Rivas – Apricot Stone,7th
5,6,14/1,🇭🇷 Croatia,Feminnem – Lako Je Sve,SF (13th)
6,7,14/1,🇳🇴 Norway,Didrik Solli-Tangen – My Heart Is Yours,20th
7,8,25/1,🇬🇷 Greece,Giorgos Alkaios & Friends – OPA,8th
8,9,28/1,🇸🇪 Sweden,Anna Bergendahl – This Is My Life,SF (11th)
9,10,33/1,🇧🇪 Belgium,Tom Dice – Me And My Guitar,6th
10,11,33/1,🇮🇪 Ireland,Niamh Kavanagh – It’s For You,23rd
11,12,33/1,🇹🇷 Turkey,maNga – We Could Be The Same,2nd
12,13,40/1,🇸🇰 Slovakia,Kristína – Horehronie,SF (16th)
13,14,66/1,🇦🇱 Albania,Juliana Pasha – It’s All About You,16th
14,15,66/1,🇧🇾 Belarus,3+2 feat. Robert Wells – Butterflies,24th

In [255]:
apuestas_2010['country'] = [pais.split(" ")[1] for pais in apuestas_2010['COUNTRY']]

lista_corregida = []
for pais in apuestas_2009['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')
    elif pais == 'F.Y.R.':
        lista_corregida.append('North Macedonia')
    else:
        lista_corregida.append(pais)
apuestas_2010['country'] = lista_corregida

codigo = []
for pais in apuestas_2010['country']:
    codigo.append(int(str(dict_codes[pais])+'2010'))
apuestas_2010['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2010['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2010['bet_mean'] = lista_corregida

apuestas_2010.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2010

                   country  codigo  bet_mean
0                   Norway  422010      3.75
1                   Greece  292010      4.50
2                   Turkey  562010      9.00
3               Montenegro  402010     13.00
4               Azerbaijan  152010     15.00
5                   Sweden  532010     15.00
6                    Malta  372010     15.00
7           United Kingdom  582010     26.00
8                  Estonia  242010     29.00
9   Bosnia and Herzegovina  182010     34.00
10                  France  262010     34.00
11                   Spain  522010     34.00
12                  Russia  462010     41.00
13                 Finland  252010     67.00
14                 Iceland  312010     67.00

### 2011

In [256]:
apuestas_2011 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2011

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,4/1,🇫🇷 France,Amaury Vassili – Sognu,15th
1,2,13/2,🇪🇪 Estonia,Getter Jaani – Rockefeller Street,24th
2,3,7/1,🇬🇧 United Kingdom,Blue – I Can,11th
3,4,8/1,🇭🇺 Hungary,Kati Wolf – What About My Dreams?,22nd
4,5,10/1,🇸🇪 Sweden,Eric Saade – Popular,3rd
5,6,10/1,🇧🇦 Bosnia & Herzegovina,Dino Merlin – Love In Rewind,6th
6,7,12/1,🇦🇿 Azerbaijan,Ell & Nikki – Running Scared,1st
7,8,12/1,🇳🇴 Norway,Stella Mwangi – Haba Haba,SF (17th)
8,9,12/1,🇩🇪 Germany,Lena – Taken By A Stranger,10th
9,10,20/1,🇷🇺 Russia,Alexej Vorobjov – Get You,16th
10,11,20/1,🇮🇪 Ireland,Jedward – Lipstick,8th
11,12,20/1,🇩🇰 Denmark,A Friend In London – New Tomorrow,5th
12,13,33/1,🇮🇹 Italy,Raphael Gualazzi – Madness Of Love,2nd
13,14,40/1,🇷🇴 Romania,Hotel FM – Change,17th
14,15,40/1,🇵🇱 Poland,Magdalena Tul – Jestem,SF (19th)

In [257]:
apuestas_2011['country'] = [pais.split(" ")[1] for pais in apuestas_2011['COUNTRY']]

lista_corregida = []
for pais in apuestas_2011['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')
    elif pais == 'F.Y.R.':
        lista_corregida.append('North Macedonia')
    else:
        lista_corregida.append(pais)
apuestas_2011['country'] = lista_corregida

codigo = []
for pais in apuestas_2011['country']:
    codigo.append(int(str(dict_codes[pais])+'2011'))
apuestas_2011['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2011['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2011['bet_mean'] = lista_corregida

apuestas_2011.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2011

                   country  codigo  bet_mean
0                   France  262011       5.0
1                  Estonia  242011       7.5
2           United Kingdom  582011       8.0
3                  Hungary  302011       9.0
4                   Sweden  532011      11.0
5   Bosnia and Herzegovina  182011      11.0
6               Azerbaijan  152011      13.0
7                   Norway  422011      13.0
8                  Germany  282011      13.0
9                   Russia  462011      21.0
10                 Ireland  322011      21.0
11                 Denmark  232011      21.0
12                   Italy  342011      34.0
13                 Romania  452011      41.0
14                  Poland  432011      41.0

### 2012

In [261]:
apuestas_2012 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2012

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,9/4,🇸🇪 Sweden,Loreen – Euphoria,1st
1,2,8/1,🇮🇹 Italy,Nina Zilli – L’amore è femmina (Out Of Love),9th
2,3,10/1,🇷🇺 Russia,Buranovskiye Babushki – Party For Everybody,2nd
3,4,11/1,🇷🇸 Serbia,Željko Joksimović – Nije Ljubav Stvar,3rd
4,5,14/1,🇩🇰 Denmark,Soluna Samay – Should’ve Known Better,23rd
5,6,14/1,🇬🇧 United Kingdom,Engelbert Humperdinck – Love Will Set You Free,25th
6,7,16/1,🇮🇪 Ireland,Jedward – Waterline,19th
7,8,18/1,🇪🇸 Spain,Pastora Soler – Quédate Conmigo (Stay With Me),10th
8,9,20/1,🇩🇪 Germany,Roman Lob – Standing Still,8th
9,10,20/1,🇳🇴 Norway,Tooji – Stay,26th
10,11,22/1,🇮🇸 Iceland,Greta Salóme and Jónsi – Never Forget,20th
11,12,25/1,🇬🇷 Greece,Eleftheria Eleftheriou – Aphrodisiac,17th
12,13,28/1,🇷🇴 Romania,Mandinga – Zaleilah,12th
13,14,28/1,🇹🇷 Turkey,Can Bonomo – Love Me Back,7th
14,15,33/1,🇨🇾 Cyprus,Ivi Adamou – La La Love,16th

In [262]:
apuestas_2012['country'] = [pais.split(" ")[1] for pais in apuestas_2012['COUNTRY']]

lista_corregida = []
for pais in apuestas_2012['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')
    elif pais == 'F.Y.R.':
        lista_corregida.append('North Macedonia')
    else:
        lista_corregida.append(pais)
apuestas_2012['country'] = lista_corregida

codigo = []
for pais in apuestas_2012['country']:
    codigo.append(int(str(dict_codes[pais])+'2012'))
apuestas_2012['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2012['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2012['bet_mean'] = lista_corregida

apuestas_2012.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2012

                  country  codigo  bet_mean
0                  Sweden  532012      3.25
1                   Italy  342012      9.00
2                  Russia  462012     11.00
3   Serbia and Montenegro  492012     12.00
4                 Denmark  232012     15.00
5          United Kingdom  582012     15.00
6                 Ireland  322012     17.00
7                   Spain  522012     19.00
8                 Germany  282012     21.00
9                  Norway  422012     21.00
10                Iceland  312012     23.00
11                 Greece  292012     26.00
12                Romania  452012     29.00
13                 Turkey  562012     29.00
14                 Cyprus  212012     34.00

### 2013

In [263]:
apuestas_2013 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2013

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,6/4,🇩🇰 Denmark,Emmelie de Forest – Only Teardrops,1st
1,2,8/1,🇳🇴 Norway,Margaret Berger – I Feed You My Love,4th
2,3,12/1,🇺🇦 Ukraine,Zlata Ognevich – Gravity,3rd
3,4,16/1,🇷🇺 Russia,Dina Garipova – What If,5th
4,5,16/1,🇸🇪 Sweden,Robin Stjernberg – You,14th
5,6,19/1,🇳🇱 Netherlands,Anouk – Birds,9th
6,7,25/1,🇩🇪 Germany,Cascada – Glorious,21st
7,8,25/1,🇬🇪 Georgia,Nodi Tatishvili & Sophie Gelovani – Waterfall,15th
8,9,25/1,🇮🇹 Italy,Marco Mengoni – L’Essenziale,7th
9,10,33/1,🇦🇿 Azerbaijan,Farid Mammadov – Hold Me,2nd
10,11,40/1,🇸🇲 San Marino,Valentina Monetta – Crisalide (Vola),SF (11th)
11,12,50/1,🇬🇧 United Kingdom,Bonnie Tyler – Believe In Me,19th
12,13,66/1,🇮🇪 Ireland,Ryan Dolan – Only Love Survives,26th
13,14,66/1,🇧🇾 Belarus,Alyona Lanskaya – Solayoh,16th
14,15,75/1,🇬🇷 Greece,Koza Mostra feat. Agathon Iakovidis – Alcohol ...,6th

In [265]:
apuestas_2013['country'] = [pais.split(" ")[1] for pais in apuestas_2013['COUNTRY']]

lista_corregida = []
for pais in apuestas_2013['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')
    elif pais == 'F.Y.R.':
        lista_corregida.append('North Macedonia')
    elif pais == 'San':
        lista_corregida.append('San Marino')
    else:
        lista_corregida.append(pais)
apuestas_2013['country'] = lista_corregida

codigo = []
for pais in apuestas_2013['country']:
    codigo.append(int(str(dict_codes[pais])+'2013'))
apuestas_2013['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2013['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2013['bet_mean'] = lista_corregida

apuestas_2013.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2013

            country  codigo  bet_mean
0           Denmark  232013       2.5
1            Norway  422013       9.0
2           Ukraine  572013      13.0
3            Russia  462013      17.0
4            Sweden  532013      17.0
5   The Netherlands  552013      20.0
6           Germany  282013      26.0
7           Georgia  272013      26.0
8             Italy  342013      26.0
9        Azerbaijan  152013      34.0
10       San Marino  472013      41.0
11   United Kingdom  582013      51.0
12          Ireland  322013      67.0
13          Belarus  162013      67.0
14           Greece  292013      76.0

### 2014

In [266]:
apuestas_2014 = pd.read_clipboard(header=None, names=['RANK','ODDS', 'COUNTRY', 'ENTRY','EUROVISION_PLACING'])
apuestas_2014

,RANK,ODDS,COUNTRY,ENTRY,EUROVISION_PLACING
0,1,6/4,🇦🇲 Armenia,Aram MP3 – Not Alone,4th
1,2,11/2,🇸🇪 Sweden,Sanna Nielsen – Undo,3rd
2,3,12/1,🇩🇰 Denmark,Basim – Cliché Love Song,9th
3,4,12/1,🇳🇴 Norway,Carl Espen – Silent Storm,8th
4,5,18/1,🇭🇺 Hungary,András Kállay-Saunders – Running,5th
5,6,20/1,🇬🇧 United Kingdom,Molly – Children Of The Universe,17th
6,7,20/1,🇺🇦 Ukraine,Mariya Yaremchuk – Tick-Tock,6th
7,8,20/1,🇦🇿 Azerbaijan,Dilara Kazimova – Start A Fire,22nd
8,9,25/1,🇧🇪 Belgium,Axel Hirsoux – Mother,SF (14th)
9,10,25/1,🇷🇴 Romania,Paula Seling & OVI – Miracle,12th
10,11,40/1,🇷🇺 Russia,Tolmachevy Sisters – Shine,7th
11,12,66/1,🇮🇹 Italy,Emma Marrone – La Mia Città,21st
12,13,66/1,🇬🇷 Greece,Freaky Fortune feat. RiskyKidd – Rise Up,20th
13,14,66/1,🇮🇱 Israel,Mei Finegold – Same Heart,SF (14th)
14,15,66/1,🇮🇪 Ireland,Can-Linn feat. Kasey Smith – Heartbeat,SF (12th)

In [267]:
apuestas_2014['country'] = [pais.split(" ")[1] for pais in apuestas_2014['COUNTRY']]

lista_corregida = []
for pais in apuestas_2014['country']:
    if pais == 'Netherlands':
        lista_corregida.append('The Netherlands')
    elif pais == 'United':
        lista_corregida.append('United Kingdom')
    elif pais == 'Bosnia':
        lista_corregida.append('Bosnia and Herzegovina')
    elif pais == 'Serbia':
        lista_corregida.append('Serbia and Montenegro')
    elif pais == 'F.Y.R.':
        lista_corregida.append('North Macedonia')
    elif pais == 'San':
        lista_corregida.append('San Marino')
    else:
        lista_corregida.append(pais)
apuestas_2014['country'] = lista_corregida

codigo = []
for pais in apuestas_2014['country']:
    codigo.append(int(str(dict_codes[pais])+'2014'))
apuestas_2014['codigo'] = codigo

lista_corregida = []
for odd in apuestas_2014['ODDS']:
    lista_corregida.append( int(odd.split('/')[0]) / int(odd.split('/')[1]) + 1 )
apuestas_2014['bet_mean'] = lista_corregida

apuestas_2014.drop(['RANK','ODDS','COUNTRY','ENTRY','EUROVISION_PLACING'], axis=1, inplace=True)

apuestas_2014

           country  codigo  bet_mean
0          Armenia  122014       2.5
1           Sweden  532014       6.5
2          Denmark  232014      13.0
3           Norway  422014      13.0
4          Hungary  302014      19.0
5   United Kingdom  582014      21.0
6          Ukraine  572014      21.0
7       Azerbaijan  152014      21.0
8          Belgium  172014      26.0
9          Romania  452014      26.0
10          Russia  462014      41.0
11           Italy  342014      67.0
12          Greece  292014      67.0
13          Israel  332014      67.0
14         Ireland  322014      67.0

In [268]:
apuestas_2002.to_excel('../Apuestas_2002.xlsx')
apuestas_2003.to_excel('../Apuestas_2003.xlsx')
apuestas_2004.to_excel('../Apuestas_2004.xlsx')
apuestas_2005.to_excel('../Apuestas_2005.xlsx')
apuestas_2006.to_excel('../Apuestas_2006.xlsx')
apuestas_2007.to_excel('../Apuestas_2007.xlsx')
apuestas_2008.to_excel('../Apuestas_2008.xlsx')
apuestas_2009.to_excel('../Apuestas_2009.xlsx')
apuestas_2010.to_excel('../Apuestas_2010.xlsx')
apuestas_2011.to_excel('../Apuestas_2011.xlsx')
apuestas_2012.to_excel('../Apuestas_2012.xlsx')
apuestas_2013.to_excel('../Apuestas_2013.xlsx')
apuestas_2014.to_excel('../Apuestas_2014.xlsx')

In [274]:
dfs = [apuestas_2002, apuestas_2003, apuestas_2004, apuestas_2005, apuestas_2006, apuestas_2007, apuestas_2008,
       apuestas_2009, apuestas_2010, apuestas_2011, apuestas_2012, apuestas_2013, apuestas_2014, apuestas_2015,
       apuestas_2016, apuestas_2017, apuestas_2018, apuestas_2019, apuestas_2021, apuestas_2022]

In [277]:
apuestas_2002_2022 = pd.concat(dfs, axis=0)

In [278]:
apuestas_2002_2022.to_excel('../Apuestas_TOTAL.xlsx')