# Scrapping (SELENIUM) Spotify

### INTENTOS FALLIDOS (API, BS...)

In [1]:
# import spotipy
# from spotipy.oauth2 import SpotifyClientCredentials

# lz_uri = 'spotify:artist:36QJpDe2go2KgaRleHCDTp'

# spotify = spotipy.Spotify(client_credentials_manager=SpotifyClientCredentials())
# results = spotify.artist_top_tracks(lz_uri)

# for track in results['tracks'][:10]:
#     print('track    : ' + track['name'])
#     print('audio    : ' + track['preview_url'])
#     print('cover art: ' + track['album']['images'][0]['url'])

In [404]:
# %pip install beautifulsoup4
import requests as req
from bs4 import BeautifulSoup as bs
import pandas as pd
# from pprint import pprint
# from lxml import html
# from lxml.html import fromstring
# import urllib.request
# from urllib.request import urlopen
# import random
# import re
# import scrapy

In [3]:
# url = 'https://open.spotify.com/playlist/37i9dQZF1DWVCKO3xAlT1Q?si=848395f62a76431f&nd=1'

In [4]:
# html1 = req.get(url).content
# sopa_1 = bs(html1, 'html.parser')

In [143]:
# box=sopa_1.find_all('div', {'role': 'row'})
# box

## Creamos tabla con Año-Canción-Duración de 2002-2022

In [409]:
from selenium import webdriver
import pandas as pd
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager

In [405]:
import time

In [410]:
#driver configuration
opciones=Options()

opciones.add_experimental_option('excludeSwitches', ['enable-automation'])
opciones.add_experimental_option('useAutomationExtension', False)
opciones.headless=False    # si True, no aperece la ventana (headless=no visible)
opciones.add_argument('--start-maximized')         # comienza maximizado
opciones.add_argument('user-data-dir=selenium')    # mantiene las cookies
#opciones.add_extension('driver_folder/adblock.crx')       # adblocker
opciones.add_argument('--incognito')

In [411]:
PATH=ChromeDriverManager().install()

[WDM] - Downloading: 100%|██████████| 6.68M/6.68M [00:03<00:00, 1.76MB/s]

In [412]:
import warnings
warnings.filterwarnings("ignore")

from selenium.webdriver.common.by import By

In [413]:
driver=webdriver.Chrome(PATH) # Defino el Driver

In [414]:
links_ESC = ['https://open.spotify.com/playlist/678Z8bEOgr4XIsNxM4GSp8', #2002
             'https://open.spotify.com/playlist/5jYbHqdi4Iydx9M7iRUr1Y', #2003
             'https://open.spotify.com/playlist/0ON9rWwf7DVqWUQCzifPAu', #2004
             'https://open.spotify.com/playlist/7yGP0bxcEONKZlPsgz6GyO', #2005
             'https://open.spotify.com/playlist/1Zd88QyEnzs6Olxfpe4yx6', #2006
             'https://open.spotify.com/playlist/3eZMKIuweYtnzhltLdX0W7', #2007
             'https://open.spotify.com/playlist/3dV9cGOxgxNJUsXvhYM1EM', #2008
             'https://open.spotify.com/playlist/00smDaf4YSGwi0QOePSErK', #2009
             'https://open.spotify.com/playlist/7u6JyU7guDPt4pQDKUnq1h', #2010
             'https://open.spotify.com/playlist/0uOfym75CYyCHY4A7udPRW', #2011
             'https://open.spotify.com/playlist/0S19HXFl9IkseQXznuM11k', #2012
             'https://open.spotify.com/playlist/5eThLL29Upy1DjI0W9DZ15', #2013
             'https://open.spotify.com/playlist/0IR8qc9ocga2lSNCq7T7fR', #2014
             'https://open.spotify.com/playlist/4uzGseR9zSG0oVMF2FyF54', #2015
             'https://open.spotify.com/playlist/0Exn6DDSPrkWv31cYu6eCP', #2016
             'https://open.spotify.com/playlist/5yhNkcfVGurxg81CfGxFrR', #2017
             'https://open.spotify.com/playlist/0CSmYggDYBskQItvoquck3', #2018
             'https://open.spotify.com/playlist/6qGNr3CLtGyr2dFUY7TRYN', #2019
             'https://open.spotify.com/playlist/36T5LUw7frosIwCbjdPXrS', #2020
             'https://open.spotify.com/playlist/1rxDhj2Bqa4TeXOQCESuRb', #2021
             'https://open.spotify.com/playlist/33Gtj8gByPmwJGn6M1OKur'] #2022

In [415]:
import random

In [416]:
import tqdm 
from tqdm import tqdm

In [448]:
anio_act = 2001
df = pd.DataFrame()

for link in tqdm(links_ESC): # Para cada link en la lista de links...
    
    driver.get(link) # Entra en la página...
    time.sleep(random.randint(4,8)) # Genero un número aleatorio para esperar entre 4" y 8" para que no me "pillen" como robot
    
    driver.execute_script("document.body.style.zoom='25%'")
    dur = driver.find_elements(By.CLASS_NAME, 'Type__TypeElement-goli3j-0.eDbSCl.Btg2qHSuepFGBG6X0yEN')
    duracion = [e.text for e in dur]

    canc = driver.find_elements(By.CLASS_NAME, 'Type__TypeElement-goli3j-0.gwYBEX.t_yrXoUO3qGsJS4Y6iXX.standalone-ellipsis-one-line')
    cancion = [e.text for e in canc]
    
    cant = driver.find_elements(By.CLASS_NAME, 'Type__TypeElement-goli3j-0.eDbSCl.rq2VQ5mb9SDAFWbBIUIn.standalone-ellipsis-one-line')
    cantante = [e.text for e in cant]
    
    anio_act += 1 # Actualizo el año en cada bucle
    anio = [anio_act for i in range(len(cancion))] # Creo una lista del año con el len de la lista cantante
    
    df_ESC = pd.DataFrame()
    df_ESC['anio'] = anio
    df_ESC['cancion'] = cancion
    df_ESC['cantante'] = cantante
    df_ESC['duracion'] = duracion
    
    df = pd.concat([df, df_ESC], axis=0)
    
    
df

100%|██████████| 21/21 [06:13<00:00, 17.80s/it]

,anio,cancion,cantante,duracion
0,2002,I Wanna (Radio Version),Marie N,3:01
1,2002,7th Wonder,Ira Losco,3:01
2,2002,Runaway - Bonus Track,Anna Sahlene,2:52
3,2002,Il Faut Du Temps,Sandrine Francois,3:57
4,2002,Gimme,One,3:04
...,...,...,...,...
35,2022,Fade to black,Nadir Rustamli,2:57
36,2022,Disko,LPS,2:59
37,2022,Trenulețul (cu Frații Advahov) - Eurovision 2022,"Zdob si Zdub, Fratii Advahov",3:00
38,2022,SloMo - Eurovision's Dancebreak Edit,Chanel,3:00
39,2022,SPACE MAN - Eurovision Song Contest Edit,Sam Ryder,3:04

In [449]:
df.to_excel(r'/Users/Usuario/Desktop/IronHack/Bootcamp/Proyectos/3 - Proyecto ETL/Canciones20anios.xlsx', index = False)

### Limpiamos errores o información innecesaria

In [450]:
df_spoty = pd.read_excel('./Canciones20anios.xlsx')

In [451]:
df_spoty

,anio,cancion,cantante,duracion
0,2002,I Wanna (Radio Version),Marie N,3:01
1,2002,7th Wonder,Ira Losco,3:01
2,2002,Runaway - Bonus Track,Anna Sahlene,2:52
3,2002,Il Faut Du Temps,Sandrine Francois,3:57
4,2002,Gimme,One,3:04
...,...,...,...,...
801,2022,Fade to black,Nadir Rustamli,2:57
802,2022,Disko,LPS,2:59
803,2022,Trenulețul (cu Frații Advahov) - Eurovision 2022,"Zdob si Zdub, Fratii Advahov",3:00
804,2022,SloMo - Eurovision's Dancebreak Edit,Chanel,3:00
805,2022,SPACE MAN - Eurovision Song Contest Edit,Sam Ryder,3:04

In [452]:
df_spoty['duracion'].unique() #Está OK

array(['3:01', '2:52', '3:57', '3:04', '3:02', '3:06', '3:23', '2:43',
       '3:03', '3:00', '3:07', '2:47', '3:31', '3:05', '2:57', '2:55',
       '3:16', '3:37', '2:58', '2:56', '4:25', '2:54', '2:59', '2:45',
       '3:11', '2:49', '2:53', '3:24', '3:19', '2:39', '3:59', '2:51',
       '3:10', '2:31', '2:48', '4:15', '3:08', '2:30', '3:13', '7:33',
       '3:21', '2:42', '4:37', '2:50', '3:18', '3:44', '2:33', '3:54',
       '3:28', '3:17', '3:49', '3:48', '2:44', '3:42', '4:05', '3:09',
       '3:32', '3:12', '4:07', '3:55', '4:14', '3:25', '3:38', '3:27',
       '4:02', '6:36', '2:46', '3:14', '3:30', '1:24', '3:20', '3:22',
       '2:38', '3:50', '3:15', '3:29', '5:20', '3:36', '2:34', '2:40',
       '2:16', '2:37'], dtype=object)

In [282]:
# DEJO EL CÓDIGO COMENTADO, PERO SE ME ESCAPAN MUCHAS. CORTO POR LO SANO

# lista_corregida = []

# for song in df_spoty['cancion']:
#     if '(Eur' in song:
#         bien = song.split('(Eur')[0].strip()
#         lista_corregida.append(bien)
#     elif 'ESC' in song:
#         if '(' in song:
#             bien = song.split('(')[0].strip()
#             lista_corregida.append(bien)
#         else:
#             bien = song.split('- ')[0].strip()
#             lista_corregida.append(bien) 
            
#     elif 'Euro' in song and '-' in song:
#         bien = song.split('-')[0].strip()
#         lista_corregida.append(bien)
    
#     elif 'Remix' in song:
#         if '(' in song:
#             bien = song.split('(')[0].strip()
#             lista_corregida.append(bien)
#         else:
#             bien = song.split('- ')[0].strip()
#             lista_corregida.append(bien) 
        
#     elif 'rad' in song or 'Rad' in song:
#         if '-' in song:
#             bien = song.split('-')[0].strip()
#             lista_corregida.append(bien)
#         else:
#             bien = song.split('(')[0].strip()
#             lista_corregida.append(bien)

#     else:
#         lista_corregida.append(song)
        
# lista_corregida

In [453]:
lista_corregida = []

for song in df_spoty['cancion']:
    if '(' in song:
        bien = song.split('(')[0].strip()
        lista_corregida.append(bien)
        
    elif '-' in song:
        bien = song.split('-')[0].strip()
        lista_corregida.append(bien)
        
    else:
        lista_corregida.append(song)
        
len(lista_corregida)

806

In [454]:
df_spoty['cancion'] = lista_corregida

In [455]:
df_spoty

     anio           cancion                      cantante duracion
0    2002           I Wanna                       Marie N     3:01
1    2002        7th Wonder                     Ira Losco     3:01
2    2002           Runaway                  Anna Sahlene     2:52
3    2002  Il Faut Du Temps             Sandrine Francois     3:57
4    2002             Gimme                           One     3:04
..    ...               ...                           ...      ...
801  2022     Fade to black                Nadir Rustamli     2:57
802  2022             Disko                           LPS     2:59
803  2022        Trenulețul  Zdob si Zdub, Fratii Advahov     3:00
804  2022             SloMo                        Chanel     3:00
805  2022         SPACE MAN                     Sam Ryder     3:04

[806 rows x 4 columns]

In [456]:
subset = df_spoty.loc[:,'anio':'cancion']

In [457]:
filas_permanecen = subset.drop_duplicates().index

filas_eliminar = []
for i in df_spoty.index:
    if i not in filas_permanecen:
        filas_eliminar.append(i)
        
filas_eliminar

[136, 215, 261, 302, 392, 430, 434, 466, 497, 513, 639, 682, 683, 748, 765]

In [458]:
df_spoty.drop(filas_eliminar, inplace=True)

In [459]:
df_spoty

     anio           cancion                      cantante duracion
0    2002           I Wanna                       Marie N     3:01
1    2002        7th Wonder                     Ira Losco     3:01
2    2002           Runaway                  Anna Sahlene     2:52
3    2002  Il Faut Du Temps             Sandrine Francois     3:57
4    2002             Gimme                           One     3:04
..    ...               ...                           ...      ...
801  2022     Fade to black                Nadir Rustamli     2:57
802  2022             Disko                           LPS     2:59
803  2022        Trenulețul  Zdob si Zdub, Fratii Advahov     3:00
804  2022             SloMo                        Chanel     3:00
805  2022         SPACE MAN                     Sam Ryder     3:04

[791 rows x 4 columns]

In [426]:
# Aún habiéndola limpiado, se intuye que será dificilísimo cruzar los títulos de las canciones con las otras tablas...

### Creamos clave para cruces

In [477]:
lista_corregida = [] # Cambio a string para poder concatenarlo sin problema
for i in df_spoty['anio']:
    bien = str(i)
    lista_corregida.append(bien)
df_spoty['anio'] = lista_corregida

In [480]:
df_spoty['clave1'] = df_spoty['cantante']+" "+df_spoty['anio']
df_spoty['clave2'] = df_spoty['cancion']+" "+df_spoty['anio']

In [481]:
df_spoty['clave1']

0                           Marie N 2002
1                         Ira Losco 2002
2                      Anna Sahlene 2002
3                 Sandrine Francois 2002
4                               One 2002
                     ...
801                  Nadir Rustamli 2022
802                             LPS 2022
803    Zdob si Zdub, Fratii Advahov 2022
804                          Chanel 2022
805                       Sam Ryder 2022
Name: clave1, Length: 791, dtype: object

In [482]:
lista_corregida = [] # lo devuelvo a int
for i in df_spoty['anio']:
    bien = int(i)
    lista_corregida.append(bien)
df_spoty['anio'] = lista_corregida

In [483]:
df_spoty

,anio,cancion,cantante,duracion,clave1,clave2
0,2002,I Wanna,Marie N,3:01,Marie N 2002,I Wanna 2002
1,2002,7th Wonder,Ira Losco,3:01,Ira Losco 2002,7th Wonder 2002
2,2002,Runaway,Anna Sahlene,2:52,Anna Sahlene 2002,Runaway 2002
3,2002,Il Faut Du Temps,Sandrine Francois,3:57,Sandrine Francois 2002,Il Faut Du Temps 2002
4,2002,Gimme,One,3:04,One 2002,Gimme 2002
...,...,...,...,...,...,...
801,2022,Fade to black,Nadir Rustamli,2:57,Nadir Rustamli 2022,Fade to black 2022
802,2022,Disko,LPS,2:59,LPS 2022,Disko 2022
803,2022,Trenulețul,"Zdob si Zdub, Fratii Advahov",3:00,"Zdob si Zdub, Fratii Advahov 2022",Trenulețul 2022
804,2022,SloMo,Chanel,3:00,Chanel 2022,SloMo 2022
805,2022,SPACE MAN,Sam Ryder,3:04,Sam Ryder 2022,SPACE MAN 2022

In [485]:
df_spoty.to_excel(r'/Users/Usuario/Desktop/IronHack/Bootcamp/Proyectos/3 - Proyecto ETL/Canciones_2002_2022_Spoty.xlsx', index = False)

In [126]:
# PRUEBAS Y COMPROBACIONES
# url_prueba = 'https://open.spotify.com/playlist/1rxDhj2Bqa4TeXOQCESuRb'
# driver.get(url_prueba)

# dur = driver.find_elements(By.CLASS_NAME, 'Type__TypeElement-goli3j-0.eDbSCl.Btg2qHSuepFGBG6X0yEN')
# duracion = [e.text for e in dur]

# canc = driver.find_elements(By.CLASS_NAME, 'Type__TypeElement-goli3j-0.gwYBEX.t_yrXoUO3qGsJS4Y6iXX.standalone-ellipsis-one-line')
# cancion= [e.text for e in canc]

In [140]:
# duracion

In [142]:
# from selenium.webdriver.common.keys import Keys

In [141]:
# len(cancion)

In [150]:
# df2 = pd.read_csv('./eurovision_1957-2021.csv')

In [198]:
# df2

In [152]:
# NO ME VALE
# df2.to_excel(r'/Users/Usuario/Desktop/IronHack/Bootcamp/Proyectos/3 - Proyecto ETL/DataBase1957_2021.xlsx', index = False)

# Request Wikipedia

In [9]:
%pip install beautifulsoup4
import requests as req
from bs4 import BeautifulSoup as bs

Requirement already satisfied: beautifulsoup4 in c:\users\usuario\anaconda3\lib\site-packages (4.11.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\usuario\anaconda3\lib\site-packages (from beautifulsoup4) (2.3.1)
Note: you may need to restart the kernel to use updated packages.

In [38]:
import pandas as pd

In [2]:
url_02 = 'https://es.wikipedia.org/wiki/Festival_de_la_Canci%C3%B3n_de_Eurovisi%C3%B3n_2002'

In [6]:
html_02 = req.get(url_02).text

In [7]:
sopa_02 = bs(html_02, 'html.parser')

In [35]:
tabla = sopa_02.find_all('table')

In [196]:
# tabla # No es escalable, hay que encontrar la posición de la tabla concreta en cada una de las 20 páginas...

In [ ]:
# Probamos con clipboard. ¿Escalable? si no, una a una, pero vamos a probar.

### Creamos tabla con Orden-País-Cantante-Cancion-Idioma-Lugar-Anio

In [130]:
df_ESC=pd.DataFrame()

df_02=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_02['Anio'] = 2002
df_02.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,23,Latvia,Marie N,I Wanna,English,176,1,2002
1,20,Malta,Ira Losco,7th Wonder,English,164,2,2002
2,2,United Kingdom,Jessica Garlick,Come Back,English,111,3,2002
3,8,Estonia,Sahlene,Runaway,English,111,3,2002
4,17,France,Sandrine François,Il faut du temps,French,104,5,2002

In [131]:
df_03=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_03['Anio'] = 2003
df_03.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,4,Turkey,Sertab Erener,Everyway That I Can,English,167,1,2003
1,22,Belgium,Urban Trad,Sanomi,Imaginary,165,2,2003
2,11,Russia,t.A.T.u.,"Ne ver', ne boysia (Не верь, не бойся)",Russian,164,3,2003
3,18,Norway,Jostein Hasselgård,I'm Not Afraid to Move On,English,123,4,2003
4,25,Sweden,Fame,Give Me Your Love,English,107,5,2003

In [106]:
df_04=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_04['Anio'] = 2004
df_04.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,10,Ukraine,Ruslana,Wild Dances,"English, Ukrainian",280,1,2004
1,5,Serbia and Montenegro,Željko Joksimović and Ad-Hoc Orchestra,Lane moje (Лане моје),Serbian,263,2,2004
2,16,Greece,Sakis Rouvas,Shake It,English,252,3,2004
3,22,Turkey,Athena,For Real,English,195,4,2004
4,21,Cyprus,Lisa Andreas,Stronger Every Minute,English,170,5,2004

In [110]:
df_05=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_05['Anio'] = 2005
df_05.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,19,Greece,Helena Paparizou,My Number One,English,230,1,2005
1,3,Malta,Chiara,Angel,English,192,2,2005
2,4,Romania,Luminița Anghel and Sistem,Let Me Try,English,158,3,2005
3,11,Israel,Shiri Maimon,HaSheket SheNish'ar (השקט שנשאר),"Hebrew, English",154,4,2005
4,23,Latvia,Walters and Kazha,The War Is Not Over,English,153,5,2005

In [111]:
df_06=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_06['Anio'] = 2006
df_06.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,17,Finland,Lordi,Hard Rock Hallelujah,English,292,1,2006
1,10,Russia,Dima Bilan,Never Let You Go,English,248,2,2006
2,13,Bosnia and Herzegovina,Hari Mata Hari,Lejla,Bosnian,229,3,2006
3,12,Romania,Mihai Trăistariu,Tornerò,"English, Italian",172,4,2006
4,22,Sweden,Carola,Invincible,English,170,5,2006

In [112]:
df_07=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_07['Anio'] = 2007
df_07.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,17,Serbia,Marija Šerifović,Molitva (Молитва),Serbian,268,1,2007
1,18,Ukraine,Verka Serduchka,Dancing Lasha Tumbai,"German, English, Surzhyk[e]",235,2,2007
2,15,Russia,Serebro,Song #1,English,207,3,2007
3,22,Turkey,Kenan Doğulu,Shake It Up Şekerim,English,163,4,2007
4,21,Bulgaria,Elitsa Todorova and Stoyan Yankoulov,Water,Bulgarian,157,5,2007

In [114]:
df_08=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_08['Anio'] = 2008
df_08.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,24,Russia,Dima Bilan,Believe,English,272,1,2008
1,18,Ukraine,Ani Lorak,Shady Lady,English,230,2,2008
2,21,Greece,Kalomira,Secret Combination,English,218,3,2008
3,5,Armenia,Sirusho,"Qélé, Qélé (Քելե Քելե)","English, Armenian",199,4,2008
4,25,Norway,Maria,Hold On Be Strong,English,182,5,2008

In [115]:
df_09=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_09['Anio'] = 2009
df_09.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,20,Norway,Alexander Rybak,Fairytale,English,387,1,2009
1,7,Iceland,Yohanna,Is It True?,English,218,2,2009
2,11,Azerbaijan,AySel and Arash,Always,English,207,3,2009
3,18,Turkey,Hadise,Düm Tek Tek,English[b],177,4,2009
4,23,United Kingdom,Jade Ewen,It's My Time,English,173,5,2009

In [116]:
df_10=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_10['Anio'] = 2010
df_10.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,22,Germany,Lena,Satellite,English,246,1,2010
1,14,Turkey,Manga,We Could Be the Same,English,170,2,2010
2,19,Romania,Paula Seling and Ovi,Playing with Fire,English,162,3,2010
3,25,Denmark,Chanée and N'evergreen,In a Moment like This,English,149,4,2010
4,1,Azerbaijan,Safura,Drip Drop,English,145,5,2010

In [117]:
df_11=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_11['Anio'] = 2011
df_11.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,19,Azerbaijan,Ell and Nikki,Running Scared,English,221,1,2011
1,12,Italy,Raphael Gualazzi,Madness of Love,"Italian, English",189,2,2011
2,7,Sweden,Eric Saade,Popular,English,185,3,2011
3,23,Ukraine,Mika Newton,Angel,English,159,4,2011
4,3,Denmark,A Friend in London,New Tomorrow,English,134,5,2011

In [118]:
df_12=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_12['Anio'] = 2012
df_12.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,17,Sweden,Loreen,Euphoria,English,372,1,2012
1,6,Russia,Buranovskiye Babushki,Party for Everybody,"Udmurt, English",259,2,2012
2,24,Serbia,Željko Joksimović,Nije ljubav stvar (Није љубав ствар),Serbian,214,3,2012
3,13,Azerbaijan,Sabina Babayeva,When the Music Dies,English,150,4,2012
4,3,Albania,Rona Nishliu,Suus,Albanian[c],146,5,2012

In [119]:
df_13=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_13['Anio'] = 2013
df_13.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,18,Denmark,Emmelie de Forest,Only Teardrops,English,281,1,2013
1,20,Azerbaijan,Farid Mammadov,Hold Me,English,234,2,2013
2,22,Ukraine,Zlata Ognevich,Gravity,English,214,3,2013
3,24,Norway,Margaret Berger,I Feed You My Love,English,191,4,2013
4,10,Russia,Dina Garipova,What If,English,174,5,2013

In [120]:
df_14=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_14['Anio'] = 2014
df_14.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,11,Austria,Conchita Wurst,Rise Like a Phoenix,English,290,1,2014
1,24,Netherlands,The Common Linnets,Calm After the Storm,English,238,2,2014
2,13,Sweden,Sanna Nielsen,Undo,English,218,3,2014
3,7,Armenia,Aram Mp3,Not Alone,English,174,4,2014
4,21,Hungary,András Kállay-Saunders,Running,English,143,5,2014

In [121]:
df_15=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_15['Anio'] = 2015
df_15.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,10,Sweden,Måns Zelmerlöw,Heroes,English,365,1,2015
1,25,Russia,Polina Gagarina,A Million Voices,English,303,2,2015
2,27,Italy,Il Volo,Grande amore,Italian,292,3,2015
3,13,Belgium,Loïc Nottet,Rhythm Inside,English,217,4,2015
4,12,Australia,Guy Sebastian,Tonight Again,English,196,5,2015

In [122]:
df_16=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_16['Anio'] = 2016
df_16.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,21,Ukraine,Jamala,1944,"English, Crimean Tatar",534,1,2016
1,13,Australia,Dami Im,Sound of Silence,English,511,2,2016
2,18,Russia,Sergey Lazarev,You Are the Only One,English,491,3,2016
3,8,Bulgaria,Poli Genova,If Love Was a Crime,"English, Bulgarian",307,4,2016
4,9,Sweden,Frans,If I Were Sorry,English,261,5,2016

In [123]:
df_17=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_17['Anio'] = 2017
df_17.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,11,Portugal,Salvador Sobral,Amar pelos dois,Portuguese,758,1,2017
1,25,Bulgaria,Kristian Kostov,Beautiful Mess,English,615,2,2017
2,7,Moldova,SunStroke Project,Hey Mamma,English,374,3,2017
3,23,Belgium,Blanche,City Lights,English,363,4,2017
4,24,Sweden,Robin Bengtsson,I Can't Go On,English,344,5,2017

In [124]:
df_18=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_18['Anio'] = 2018
df_18.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,22,Israel,Netta,Toy,English[b],529,1,2018
1,25,Cyprus,Eleni Foureira,Fuego,English[c],436,2,2018
2,5,Austria,Cesár Sampson,Nobody but You,English,342,3,2018
3,11,Germany,Michael Schulte,You Let Me Walk Alone,English,340,4,2018
4,26,Italy,Ermal Meta and Fabrizio Moro,Non mi avete fatto niente,Italian,308,5,2018

In [125]:
df_19=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_19['Anio'] = 2019
df_19.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,12,Netherlands,Duncan Laurence,Arcade,English,498,1,2019
1,22,Italy,Mahmood,Soldi,Italian[i],472,2,2019
2,5,Russia,Sergey Lazarev,Scream,English,370,3,2019
3,24,Switzerland,Luca Hänni,She Got Me,English,364,4,2019
4,9,Sweden,John Lundvik,Too Late for Love,English,334,5,2019

In [126]:
df_21=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_21['Anio'] = 2021
df_21.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,24,Italy,Måneskin,Zitti e buoni,Italian,524,1,2021
1,20,France,Barbara Pravi,Voilà,French,499,2,2021
2,11,Switzerland,Gjon's Tears,Tout l'univers,French,432,3,2021
3,12,Iceland[o],Daði og Gagnamagnið,10 Years,English,378,4,2021
4,19,Ukraine,Go_A,Shum (Шум),Ukrainian,364,5,2021

In [127]:
df_22=pd.read_clipboard(header=None, names=['Orden','Pais','Cantante','Cancion','Idioma','Puntos','Lugar'])
df_22['Anio'] = 2022
df_22.head()

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,12,Ukraine,Kalush Orchestra,Stefania (Стефанія),Ukrainian,631,1,2022
1,22,United Kingdom,Sam Ryder,Space Man,English,466,2,2022
2,10,Spain,Chanel,SloMo,"Spanish, English",459,3,2022
3,20,Sweden,Cornelia Jakobs,Hold Me Closer,English,438,4,2022
4,24,Serbia,Konstrakta,In corpore sano,"Serbian, Latin",312,5,2022

In [102]:
datafreims = []
anio = 1
for i in range(21):
    anio += 1
    if anio < 10:
        datafreims.append('df_'+'0'+str(anio))
    else:
        datafreims.append('df_' + str(anio))
        
print(datafreims)

['df_02', 'df_03', 'df_04', 'df_05', 'df_06', 'df_07', 'df_08', 'df_09', 'df_10', 'df_11', 'df_12', 'df_13', 'df_14', 'df_15', 'df_16', 'df_17', 'df_18', 'df_19', 'df_20', 'df_21', 'df_22']

In [105]:
tablas = ""
for i in datafreims:
    tablas += i+", "
tablas

'df_02, df_03, df_04, df_05, df_06, df_07, df_08, df_09, df_10, df_11, df_12, df_13, df_14, df_15, df_16, df_17, df_18, df_19, df_20, df_21, df_22, '

In [488]:
df_ESC = pd.concat([df_02, df_03, df_04, df_05, df_06, df_07, df_08, df_09, df_10, df_11, df_12, df_13, df_14, df_15, 
                    df_16, df_17, df_18, df_19, df_21, df_22,], axis=0)

In [489]:
df_ESC

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio
0,23,Latvia,Marie N,I Wanna,English,176,1,2002
1,20,Malta,Ira Losco,7th Wonder,English,164,2,2002
2,2,United Kingdom,Jessica Garlick,Come Back,English,111,3,2002
3,8,Estonia,Sahlene,Runaway,English,111,3,2002
4,17,France,Sandrine François,Il faut du temps,French,104,5,2002
...,...,...,...,...,...,...,...,...
20,1,Czech Republic,We Are Domi,Lights Off,English,38,22[e],2022
21,4,Finland,The Rasmus,Jezebel,English,38,21[e],2022
22,18,Iceland,Systur,Með hækkandi sól,Icelandic,20,23,2022
23,6,France,Alvan and Ahez,Fulenn,Breton,17,24,2022
24,13,Germany,Malik Harris,Rockstars,English,6,25,2022

### Limpieza de columnas

In [490]:
df_ESC['Lugar'].unique() # Limpiamos la columna "Lugar" para eliminar algunas anotaciones de wikipedia

array([1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22,
       23, 24, 4, 14, 15, 25, 26, 27, '1', '2', '3', '4', '5', '6', '7',
       '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18',
       '20', '19[h]', '21', '22', '23', '24', '25', '26', '19', '22[e]',
       '21[e]'], dtype=object)

In [491]:
lugar_bien = []
for i in df_ESC['Lugar']:
    i = str(i)
    bien = (i.split('[')[0]).strip()
    lugar_bien.append(int(bien))

In [492]:
# lugar_bien

In [493]:
df_ESC['Lugar'] = lugar_bien

In [494]:
df_ESC['Lugar'].unique()

array([ 1,  2,  3,  5,  6,  7,  8,  9, 10, 11, 12, 13, 16, 17, 18, 19, 20,
       21, 22, 23, 24,  4, 14, 15, 25, 26, 27], dtype=int64)

In [495]:
df_ESC['Orden'].unique() # Convertimos a enteros todos los números de orden y quitamos anotaciones

array([23, 20, 2, 8, 17, 1, 5, 12, 21, 7, 6, 10, 15, 16, 22, 19, 4, 3, 9,
       13, 18, 11, 24, 14, 25, 26, '22', '14', '19', '25', '1', '7', '21',
       '11', '13', '17', '20', '18', '8', '24', '2[d]', '15', '6', '23',
       '16', '3', '4', '5', '10', '9', '12', 27], dtype=object)

In [496]:
orden_bien = []
for i in df_ESC['Orden']:
    i = str(i)
    bien = (i.split('[')[0]).strip()
    orden_bien.append(int(bien))

In [497]:
df_ESC['Orden'] = orden_bien

In [498]:
print(sorted(df_ESC['Orden'].unique()))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27]

In [499]:
def limpieza_nums(columna): # Creamos una funcion para casos similares
    lista_corregida = []
    for i in columna:
        i = str(i)
        bien = (i.split('[')[0]).strip()
        lista_corregida.append(int(bien))

In [500]:
print(sorted(df_ESC['Pais'].unique())) # Quitamos espacios innecesarios y quitamos anotaciones

['  Switzerland', ' Albania', ' Armenia', ' Australia', ' Austria', ' Azerbaijan', ' Belarus', ' Belgium', ' Bosnia and Herzegovina', ' Bulgaria', ' Croatia', ' Cyprus', ' Czech Republic', ' Denmark', ' Estonia', ' Finland', ' France', ' Georgia', ' Germany', ' Greece', ' Hungary', ' Iceland', ' Iceland[o]', ' Ireland', ' Israel', ' Italy', ' Latvia', ' Lithuania', ' Macedonia', ' Malta', ' Moldova', ' Montenegro', ' Netherlands', ' North Macedonia', ' Norway', ' Poland', ' Portugal', ' Romania', ' Russia', ' San Marino', ' Serbia', ' Serbia and Montenegro', ' Slovenia', ' Spain', ' Sweden', ' Turkey', ' Ukraine', ' United Kingdom']

In [501]:
def limpieza_str(columna):
    lista_corregida = []
    for i in columna:
        bien = (i.split('[')[0]).strip()
        lista_corregida.append(bien)
    columna = lista_corregida

In [502]:
limpieza_str(df_ESC['Pais']) # No funciona...

In [503]:
print(sorted(df_ESC['Pais'].unique()))

['  Switzerland', ' Albania', ' Armenia', ' Australia', ' Austria', ' Azerbaijan', ' Belarus', ' Belgium', ' Bosnia and Herzegovina', ' Bulgaria', ' Croatia', ' Cyprus', ' Czech Republic', ' Denmark', ' Estonia', ' Finland', ' France', ' Georgia', ' Germany', ' Greece', ' Hungary', ' Iceland', ' Iceland[o]', ' Ireland', ' Israel', ' Italy', ' Latvia', ' Lithuania', ' Macedonia', ' Malta', ' Moldova', ' Montenegro', ' Netherlands', ' North Macedonia', ' Norway', ' Poland', ' Portugal', ' Romania', ' Russia', ' San Marino', ' Serbia', ' Serbia and Montenegro', ' Slovenia', ' Spain', ' Sweden', ' Turkey', ' Ukraine', ' United Kingdom']

In [504]:
lista_corregida = []
for i in df_ESC['Pais']:
    bien = (i.split('[')[0]).strip()
    lista_corregida.append(bien)
df_ESC['Pais'] = lista_corregida

In [505]:
print(sorted(df_ESC['Pais'].unique())) # Hay que corregir Macedonia...

['Albania', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Israel', 'Italy', 'Latvia', 'Lithuania', 'Macedonia', 'Malta', 'Moldova', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Serbia and Montenegro', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Turkey', 'Ukraine', 'United Kingdom']

In [506]:
lista_corregida = []
for i in df_ESC['Pais']:
    if i == 'Macedonia':
        lista_corregida.append('North Macedonia')
    else:
        lista_corregida.append(i)
df_ESC['Pais'] = lista_corregida

In [507]:
print(sorted(df_ESC['Pais'].unique()))

['Albania', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Israel', 'Italy', 'Latvia', 'Lithuania', 'Malta', 'Moldova', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Serbia and Montenegro', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'Turkey', 'Ukraine', 'United Kingdom']

In [508]:
df_ESC['Idioma'].unique() # Limpiamos quitando anotaciones

array(['English', 'French', 'Spanish[b]', 'Hebrew, English',
       'Serbian, English', 'Slovene', 'Turkish, English', 'English[a]',
       'Macedonian', 'Imaginary', 'Russian', 'German[a]',
       'German, Polish, Russian', 'Spanish', 'English[c]',
       'Croatian, English', 'Hebrew[b]', 'Portuguese, English',
       'English, Ukrainian', 'Serbian', 'English, Turkish',
       'French, Spanish', 'English, Spanish', 'German',
       'English, Romanian', 'Montenegrin', 'Croatian', 'Hungarian',
       'Turkish', 'Ukrainian, English[a]', 'Bosnian', 'English, Italian',
       'English[d]', 'Turkish, English[c]', 'English, Macedonian',
       'Norwegian', 'English[b]', 'German, English, Surzhyk[e]',
       'Bulgarian', 'English, Armenian',
       'English, Italian, Spanish, Russian, French, Romanian',
       'Macedonian, English', 'Italian', 'German, English', 'Spanish[c]',
       'French, English ("Franglais")', 'Hebrew[a]', 'Portuguese',
       'Albanian', 'Spanish, English', 'English[f]', 'Romanian, Italian',
       'Finnish', 'Estonian', 'Russian, Ukrainian', 'Romanian, English',
       'English, Hebrew, Arabic', 'English, French', 'English, Russian',
       'Greek[a]', 'Hebrew', 'Italian, English', 'English, Greek',
       'Corsican', 'English, Hungarian', 'Udmurt, English', 'Albanian[c]',
       'French, English', 'Greek[b]', 'Romanian', 'Icelandic',
       'Polish, English', 'Italian[c]', 'English, Slovene', 'French[b]',
       'English, Crimean Tatar', 'English, Bulgarian', 'Italian[g]',
       'Hungarian[d]', 'Belarusian[f]', 'English[e]', 'Serbian[d]',
       'Slovene[g]', 'Italian[i]', 'English[h]', 'English, French[g]',
       'Ukrainian', 'English[k]', 'Russian, English', 'Serbian[p]',
       'English[i]', 'English[j]', 'English[m]', 'English, Sranan Tongo',
       'English[q]', 'Serbian, Latin', 'English, Portuguese', 'Dutch',
       'Lithuanian', 'Breton'], dtype=object)

In [509]:
lista_corregida = []
for i in df_ESC['Idioma']:
    bien = (i.split('[')[0]).strip()
    lista_corregida.append(bien)
df_ESC['Idioma'] = lista_corregida

In [510]:
df_ESC['Idioma'].unique()

array(['English', 'French', 'Spanish', 'Hebrew, English',
       'Serbian, English', 'Slovene', 'Turkish, English', 'Macedonian',
       'Imaginary', 'Russian', 'German', 'German, Polish, Russian',
       'Croatian, English', 'Hebrew', 'Portuguese, English',
       'English, Ukrainian', 'Serbian', 'English, Turkish',
       'French, Spanish', 'English, Spanish', 'English, Romanian',
       'Montenegrin', 'Croatian', 'Hungarian', 'Turkish',
       'Ukrainian, English', 'Bosnian', 'English, Italian',
       'English, Macedonian', 'Norwegian', 'German, English, Surzhyk',
       'Bulgarian', 'English, Armenian',
       'English, Italian, Spanish, Russian, French, Romanian',
       'Macedonian, English', 'Italian', 'German, English',
       'French, English ("Franglais")', 'Portuguese', 'Albanian',
       'Spanish, English', 'Romanian, Italian', 'Finnish', 'Estonian',
       'Russian, Ukrainian', 'Romanian, English',
       'English, Hebrew, Arabic', 'English, French', 'English, Russian',
       'Greek', 'Italian, English', 'English, Greek', 'Corsican',
       'English, Hungarian', 'Udmurt, English', 'French, English',
       'Romanian', 'Icelandic', 'Polish, English', 'English, Slovene',
       'English, Crimean Tatar', 'English, Bulgarian', 'Belarusian',
       'Ukrainian', 'Russian, English', 'English, Sranan Tongo',
       'Serbian, Latin', 'English, Portuguese', 'Dutch', 'Lithuanian',
       'Breton'], dtype=object)

In [530]:
lista_corregida = []
for i in df_ESC['Anio']:
    bien = str(i)
    lista_corregida.append(bien)
df_ESC['Anio'] = lista_corregida

In [531]:
df_ESC['clave1'] = df_ESC['Cantante']+" "+df_ESC['Anio']
df_ESC['clave2'] = df_ESC['Cancion']+" "+df_ESC['Anio']
df_ESC['clave3'] = df_ESC['Pais']+" "+df_ESC['Anio']

In [532]:
df_ESC

,Orden,Pais,Cantante,Cancion,Idioma,Puntos,Lugar,Anio,clave1,clave2,clave3
0,23,Latvia,Marie N,I Wanna,English,176,1,2002,Marie N 2002,I Wanna 2002,Latvia 2002
1,20,Malta,Ira Losco,7th Wonder,English,164,2,2002,Ira Losco 2002,7th Wonder 2002,Malta 2002
2,2,United Kingdom,Jessica Garlick,Come Back,English,111,3,2002,Jessica Garlick 2002,Come Back 2002,United Kingdom 2002
3,8,Estonia,Sahlene,Runaway,English,111,3,2002,Sahlene 2002,Runaway 2002,Estonia 2002
4,17,France,Sandrine François,Il faut du temps,French,104,5,2002,Sandrine François 2002,Il faut du temps 2002,France 2002
...,...,...,...,...,...,...,...,...,...,...,...
20,1,Czech Republic,We Are Domi,Lights Off,English,38,22,2022,We Are Domi 2022,Lights Off 2022,Czech Republic 2022
21,4,Finland,The Rasmus,Jezebel,English,38,21,2022,The Rasmus 2022,Jezebel 2022,Finland 2022
22,18,Iceland,Systur,Með hækkandi sól,Icelandic,20,23,2022,Systur 2022,Með hækkandi sól 2022,Iceland 2022
23,6,France,Alvan and Ahez,Fulenn,Breton,17,24,2022,Alvan and Ahez 2022,Fulenn 2022,France 2022
24,13,Germany,Malik Harris,Rockstars,English,6,25,2022,Malik Harris 2022,Rockstars 2022,Germany 2022

In [516]:
lista_corregida = []
for i in df_ESC['Anio']:
    bien = int(i)
    lista_corregida.append(bien)
df_ESC['Anio'] = lista_corregida

In [517]:
df_ESC.to_excel(r'/Users/Usuario/Desktop/IronHack/Bootcamp/Proyectos/3 - Proyecto ETL/BBSS_Puntos_2002_2022.xlsx', index = False)

# Scrapping YouTube (Fallido)

In [329]:
driver.get('https://www.youtube.com/playlist?list=PL2QMi0PdRqgQ88Etn6_0syH87l7hT4QiP')

In [334]:
html_YT = req.get('https://www.youtube.com/playlist?list=PL2QMi0PdRqgQ88Etn6_0syH87l7hT4QiP').text

In [335]:
sopa = bs(html_YT, 'html.parser')

In [337]:
# sopa # Plan fallido, no salen las reproducciones en las miniaturas del video cuando es una lista de reproducción...

# BBDD Kaggle Lyrics

In [1]:
%pip install pymongo
from pymongo import MongoClient
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: pymongo in c:\users\usuario\anaconda3\lib\site-packages (4.2.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
cursor = MongoClient('mongodb://localhost:27017')
cursor

MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True)

In [3]:
cursor.list_database_names()

['EurovisionComments', 'admin', 'companies2', 'config', 'local']

In [4]:
db = cursor.EurovisionComments  # use companies;
colec = db.esc

In [5]:
colec

Collection(Database(MongoClient(host=['localhost:27017'], document_class=dict, tz_aware=False, connect=True), 'EurovisionComments'), 'esc')

In [6]:
ESC_lyrics = list(colec.find({'Year':{'$gte':"2002", '$lte':"2022"}},
               {'Year':1, 'Host_Country':1, 'Host_City':1,'Eurovision_Number':1, 'Country':1, 'Artist':1, 'Song':1, 
                'Language':1, 'Lyrics':1, 'Lyrics translation':1, '_id':0}))

In [9]:
df_lyrics = pd.DataFrame(ESC_lyrics)
df_lyrics

,Country,Artist,Song,Language,Eurovision_Number,Year,Host_Country,Host_City,Lyrics,Lyrics translation
0,Cyprus,One,Gimme,English,47,2002,Estonia,Tallinn,"Say yeah... gimme your lovin'\n(Gimme, gimme, ...",English
1,United Kingdom,Jessica Garlick,Come Back,English,47,2002,Estonia,Tallinn,We've both made the same mistakes\nAnd believe...,English
2,Austria,Manuel Ortega,Say a Word,English,47,2002,Estonia,Tallinn,I can be the sunshine today\nI'll be there to ...,English
3,Greece,Michalis Rakintzis,S.A.G.A.P.O.,English (title Greek),47,2002,Estonia,Tallinn,"Hey (Hey, hey, hey, hey...)\nEvery time you ne...",English
4,Spain,Rosa,Europe's Living a Celebration,Spanish (title English),47,2002,Estonia,Tallinn,"(Celebration, celebration)\n\n(Celebration, ce...","(Celebration, celebration) (Celebration, celeb..."
...,...,...,...,...,...,...,...,...,...,...
812,Sweden,Cornelia Jakobs,Hold Me Closer,English,66,2022,Italy,Turin,No need to apologise\nCuz there‘s nothing to r...,English
813,Switzerland,Marius Bear,Boys Do Cry,English,66,2022,Italy,Turin,"In my room, lives a boy who could be blue,\nAn...",English
814,The Netherlands,S10,De Diepte,Dutch,66,2022,Italy,Turin,"Ken je het gevoel dat, dat je droom niet uitko...",Do you know the feeling\nYour dream is never c...
815,Ukraine,Kalush Orchestra,Stefania,Ukrainian,66,2022,Italy,Turin,"Стефанія мамо мамо Стефанія,\nРозквітає поле, ...",Mother Stephania Stephania mother\nThe field i...
816,United Kingdom,Sam Ryder,SPACE MAN,English,66,2022,Italy,Turin,"If I was an astronaut, I‘d be floating in mid-...",English

In [10]:
long_list = []

for i in df_lyrics['Lyrics']:
    long = len(i)
    long_list.append(long)

In [11]:
df_lyrics['Lyrics_Long'] = long_list

In [12]:
df_lyrics

,Country,Artist,Song,Language,Eurovision_Number,Year,Host_Country,Host_City,Lyrics,Lyrics translation,Lyrics_Long
0,Cyprus,One,Gimme,English,47,2002,Estonia,Tallinn,"Say yeah... gimme your lovin'\n(Gimme, gimme, ...",English,1482
1,United Kingdom,Jessica Garlick,Come Back,English,47,2002,Estonia,Tallinn,We've both made the same mistakes\nAnd believe...,English,840
2,Austria,Manuel Ortega,Say a Word,English,47,2002,Estonia,Tallinn,I can be the sunshine today\nI'll be there to ...,English,1274
3,Greece,Michalis Rakintzis,S.A.G.A.P.O.,English (title Greek),47,2002,Estonia,Tallinn,"Hey (Hey, hey, hey, hey...)\nEvery time you ne...",English,1344
4,Spain,Rosa,Europe's Living a Celebration,Spanish (title English),47,2002,Estonia,Tallinn,"(Celebration, celebration)\n\n(Celebration, ce...","(Celebration, celebration) (Celebration, celeb...",1355
...,...,...,...,...,...,...,...,...,...,...,...
812,Sweden,Cornelia Jakobs,Hold Me Closer,English,66,2022,Italy,Turin,No need to apologise\nCuz there‘s nothing to r...,English,1467
813,Switzerland,Marius Bear,Boys Do Cry,English,66,2022,Italy,Turin,"In my room, lives a boy who could be blue,\nAn...",English,759
814,The Netherlands,S10,De Diepte,Dutch,66,2022,Italy,Turin,"Ken je het gevoel dat, dat je droom niet uitko...",Do you know the feeling\nYour dream is never c...,1047
815,Ukraine,Kalush Orchestra,Stefania,Ukrainian,66,2022,Italy,Turin,"Стефанія мамо мамо Стефанія,\nРозквітає поле, ...",Mother Stephania Stephania mother\nThe field i...,983
816,United Kingdom,Sam Ryder,SPACE MAN,English,66,2022,Italy,Turin,"If I was an astronaut, I‘d be floating in mid-...",English,1214

In [13]:
palabras = []
len(set(sorted(df_lyrics['Lyrics'][1].lower().replace('(', "").replace(')',"").replace(',',"").replace('.',"").split())))

76

In [14]:
words_list = []

for i in range(len(df_lyrics['Lyrics'])):
    palabras = len(set(sorted(df_lyrics['Lyrics'][i].lower().replace('(', "").replace(')',"").replace(',',"").replace('.',"").split())))
    words_list.append(palabras)

In [15]:
df_lyrics['Lyrics_words'] = words_list

In [16]:
print(sorted(df_lyrics['Country'].unique())) # Comprobamos que los paises tienen el nombre bien escrito siempre

['Albania', 'Andorra', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Israel', 'Italy', 'Latvia', 'Lithuania', 'Macedonia', 'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Serbia and Montenegro', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'The Netherlands', 'Turkey', 'Ukraine', 'United Kingdom']

In [17]:
lista_corregida = []
for i in df_lyrics['Country']:
    if i == 'Macedonia':
        lista_corregida.append('North Macedonia')
    else:
        lista_corregida.append(i)
df_lyrics['Country'] = lista_corregida

In [18]:
print(sorted(df_lyrics['Country'].unique()))

['Albania', 'Andorra', 'Armenia', 'Australia', 'Austria', 'Azerbaijan', 'Belarus', 'Belgium', 'Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Cyprus', 'Czech Republic', 'Denmark', 'Estonia', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'Iceland', 'Ireland', 'Israel', 'Italy', 'Latvia', 'Lithuania', 'Malta', 'Moldova', 'Monaco', 'Montenegro', 'Netherlands', 'North Macedonia', 'Norway', 'Poland', 'Portugal', 'Romania', 'Russia', 'San Marino', 'Serbia', 'Serbia and Montenegro', 'Slovakia', 'Slovenia', 'Spain', 'Sweden', 'Switzerland', 'The Netherlands', 'Turkey', 'Ukraine', 'United Kingdom']

In [19]:
lista_corregida = []
for i in df_lyrics['Year']:
    anio = int(i)
    lista_corregida.append(anio)
df_lyrics['Year'] = lista_corregida

In [20]:
print(sorted(df_lyrics['Year'].unique()))

[2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022]

In [21]:
lista_corregida = []
for i in df_lyrics['Year']:
    bien = str(i)
    lista_corregida.append(bien)
df_lyrics['Year'] = lista_corregida

In [22]:
df_lyrics['clave1'] = df_lyrics['Song']+" "+df_lyrics['Year']
df_lyrics['clave2'] = df_lyrics['Artist']+" "+df_lyrics['Year']
df_lyrics['clave3'] = df_lyrics['Country']+" "+df_lyrics['Year']

In [23]:
df_lyrics

,Country,Artist,Song,Language,Eurovision_Number,Year,Host_Country,Host_City,Lyrics,Lyrics translation,Lyrics_Long,Lyrics_words,clave1,clave2,clave3
0,Cyprus,One,Gimme,English,47,2002,Estonia,Tallinn,"Say yeah... gimme your lovin'\n(Gimme, gimme, ...",English,1482,65,Gimme 2002,One 2002,Cyprus 2002
1,United Kingdom,Jessica Garlick,Come Back,English,47,2002,Estonia,Tallinn,We've both made the same mistakes\nAnd believe...,English,840,76,Come Back 2002,Jessica Garlick 2002,United Kingdom 2002
2,Austria,Manuel Ortega,Say a Word,English,47,2002,Estonia,Tallinn,I can be the sunshine today\nI'll be there to ...,English,1274,84,Say a Word 2002,Manuel Ortega 2002,Austria 2002
3,Greece,Michalis Rakintzis,S.A.G.A.P.O.,English (title Greek),47,2002,Estonia,Tallinn,"Hey (Hey, hey, hey, hey...)\nEvery time you ne...",English,1344,47,S.A.G.A.P.O. 2002,Michalis Rakintzis 2002,Greece 2002
4,Spain,Rosa,Europe's Living a Celebration,Spanish (title English),47,2002,Estonia,Tallinn,"(Celebration, celebration)\n\n(Celebration, ce...","(Celebration, celebration) (Celebration, celeb...",1355,102,Europe's Living a Celebration 2002,Rosa 2002,Spain 2002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,Sweden,Cornelia Jakobs,Hold Me Closer,English,66,2022,Italy,Turin,No need to apologise\nCuz there‘s nothing to r...,English,1467,116,Hold Me Closer 2022,Cornelia Jakobs 2022,Sweden 2022
813,Switzerland,Marius Bear,Boys Do Cry,English,66,2022,Italy,Turin,"In my room, lives a boy who could be blue,\nAn...",English,759,74,Boys Do Cry 2022,Marius Bear 2022,Switzerland 2022
814,The Netherlands,S10,De Diepte,Dutch,66,2022,Italy,Turin,"Ken je het gevoel dat, dat je droom niet uitko...",Do you know the feeling\nYour dream is never c...,1047,84,De Diepte 2022,S10 2022,The Netherlands 2022
815,Ukraine,Kalush Orchestra,Stefania,Ukrainian,66,2022,Italy,Turin,"Стефанія мамо мамо Стефанія,\nРозквітає поле, ...",Mother Stephania Stephania mother\nThe field i...,983,93,Stefania 2022,Kalush Orchestra 2022,Ukraine 2022
816,United Kingdom,Sam Ryder,SPACE MAN,English,66,2022,Italy,Turin,"If I was an astronaut, I‘d be floating in mid-...",English,1214,84,SPACE MAN 2022,Sam Ryder 2022,United Kingdom 2022

In [24]:
df_lyrics.to_excel(r'/Users/Usuario/Desktop/IronHack/Bootcamp/Proyectos/3 - Proyecto ETL/BBSS_Long_Letras_2002_2022_con_translation.xlsx', index = False)

### Conectamos con Workbench SQL

In [524]:
%pip install SQLAlchemy

Requirement already satisfied: SQLAlchemy in c:\users\usuario\anaconda3\lib\site-packages (1.4.32)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\usuario\anaconda3\lib\site-packages (from SQLAlchemy) (1.1.1)
Note: you may need to restart the kernel to use updated packages.

In [29]:
from sqlalchemy import create_engine

In [526]:
str_conn='mysql+pymysql://root:pasword@localhost:3306' #Conectar al servidor

cursor=create_engine(str_conn) #Cursor que apunta al servidor

cursor.execute('drop database if exists ESC;') #Lanzar query en el servidor

cursor.execute('create database ESC;') #Crear BDD ESC

In [527]:
str_conn='mysql+pymysql://root:pasword@localhost:3306/esc' #Conexión a BDD esc

cursor_db=create_engine(str_conn) #Cursor que apunta a BDD ESC

In [534]:
df_ESC.to_sql(name='puntos', con=cursor_db, if_exists='replace', index=False)

506

In [535]:
df_spoty.to_sql(name='spoty', con=cursor_db, if_exists='replace', index=False)

791

In [536]:
df_lyrics.to_sql(name='letras', con=cursor_db, if_exists='replace', index=False)

817

### Imposible vincular la tabla de Spotify (por ahora). Buscamos otro plan (conseguido con excel)

## Descargamos CSV (Kaggle) con histórico (1999-2022) del PIB por país

In [552]:
df_gdp = pd.read_csv('./GDP by Country 1999-2022.csv')

In [553]:
df_gdp.to_excel(r'/Users/Usuario/Desktop/IronHack/Bootcamp/Proyectos/3 - Proyecto ETL/GPD_Historic_1999_2022.xlsx', index = True)

In [557]:
df_gdp = pd.read_excel('./GPD_Historic_1999_2022.xlsx')

In [558]:
df_gdp

               PAIS   AÑO      GDP
0           Albania  2002  4456.00
1           Albania  2003     5.60
2           Albania  2004  7452.00
3           Albania  2005  8376.00
4           Albania  2006  9133.00
..              ...   ...      ...
855  United Kingdom  2017  3425.54
856  United Kingdom  2018  3616.82
857  United Kingdom  2019  3851.98
858  United Kingdom  2020  3108.42
859  United Kingdom  2021  3442.21

[860 rows x 3 columns]

In [560]:
lista_corregida = []
for i in df_gdp['AÑO']:
    bien = str(i)
    lista_corregida.append(bien)
df_gdp['AÑO'] = lista_corregida

In [561]:
df_gdp['clave1'] = df_gdp['PAIS']+" "+df_gdp['AÑO']

In [562]:
df_gdp

               PAIS   AÑO      GDP               clave1
0           Albania  2002  4456.00         Albania 2002
1           Albania  2003     5.60         Albania 2003
2           Albania  2004  7452.00         Albania 2004
3           Albania  2005  8376.00         Albania 2005
4           Albania  2006  9133.00         Albania 2006
..              ...   ...      ...                  ...
855  United Kingdom  2017  3425.54  United Kingdom 2017
856  United Kingdom  2018  3616.82  United Kingdom 2018
857  United Kingdom  2019  3851.98  United Kingdom 2019
858  United Kingdom  2020  3108.42  United Kingdom 2020
859  United Kingdom  2021  3442.21  United Kingdom 2021

[860 rows x 4 columns]

In [563]:
lista_corregida = []
for i in df_gdp['AÑO']:
    bien = int(i)
    lista_corregida.append(bien)
df_gdp['AÑO'] = lista_corregida

In [565]:
df_gdp.to_sql(name='gdp_country', con=cursor_db, if_exists='replace', index=False)

860

### Recargamos datos desde excel

In [37]:
df_gdp = pd.read_excel('./GPD_2002_2022.xlsx')

In [40]:
df_letras = pd.read_excel('./Letras_2002_2022.xlsx')

In [43]:
df_puntos = pd.read_excel('./Puntos_2002_2022.xlsx')

In [46]:
df_spoty = pd.read_excel('./Spoty_2002_2022.xlsx')

In [47]:
str_conn='mysql+pymysql://root:pasword@localhost:3306' #Conectar al servidor

cursor=create_engine(str_conn) #Cursor que apunta al servidor

cursor.execute('drop database if exists ESC;') #Lanzar query en el servidor

cursor.execute('create database ESC;') #Crear BDD ESC

In [48]:
str_conn='mysql+pymysql://root:pasword@localhost:3306/esc' #Conexión a BDD esc

cursor_db=create_engine(str_conn) #Cursor que apunta a BDD ESC

In [49]:
df_gdp.to_sql(name='gdp', con=cursor_db, if_exists='replace', index=False)

924

In [50]:
df_letras.to_sql(name='letras', con=cursor_db, if_exists='replace', index=False)

817

In [51]:
df_puntos.to_sql(name='puntos', con=cursor_db, if_exists='replace', index=False)

506

In [52]:
df_spoty.to_sql(name='spoty', con=cursor_db, if_exists='replace', index=False)

790

### Vamos a por YouTube (lo conseguiremos)

In [63]:
# driver.get('https://www.youtube.com/playlist?list=PL2QMi0PdRqgQ88Etn6_0syH87l7hT4QiP')

In [136]:
link = 'https://www.youtube.com/playlist?list=PLE254AB759ABA9749'

In [137]:
driver.get(link)

In [139]:
links = [e.get_attribute('href') for e in driver.find_elements(By.CLASS_NAME, 'yt-simple-endpoint.style-scope.ytd-playlist-video-renderer')]

In [141]:
driver.get(links[0])

In [146]:
driver.find_element(By.CLASS_NAME, 'style-scope.yt-formatted-string.bold').text

'186.651 visualizaciones'

In [172]:
driver.find_elements(By.CLASS_NAME, 'style-scope.ytd-toggle-button-renderer.style-text')[1].text

'962'

In [175]:
driver.find_elements(By.CLASS_NAME, 'style-scope.ytd-watch-metadata')[1].text

'Eurovision 2002 01 Cyprus *One* *Gimme* 16:9 HQ'

In [176]:
import tqdm 
from tqdm import tqdm

In [185]:
import pandas as pd

In [195]:
df_prueba = pd.DataFrame(lista, columns=['Song','Views','Likes'])

In [192]:
prueba = ['https://www.youtube.com/watch?v=TLKfSIKDGMI&list=PLE254AB759ABA9749&index=1',
        'https://www.youtube.com/watch?v=2NSR5rSk0Cs&list=PLE254AB759ABA9749&index=2',
         'https://www.youtube.com/watch?v=raLn9d5MNHw&list=PLE254AB759ABA9749&index=3']

lista = []
for link in tqdm(prueba):
    driver.get(link)
    time.sleep(random.randint(5,7))

    title = driver.find_elements(By.CLASS_NAME, 'style-scope.ytd-watch-metadata')[1].text
    views = driver.find_element(By.CLASS_NAME, 'style-scope.yt-formatted-string.bold').text
    likes = driver.find_elements(By.CLASS_NAME, 'style-scope.ytd-toggle-button-renderer.style-text')[1].text

    res = []
    res.append(title)
    res.append(views)
    res.append(likes)

    lista.append(res)
    
lista

[['Eurovision 2002 01 Cyprus *One* *Gimme* 16:9 HQ',
  '186.654 visualizaciones',
  '962'],
 ['Eurovision 2002 02 UK *Jessica Garlic* *Come Back* 16:9',
  '91.374 visualizaciones',
  '546'],
 ['Eurovision 2002 03 Austria *Manuel Ortega* *Say A Word* 16:9',
  '68.496 visualizaciones',
  '290']]

In [196]:
df_prueba

,Song,Views,Likes
0,Eurovision 2002 01 Cyprus *One* *Gimme* 16:9 HQ,186.654 visualizaciones,962
1,Eurovision 2002 02 UK *Jessica Garlic* *Come B...,91.374 visualizaciones,546
2,Eurovision 2002 03 Austria *Manuel Ortega* *Sa...,68.496 visualizaciones,290

In [417]:
listas_ESC = ['https://www.youtube.com/playlist?list=PLE254AB759ABA9749', #2002
              'https://www.youtube.com/playlist?list=PL72C2D6ECFB278B75', #2003
              'https://www.youtube.com/playlist?list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC', #2004
              'https://www.youtube.com/playlist?list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5', #2005
              'https://www.youtube.com/playlist?list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6', #2006
              'https://www.youtube.com/playlist?list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou', #2007
              'https://www.youtube.com/playlist?list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS', #2008
              'https://www.youtube.com/playlist?list=PLUX4X1NSuWBJssx__KKexD52fL59YdaZR', #2009
              'https://www.youtube.com/playlist?list=PLhcBOnqL4lysuSPA7s0gNVJtZYVPzMWOU', #2010
              'https://www.youtube.com/playlist?list=PLhcBOnqL4lyvnFfvJe7Cs0fXfWTeoPD-6', #2011
              'https://www.youtube.com/playlist?list=PL3E6CE8F0462BEE1F', #2012
              'https://www.youtube.com/playlist?list=PLhcBOnqL4lytipVRw5CvUP9VtigPCHiNe', #2013
              'https://www.youtube.com/playlist?list=PLhcBOnqL4lysLD17tmTaDoI3PFR4WcWY4', #2014
              'https://www.youtube.com/playlist?list=PLhcBOnqL4lytb48RmiW93hiGea_-Qa2py', #2015
              'https://www.youtube.com/playlist?list=PLhcBOnqL4lyumlJVxhJGjiXdWE3wwZMDA', #2016
              'https://www.youtube.com/playlist?list=PLhcBOnqL4lytwPE9ix2-6Q7aYFEvWapa3', #2017
              'https://www.youtube.com/playlist?list=PLEc-6vWkCYHPTqTNfPREZNbMgodfgS1dx', #2018
              'https://www.youtube.com/playlist?list=PLOFJBZXtfFfgmrhlNlxWYNcyOXViDmkpd', #2019
              'https://www.youtube.com/playlist?list=PLmWYEDTNOGUL69D2wj9m2onBKV2s3uT5Y', #2020
              'https://www.youtube.com/playlist?list=PLhcBOnqL4lys9lzdZWZY2T9IaLvY4EE-A', #2021
              'https://www.youtube.com/playlist?list=PLmWYEDTNOGUJVTOMa-ZEmF0y7Iwkg11e2' #2022
             ]

In [215]:
listas_prueba = ['https://www.youtube.com/playlist?list=PLE254AB759ABA9749', #2002
              'https://www.youtube.com/playlist?list=PL72C2D6ECFB278B75', #2003
              'https://www.youtube.com/playlist?list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC']

In [418]:
from selenium.webdriver.common.keys import Keys

In [419]:
links = []

for lista in tqdm(listas_ESC):
    driver.get(lista)
    time.sleep(random.randint(5,8))
    driver.find_element(By.XPATH, '//body').send_keys(Keys.END)
    
    links_lista = [e.get_attribute('href') for e in driver.find_elements(By.CLASS_NAME, 'yt-simple-endpoint.style-scope.ytd-playlist-video-renderer')]
    
    links.append(links_lista)

links_bien = []
for lista in links:
    for link in lista:
        links_bien.append(link)
        
links_bien

100%|██████████| 21/21 [04:24<00:00, 12.57s/it]

['https://www.youtube.com/watch?v=TLKfSIKDGMI&list=PLE254AB759ABA9749&index=1',
 'https://www.youtube.com/watch?v=2NSR5rSk0Cs&list=PLE254AB759ABA9749&index=2',
 'https://www.youtube.com/watch?v=raLn9d5MNHw&list=PLE254AB759ABA9749&index=3',
 'https://www.youtube.com/watch?v=oppbLQtsHqI&list=PLE254AB759ABA9749&index=4',
 'https://www.youtube.com/watch?v=Ck7ql_nJ02g&list=PLE254AB759ABA9749&index=5',
 'https://www.youtube.com/watch?v=9ZcV4kqK-R0&list=PLE254AB759ABA9749&index=6',
 'https://www.youtube.com/watch?v=gmoWe9tQSzw&list=PLE254AB759ABA9749&index=7',
 'https://www.youtube.com/watch?v=S4WuVfC_w64&list=PLE254AB759ABA9749&index=8',
 'https://www.youtube.com/watch?v=EZEEvq1i7PA&list=PLE254AB759ABA9749&index=9',
 'https://www.youtube.com/watch?v=bbWBSpf-7Eo&list=PLE254AB759ABA9749&index=10',
 'https://www.youtube.com/watch?v=yY3WUyMiJqI&list=PLE254AB759ABA9749&index=11',
 'https://www.youtube.com/watch?v=BZYnmqCJ7zI&list=PLE254AB759ABA9749&index=12',
 'https://www.youtube.com/watch?v=mRVG1vK07C8&list=PLE254AB759ABA9749&index=13',
 'https://www.youtube.com/watch?v=eOTyfceOwAw&list=PLE254AB759ABA9749&index=14',
 'https://www.youtube.com/watch?v=m_Abg3Tv8so&list=PLE254AB759ABA9749&index=15',
 'https://www.youtube.com/watch?v=ZDSd_T_Sthk&list=PLE254AB759ABA9749&index=16',
 'https://www.youtube.com/watch?v=vKcUd35CU3U&list=PLE254AB759ABA9749&index=17',
 'https://www.youtube.com/watch?v=BF_M77NmmuE&list=PLE254AB759ABA9749&index=18',
 'https://www.youtube.com/watch?v=nPvsLhdka6s&list=PLE254AB759ABA9749&index=19',
 'https://www.youtube.com/watch?v=pr9Pr3GRBA4&list=PLE254AB759ABA9749&index=20',
 'https://www.youtube.com/watch?v=b5yqQ6wijxs&list=PLE254AB759ABA9749&index=21',
 'https://www.youtube.com/watch?v=TkN8ZX-gaeY&list=PLE254AB759ABA9749&index=22',
 'https://www.youtube.com/watch?v=ZI7l5WSJPIA&list=PL72C2D6ECFB278B75&index=1',
 'https://www.youtube.com/watch?v=O62NrzJ_LuU&list=PL72C2D6ECFB278B75&index=2',
 'https://www.youtube.com/watch?v=NZ9jfwOcmro&list=PL72C2D6ECFB278B75&index=3',
 'https://www.youtube.com/watch?v=dKVhpVVDm6Q&list=PL72C2D6ECFB278B75&index=4',
 'https://www.youtube.com/watch?v=gJRXn1rW0H8&list=PL72C2D6ECFB278B75&index=5',
 'https://www.youtube.com/watch?v=KPFjADXmEPo&list=PL72C2D6ECFB278B75&index=6',
 'https://www.youtube.com/watch?v=iQx8myLohWM&list=PL72C2D6ECFB278B75&index=7',
 'https://www.youtube.com/watch?v=4ZsVBPI05Ng&list=PL72C2D6ECFB278B75&index=8',
 'https://www.youtube.com/watch?v=EmJuQIUIe3Q&list=PL72C2D6ECFB278B75&index=9',
 'https://www.youtube.com/watch?v=OhBs4VasEzs&list=PL72C2D6ECFB278B75&index=10',
 'https://www.youtube.com/watch?v=OAK0tbe4XtA&list=PL72C2D6ECFB278B75&index=11',
 'https://www.youtube.com/watch?v=e8USu9t9260&list=PL72C2D6ECFB278B75&index=12',
 'https://www.youtube.com/watch?v=4FzOTlfV8-8&list=PL72C2D6ECFB278B75&index=13',
 'https://www.youtube.com/watch?v=ojI8Z48w3Ck&list=PL72C2D6ECFB278B75&index=14',
 'https://www.youtube.com/watch?v=XAJ62IG3gBo&list=PL72C2D6ECFB278B75&index=15',
 'https://www.youtube.com/watch?v=6JWGKDA_HdU&list=PL72C2D6ECFB278B75&index=16',
 'https://www.youtube.com/watch?v=i1OBgbeYInk&list=PL72C2D6ECFB278B75&index=17',
 'https://www.youtube.com/watch?v=KuxMly_F75M&list=PL72C2D6ECFB278B75&index=18',
 'https://www.youtube.com/watch?v=gYuc67k-wYc&list=PL72C2D6ECFB278B75&index=19',
 'https://www.youtube.com/watch?v=4-bAxcWPRfs&list=PL72C2D6ECFB278B75&index=20',
 'https://www.youtube.com/watch?v=jFrO6QUl61k&list=PL72C2D6ECFB278B75&index=21',
 'https://www.youtube.com/watch?v=K1px4aab5y8&list=PL72C2D6ECFB278B75&index=22',
 'https://www.youtube.com/watch?v=1N4iLTSEwa4&list=PL72C2D6ECFB278B75&index=23',
 'https://www.youtube.com/watch?v=PNaB5C-p2I4&list=PL72C2D6ECFB278B75&index=24',
 'https://www.youtube.com/watch?v=oPr6pQRefDM&list=PL72C2D6ECFB278B75&index=25',
 'https://www.youtube.com/watch?v=10XR67NQcAc&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=1',
 'https://www.youtube.com/watch?v=z7OvpjplJ_8&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=2',
 'https://www.youtube.com/watch?v=asZwDUTEXls&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=3',
 'https://www.youtube.com/watch?v=pipamUl14A4&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=4',
 'https://www.youtube.com/watch?v=na2qDYmm7LM&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=5',
 'https://www.youtube.com/watch?v=Dq4RNHax5ow&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=6',
 'https://www.youtube.com/watch?v=NrVrCJFCejs&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=7',
 'https://www.youtube.com/watch?v=j6jSUb_RvXM&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=8',
 'https://www.youtube.com/watch?v=23h__RssJQo&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=9',
 'https://www.youtube.com/watch?v=V2nGwnq9XAE&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=10',
 'https://www.youtube.com/watch?v=Cs76CYGjfIs&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=11',
 'https://www.youtube.com/watch?v=hbKBo7QhwcI&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=12',
 'https://www.youtube.com/watch?v=WnuBcWHRMjY&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=13',
 'https://www.youtube.com/watch?v=5_NX0usepUI&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=14',
 'https://www.youtube.com/watch?v=vrzC1oGWX_I&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=15',
 'https://www.youtube.com/watch?v=i6S9vDdTWAA&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=16',
 'https://www.youtube.com/watch?v=kWS-S53Zsio&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=17',
 'https://www.youtube.com/watch?v=1QwC2gsmGkA&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=18',
 'https://www.youtube.com/watch?v=fe5Sql0wKJI&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=19',
 'https://www.youtube.com/watch?v=phHQrLvEBUU&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=20',
 'https://www.youtube.com/watch?v=_KXWrVtNFiE&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=21',
 'https://www.youtube.com/watch?v=w5mX3ecBtTI&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=22',
 'https://www.youtube.com/watch?v=DpHuREDD798&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=23',
 'https://www.youtube.com/watch?v=1_0JT8ne6_0&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=24',
 'https://www.youtube.com/watch?v=W-SFQaPP6kg&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=25',
 'https://www.youtube.com/watch?v=5NrtXPjwLB4&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=26',
 'https://www.youtube.com/watch?v=RJ8ow0_GYBQ&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=27',
 'https://www.youtube.com/watch?v=LRQgeLajKN4&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=28',
 'https://www.youtube.com/watch?v=4t2aNdDdJ0c&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=29',
 'https://www.youtube.com/watch?v=98tSrPbvEyQ&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=30',
 'https://www.youtube.com/watch?v=r-wTd_9IThc&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=31',
 'https://www.youtube.com/watch?v=oU-GqNYyeV8&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=32',
 'https://www.youtube.com/watch?v=p62weX__fTc&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=33',
 'https://www.youtube.com/watch?v=bINn55fuScE&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=34',
 'https://www.youtube.com/watch?v=2gh2F0aufEw&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=35',
 'https://www.youtube.com/watch?v=EUX3_0KM7fc&list=PLi9YM31Hg1b-w-dteFCkQJmiuhMHA8qBC&index=36',
 'https://www.youtube.com/watch?v=kiqwj6a2J4M&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=1',
 'https://www.youtube.com/watch?v=k8zTZkCdeyg&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=2',
 'https://www.youtube.com/watch?v=Vv8GmwcfR9A&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=3',
 'https://www.youtube.com/watch?v=bGY20O4Z7nM&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=4',
 'https://www.youtube.com/watch?v=w07N2nfB7KY&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=5',
 'https://www.youtube.com/watch?v=hZ5JLyGSlHU&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=6',
 'https://www.youtube.com/watch?v=mVhtWfC7RF4&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=7',
 'https://www.youtube.com/watch?v=0W-vu5G5PEE&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=8',
 'https://www.youtube.com/watch?v=nweOwnxKrdw&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=9',
 'https://www.youtube.com/watch?v=tNXwZeHHM84&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=10',
 'https://www.youtube.com/watch?v=MyChlzTADQY&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=11',
 'https://www.youtube.com/watch?v=dlG7_9-VPw0&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=12',
 'https://www.youtube.com/watch?v=JgQ242v8iVs&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=13',
 'https://www.youtube.com/watch?v=YbZjSdSNCiw&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=14',
 'https://www.youtube.com/watch?v=NqvRDkJ5StM&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=15',
 'https://www.youtube.com/watch?v=N5u6J_mbhLU&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=16',
 'https://www.youtube.com/watch?v=HwcrRmxg6uY&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=17',
 'https://www.youtube.com/watch?v=0pfaElEFo28&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=18',
 'https://www.youtube.com/watch?v=ghQZojJWxKI&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=19',
 'https://www.youtube.com/watch?v=HQhgevOeh1E&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=20',
 'https://www.youtube.com/watch?v=Kqof50gLBIo&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=21',
 'https://www.youtube.com/watch?v=OJX8RWJg7y4&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=22',
 'https://www.youtube.com/watch?v=Q5HAilNn4fs&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=23',
 'https://www.youtube.com/watch?v=1qVzlYOdhdM&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=24',
 'https://www.youtube.com/watch?v=JwglpNlPrZU&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=25',
 'https://www.youtube.com/watch?v=qUfTcrz8Zcc&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=26',
 'https://www.youtube.com/watch?v=iQqQZpHmIR0&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=27',
 'https://www.youtube.com/watch?v=DjqkIf3lQAk&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=28',
 'https://www.youtube.com/watch?v=lnY0HbiuiX4&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=29',
 'https://www.youtube.com/watch?v=S_Yy3L4mJKo&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=30',
 'https://www.youtube.com/watch?v=fa2HRtjxfIc&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=31',
 'https://www.youtube.com/watch?v=oKavU_HiHR0&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=32',
 'https://www.youtube.com/watch?v=mqvOUfdwQtw&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=33',
 'https://www.youtube.com/watch?v=09TuHCqg5t4&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=34',
 'https://www.youtube.com/watch?v=-RJS79sbMLc&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=35',
 'https://www.youtube.com/watch?v=l6rnAKD1QuU&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=36',
 'https://www.youtube.com/watch?v=J9CHcqe7xro&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=37',
 'https://www.youtube.com/watch?v=qUTIYik9cRA&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=38',
 'https://www.youtube.com/watch?v=s2uiE85oWuo&list=PL2pWIt9BRg1c37LspPHqchUhnLXBBklx5&index=39',
 'https://www.youtube.com/watch?v=z_r4IzbwDY4&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=1',
 'https://www.youtube.com/watch?v=UffvRSmRYEk&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=2',
 'https://www.youtube.com/watch?v=FbsnjmFk-1s&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=3',
 'https://www.youtube.com/watch?v=jkGqAU3m-jw&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=4',
 'https://www.youtube.com/watch?v=3JHnre0q3ow&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=5',
 'https://www.youtube.com/watch?v=SXlIN3mcsH4&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=6',
 'https://www.youtube.com/watch?v=_Q_x1lOmdpM&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=7',
 'https://www.youtube.com/watch?v=hGp3YfEj_GY&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=8',
 'https://www.youtube.com/watch?v=cXXQIbxL110&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=9',
 'https://www.youtube.com/watch?v=7lvegAK4vOA&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=10',
 'https://www.youtube.com/watch?v=zOybfT_x8Sc&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=11',
 'https://www.youtube.com/watch?v=gAh9NRGNhUU&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=12',
 'https://www.youtube.com/watch?v=-ZtZX2H6Wn4&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=13',
 'https://www.youtube.com/watch?v=meOfoHemzQY&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=14',
 'https://www.youtube.com/watch?v=IKvPzL1NSSI&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=15',
 'https://www.youtube.com/watch?v=EJDqzQ_GlW0&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=16',
 'https://www.youtube.com/watch?v=KkydPOGTJKk&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=17',
 'https://www.youtube.com/watch?v=6BzFlczwSf8&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=18',
 'https://www.youtube.com/watch?v=GzDgdDbHM6g&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=19',
 'https://www.youtube.com/watch?v=-_pDAxEtt7g&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=20',
 'https://www.youtube.com/watch?v=DBAdOlQPbwg&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=21',
 'https://www.youtube.com/watch?v=kiORqJIala8&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=22',
 'https://www.youtube.com/watch?v=11Xi8u1gkTo&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=23',
 'https://www.youtube.com/watch?v=g23U7o4NgmA&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=24',
 'https://www.youtube.com/watch?v=LIaFyFGWgnw&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=25',
 'https://www.youtube.com/watch?v=n7pL-jaEnwQ&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=26',
 'https://www.youtube.com/watch?v=mWLX83XLmCs&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=27',
 'https://www.youtube.com/watch?v=1SyPb8IOimE&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=28',
 'https://www.youtube.com/watch?v=waYpnAexrUA&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=29',
 'https://www.youtube.com/watch?v=6AfU39gHNg4&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=30',
 'https://www.youtube.com/watch?v=N8HnyH8PHVI&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=31',
 'https://www.youtube.com/watch?v=vFu5y0nP-RQ&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=32',
 'https://www.youtube.com/watch?v=eSkQmSug55g&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=33',
 'https://www.youtube.com/watch?v=QMK4h4sFFIM&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=34',
 'https://www.youtube.com/watch?v=BlIDxZ1YfVc&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=35',
 'https://www.youtube.com/watch?v=mRqhkwTIuU8&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=36',
 'https://www.youtube.com/watch?v=OYgE7O0OLyw&list=PLTdjW0IxIyG9amDW9YF9WGpQHbKHQ06E6&index=37',
 'https://www.youtube.com/watch?v=b2h52r1oOYA&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=1',
 'https://www.youtube.com/watch?v=ze5uXuSSqgg&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=2',
 'https://www.youtube.com/watch?v=PxON-jTcBPA&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=3',
 'https://www.youtube.com/watch?v=N40wpl5m0UM&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=4',
 'https://www.youtube.com/watch?v=3ibC5pps0dA&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=5',
 'https://www.youtube.com/watch?v=TBPcvkEqTG8&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=6',
 'https://www.youtube.com/watch?v=KKrOMagZnMI&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=7',
 'https://www.youtube.com/watch?v=2WsuY94n06w&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=8',
 'https://www.youtube.com/watch?v=Rebt7qd-HcI&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=9',
 'https://www.youtube.com/watch?v=LebXvZtRMrE&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=10',
 'https://www.youtube.com/watch?v=EHImNpPta7M&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=11',
 'https://www.youtube.com/watch?v=r02Lg8JIco0&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=12',
 'https://www.youtube.com/watch?v=xjo3PIABpVQ&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=13',
 'https://www.youtube.com/watch?v=zghnafACJyE&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=14',
 'https://www.youtube.com/watch?v=MVPez6Zvr8g&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=15',
 'https://www.youtube.com/watch?v=9PiGGv3asug&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=16',
 'https://www.youtube.com/watch?v=FSueQN1QvV4&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=17',
 'https://www.youtube.com/watch?v=hfjHJneVonE&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=18',
 'https://www.youtube.com/watch?v=XT6yOIC6ihI&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=19',
 'https://www.youtube.com/watch?v=QIEDaAEJyxQ&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=20',
 'https://www.youtube.com/watch?v=CVO3mEj8Udo&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=21',
 'https://www.youtube.com/watch?v=pSs1XHuFfuQ&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=22',
 'https://www.youtube.com/watch?v=BgkFJD6F7wA&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=23',
 'https://www.youtube.com/watch?v=SZzcIOvoIfo&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=24',
 'https://www.youtube.com/watch?v=5KhPzTLQBJE&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=25',
 'https://www.youtube.com/watch?v=bLpM5gMpUkI&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=26',
 'https://www.youtube.com/watch?v=e2he47-SC1k&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=27',
 'https://www.youtube.com/watch?v=mNXURugfanw&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=28',
 'https://www.youtube.com/watch?v=h9YTasUpAjw&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=29',
 'https://www.youtube.com/watch?v=k2IPKCOixtE&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=30',
 'https://www.youtube.com/watch?v=rP2OECgTA5k&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=31',
 'https://www.youtube.com/watch?v=T_gQOqKJ9ck&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=32',
 'https://www.youtube.com/watch?v=orMSTz7povE&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=33',
 'https://www.youtube.com/watch?v=lYBuHhT4q_Y&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=34',
 'https://www.youtube.com/watch?v=iBZaVQ52RQY&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=35',
 'https://www.youtube.com/watch?v=YaUROb43iDo&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=36',
 'https://www.youtube.com/watch?v=hNjMDNxNIr4&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=37',
 'https://www.youtube.com/watch?v=vhy-c5XMFks&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=38',
 'https://www.youtube.com/watch?v=RcbefpUPuLA&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=39',
 'https://www.youtube.com/watch?v=U_ESE5inG-I&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=40',
 'https://www.youtube.com/watch?v=qUK7lx0TSAI&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=41',
 'https://www.youtube.com/watch?v=gydbp99tMlg&list=PL2pWIt9BRg1eKeChzaa778gv99v2Cg5Ou&index=42',
 'https://www.youtube.com/watch?v=lUs3WNB-v44&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=1',
 'https://www.youtube.com/watch?v=CmvA5kfNsig&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=2',
 'https://www.youtube.com/watch?v=bridO-wD7c8&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=3',
 'https://www.youtube.com/watch?v=6OGVL_9P5fw&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=4',
 'https://www.youtube.com/watch?v=kIRDbmpC2PI&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=5',
 'https://www.youtube.com/watch?v=r2IXuAO3jHY&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=6',
 'https://www.youtube.com/watch?v=yXSRbgM8cvs&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=7',
 'https://www.youtube.com/watch?v=wG8p0fSHc3U&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=8',
 'https://www.youtube.com/watch?v=GgNU5_htNXk&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=9',
 'https://www.youtube.com/watch?v=6m2HZD3eXfI&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=10',
 'https://www.youtube.com/watch?v=RqYgZKpMhh4&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=11',
 'https://www.youtube.com/watch?v=bCk419FVaj8&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=12',
 'https://www.youtube.com/watch?v=bA_qUXpQFfg&list=PLnFXdA3kKLeVBajMInrSm_6buMk2I1GqS&index=13',

In [221]:
len(links_bien)

817

In [222]:
lista = []
for link in tqdm(links_bien):
    try:
        driver.get(link)
        time.sleep(random.randint(7,10))

        title = driver.find_elements(By.CLASS_NAME, 'style-scope.ytd-watch-metadata')[1].text
        views = driver.find_element(By.CLASS_NAME, 'style-scope.yt-formatted-string.bold').text
        likes = driver.find_elements(By.CLASS_NAME, 'style-scope.ytd-toggle-button-renderer.style-text')[1].text

        res = []
        res.append(title)
        res.append(views)
        res.append(likes)

        lista.append(res)
    
    except:
        continue
    
df_prueba = pd.DataFrame(lista)

100%|██████████| 817/817 [3:59:10<00:00, 17.56s/it]

In [223]:
df_prueba

,0,1,2
0,Eurovision 2002 01 Cyprus *One* *Gimme* 16:9 HQ,186.656 visualizaciones,962
1,Eurovision 2002 02 UK *Jessica Garlic* *Come B...,91.376 visualizaciones,546
2,Eurovision 2002 03 Austria *Manuel Ortega* *Sa...,68.501 visualizaciones,290
3,Eurovision 2002 05 Spain *Rosa* *Europe's Livi...,23.995 visualizaciones,148
4,Eurovision 2002 06 Croatia *Vesna Pisarović* *...,86.321 visualizaciones,505
...,...,...,...
812,REDDI - The Show - LIVE - Denmark 🇩🇰 - First S...,364.088 visualizaciones,8552
813,Mia Dimšić - Guilty Pleasure - LIVE - Croatia ...,832.624 visualizaciones,14.078
814,Citi Zēni - Eat Your Salad - LIVE - Latvia 🇱🇻 ...,1.296.619 visualizaciones,29.043
815,LPS - Disko - LIVE - Slovenia 🇸🇮 - First Semi-...,612.721 visualizaciones,15.579
816,Intelligent Music Project - Intention - LIVE -...,313.306 visualizaciones,5805

In [ ]:
df_prueba.rename('song', 'views', 'likes')

In [224]:
df_YT = df_prueba

In [234]:
df_YT.rename({0:'SONG', 1:'VIEWS',2:'LIKES'}, axis=1, inplace=True)

In [241]:
df_YT['VIEWS'][1].split()[0]

'91.376'

In [243]:
lista_corregida = [e.split()[0] for e in df_YT['VIEWS']]
df_YT['VIEWS'] = lista_corregida

In [244]:
df_YT

                                                  SONG      VIEWS   LIKES
0      Eurovision 2002 01 Cyprus *One* *Gimme* 16:9 HQ    186.656     962
1    Eurovision 2002 02 UK *Jessica Garlic* *Come B...     91.376     546
2    Eurovision 2002 03 Austria *Manuel Ortega* *Sa...     68.501     290
3    Eurovision 2002 05 Spain *Rosa* *Europe's Livi...     23.995     148
4    Eurovision 2002 06 Croatia *Vesna Pisarović* *...     86.321     505
..                                                 ...        ...     ...
812  REDDI - The Show - LIVE - Denmark 🇩🇰 - First S...    364.088    8552
813  Mia Dimšić - Guilty Pleasure - LIVE - Croatia ...    832.624  14.078
814  Citi Zēni - Eat Your Salad - LIVE - Latvia 🇱🇻 ...  1.296.619  29.043
815  LPS - Disko - LIVE - Slovenia 🇸🇮 - First Semi-...    612.721  15.579
816  Intelligent Music Project - Intention - LIVE -...    313.306    5805

[817 rows x 3 columns]

In [246]:
df_YT['SONG'].unique()

array(['Eurovision 2002 01 Cyprus *One* *Gimme* 16:9 HQ',
       'Eurovision 2002 02 UK *Jessica Garlic* *Come Back* 16:9',
       'Eurovision 2002 03 Austria *Manuel Ortega* *Say A Word* 16:9',
       "Eurovision 2002 05 Spain *Rosa* *Europe's Living A Celebration* 16:9 HQ",
       'Eurovision 2002 06 Croatia *Vesna Pisarović* *Everything I Want* 16:9 HQ',
       'Eurovision 2002 07 Russia *Prime Minister* *Northern Girl* 16:9 HQ',
       'Eurovision 2002 08 Estonia *Sahlene* *Runaway* 16:9 HQ',
       'Eurovision 2002 09 FYR Macedonia *Karolina* *It depends on us* 16:9 HQ',
       'Eurovision 2002 11 Switzerland *Francine Jordi* *Dans le jardin de mon âme* 16:9 HQ',
       'Eurovision 2002 12 Sweden *Afro-Dite* *Never Let It Go* 16:9 HQ',
       'Eurovision 2002 13 Finland *Laura* *Addicted To You* 16:9 HQ',
       'Eurovision 2002 14 Denmark *Malene* *Tell Me Who You Are* 16:9 HQ',
       'Eurovision 2002 15 Bosnia & Herzegovina *Maja* *Na Jastuku Za Dvoje* 16:9 HQ',
       'Eurovision 2002 16 Belgium *Sergio & the Ladies* *Sister* 16:9 HQ',
       'Eurovision 2002 17 France *Sandrine François* *Il Fait Du Temps* 16:9 HQ',
       "Eurovision 2002 18 Germany *Corrina May* *I Can't Live Without Music* 16:9 HQ",
       'Eurovision 2002 19 Turkey *Buket Bengisu* *Leylaklar Soldu Kalbinde* 16:9 HQ',
       'Eurovision 2002 20 Malta *Ira Losco* *7th Wonder* 16:9 HQ',
       'Eurovision 2002 21 Romania *Monica Anghel & Marcel Pavel* *Tell Me Why* 16:9 HQ',
       'Eurovision 2002 22 Slovenia *Sestre* *Samo Ljubezen* 16:9 HQ',
       'Eurovision 2002 23 Latvia *Marie N* *I Wanna* 16:9 HQ',
       'Eurovision 2002 24 Lithuania *Aivaras* *Happy You* 16:9 HQ',
       'Eurovision 2003 01 Iceland *Birgitta Haukdal* *Open Your Heart* 16:9',
       'Eurovision 2003 02 Austria *Alf Poier* *Weil der Mensch zahlt* 16:9',
       "Eurovision 2003 03 Ireland *Mickey Joe Harte* *We've got the world*16:9",
       'Eurovision 2003 04 Turkey *Sertab Erener* *Everyway That I Can*16:9',
       'Eurovision 2003 05 Malta *Lynn Chircop* *To Dream Again* 16:9',
       'Eurovision 2003 06 Bosnia & Herzegovina *Mija Martina* *Ne brini* 16:9',
       'Eurovision 2003 07 Portugal *Rita Guerra* *Deixa-me sonhar* 16:9',
       'Eurovision 2003 08 Croatia *Claudia Beni* *Vise nisam tvoja* 16:9',
       'Eurovision 2003 09 Cyprus *Stelios Konstantas* *Feeling Alive* 16:9 HQ',
       "Eurovision 2003 10 Germany *Lou* *Let's Get Happy* 16:9",
       "Eurovision 2003 11 Russia *t.A.T.u* *Ne ver', ne boysia*16:9 HQ",
       'Eurovision 2003 12 Spain *Beth* *Dime* 16:9 HQ',
       'Eurovision 2003 13 Israel *Lior Narkis* *Words Of Love* 16:9 HQ',
       'Eurovision Song Contest 2003 14 Netherlands *Esther Hart* *One More Night* 16:9',
       'Eurovision 2003 15 United Kingdom *Jemini* *Cry Baby* 16:9 HQ',
       'Eurovision 2003 16 Ukraine *Olexandr* *Hasta La Vista* 16:9 HQ',
       'Eurovision 2003 17 Greece *Mando* *Never Let You Go* 16:9 HQ',
       "Eurovision 2003 18 Norway *Jostein Hasselgård* *I'm Not Afraid To Move On* 16:9 HQ",
       'Eurovision 2003 19 France *Louisa Baileche* *Monts et mervielles* 16:9 HQ',
       'Eurovision 2003 21 Latvia *F.L.Y* *Hello From Mars* 16:9 HQ',
       'Eurovision 2003 22 Belgium *Urban Trad* *Sanomi* 16:9 HQ',
       'Eurovision 2003 23 Estonia *Ruffus* *Eighties Coming Back*16:9 HQ',
       "Eurovision 2003 24 Romania *Nicola* *Don't Break My Heart* 16:9 HQ",
       'Eurovision 2003 25 Sweden *FAME* *Give Me Your Love* 16:9 HQ',
       'Eurovision 2003 26 Slovenia *Karmen* *Nanana* 16:9 HQ',
       'Ruslana - Wild Dances (Ukraine) - LIVE - 2004 Eurovision Song Contest',
       'Zeljko Joksimovic - Lane Moje (Serbia & Montenegro) 2004 Eurovision Song Contest',
       'Sakis Rouvas - Shake It (Greece) 2004 Eurovision Song Contest',
       'Athena - For Real (Turkey) 2004 Eurovision Song Contest',
       'Lena Philipsson - It Hurts (Sweden) 2004 Eurovision Song Contest',
       'Lisa Andreas - Stronger Every Minute (Cyprus) 2004 Eurovision Song Contest',
       'Anjeza Shahini - The Image Of You (Albania) 2004 Eurovision Song Contest',
       "Max - Can't Wait Until Tonight (Germany) 2004 Eurovision Song Contest",
       'Deen - In The Disco (Bosnia And Herzegovina) 2004 Eurovision Song Contest',
       'Ramón - Para Llenarme De Ti (Spain) 2004 Eurovision Song Contest',
       'Julia Savicheva - Believe Me (Russia) 2004 Eurovision Song Contest',
       'Julie & Ludwig - On Again ... Off Again (Malta) 2004 Eurovision Song Contest',
       'Ivan Mikulic - You Are The Only One (Croatia) 2004 Eurovision Song Contest',
       'Tose Proeski - Life (F.Y.R. Macedonia) 2004 Eurovision Song Contest',
       'Jonatan Cerrada - A Chaque Pas (France) 2004 Eurovision Song Contest',
       'James Fox - Hold On To Our Love (United Kingdom) 2004 Eurovision Song Contest',
       'Blue Cafe - Love Song (Poland) 2004 Eurovision Song Contest',
       'Sanda Ladosi - I Admit (Romania) 2004 Eurovision Song Contest',
       'Jónsi - Heaven (Iceland) 2004 Eurovision Song Contest',
       'Re-union - Without You (The Netherlands) 2004 Eurovision Song Contest',
       'Tie Break - Du Bist (Austria) 2004 Eurovision Song Contest',
       'Xandee - 1 Life (Belgium) 2004 Eurovision Song Contest',
       'Chris Doran - If My World Stopped Turning (Ireland) 2004 Eurovision Song Contest',
       'Knut Anders Sørum - High (Norway) 2004 Eurovision Song Contest',
       'Eurovision 2004 Semi Final 17 Estonia *Neiokõsõ* *Tii* 16:9 HQ',
       "Eurovision 2004 Semi Final 05 Israel *David D'Or* *To Believe* 16:9 HQ",
       'Eurovision 2004 Semi Final 19 Denmark *Thomas Thordarson* *Shame On You* 16:9 HQ',
       'Eurovision 2004 Semi Final 01 Finland *Jari Sillanpaa* *Takes 2 To Tango* 16:9',
       'Eurovision 2004 Semi Final 07 Portugal *Sofia Vitória* *Foi Magia* 16:9 HQ',
       "Eurovision 2004 Semi Final 12 Lithuania *Linas & Simone* *What's Happened To Your Love?* 16:9 HQ",
       'Eurovision 2004 Semi Final 04 Latvia *Fomins & Kleins* *Dziesma par laimi* 16:9 HQ',
       'Eurovision 2004 Semi Final 06 Andorra *Marta Roure* *Jugarem a estimar-nos* 16:9 HQ',
       'Eurovision 2004 Semi Final 09 Monaco *Maryon* *Notre planète* 16:9 HQ',
       'Eurovision 2004 Semi Final 02 Belarus *Aleksandra & Konstantin* *My Galileo* 16:9',
       'Eurovision 2004 Semi Final 16 Slovenia *Platin* *Stay Forever* 16:9 HQ',
       'Eurovision 2004 Semi Final 03 Switzerland *Piero & The Music Stars* *Celebrate!* 16:9 HQ',
       'NOX - Forogj Világ (Hungary) Live - Eurovision Song Contest 2005',
       'Javine - Touch My Fire (United Kingdom) Live - Eurovision Song Contest 2005',
       'Chiara - Angel (Malta) 2005 Eurovision Song Contest',
       'Luminita Anghel & Sistem - Let Me Try (Romania) 2005 Eurovision Song Contest',
       'Wig Wam - In My Dreams (Norway) Live - Eurovision Song Contest 2005',
       'Gülseren - Rimi Rimi Ley (Turkey) Live - Eurovision Song Contest 2005',
       'Zdob Si Zdub - Boonika Bate Toba (Moldova) Live - Eurovision 2005',
       'Ledina Celo - Tomorrow I Go (Albania) Live - Eurovision Song Contest 2005',
       'Constantinos Christoforou - Ela Ela (Cyprus) Live - Eurovision 2005',
       'Son De Sol - Brujería (Spain) Live - Eurovision Song Contest 2005',
       "Shiri Maymon - Hasheket Shenish'ar (Israel) Live - Eurovision 2005",
       'No Name - Zauvijek Moja (Serbia and Montenegro) Live - Eurovision 2005',
       'Jakob Sveistrup - Talking To You (Denmark) Live - Eurovision Song Contest 2005',
       'Martin Stenmarck - Las Vegas (Sweden) Live - Eurovision Song Contest 2005',
       'Martin Vucic - Make My Day (F.Y.R. Macedonia) Live - Eurovision Song Contest 2005',
       'Greenjolly - Razom Nas Bahato (Ukraine) Live - Eurovision Song Contest 2005',
       'Gracia - Run & Hide (Germany) Live - Eurovision Song Contest 2005',
       'Boris Novkovic feat. Lado members - Vukovi Umiru Sami (Croatia) Live - Eurovision 2005',
       'Helena Paparizou - My Number One (Greece) 2005 Eurovision Song Contest',
       'Natalia Podolskaya - Nobody Hurt No One (Russia) Live - Eurovision Song Contest 2005',
       'Feminnem - Call Me (Bosnia & Herzegovina) Live - Eurovision Song Contest 2005',
       'Vanilla Ninja - Cool Vibes (Switzerland) Live - Eurovision Song Contest 2005',
       'Walter & Kazha - The War Is Not Over (Latvia) Live - Eurovision Song Contest 2005',
       'Ortal - Chacun Pense à Soi (France) Live - Eurovision Song Contest 2005',
       'Global.Kryner - Y Así (Austria) Live - Eurovision Song Contest 2005',
       'Laura and the Lovers - Little By Little (Lithuania) Live - Eurovision 2005',
       '2B - Amar (Portugal) Live - Eurovision Song Contest 2005',
       'Lise Darly - Tout De Moi (Monaco)',
       'Angelica Agurbash - Love Me Tonight (Belarus) Live - Eurovision 2005',
       'Glennis Grace - My Impossible Dream (The Netherlands) Live - Eurovision 2005',
       'Selma - If I Had Your Love (Iceland) Live - Eurovision Song Contest 2005',
       'Eurovision 2005 Semi Final 11 Belgium *Nuno Resende* *Le Grand Soir* 16:9 HQ',
       "Suntribe - Let's Get Loud (Estonia) Live - Eurovision Song Contest 2005",
       'Geir Rönning - Why (Finland) Live - Eurovision Song Contest 2005',
       'Marian van de Wal - La Mirada Interior (Andorra) Live - Eurovision Song Contest 2005',
       'Kaffe - Lorraine (Bulgaria) Live - Eurovision Song Contest 2005',
       'Donna and Joe - Love? (Ireland) Live - Eurovision Song Contest 2005',
       'Omar Naber - Stop (Slovenia) Live - Eurovision Song Contest 2005',
       'Ivan & Delfin - Czarna Dziewczyna (Poland) Live - Eurovision Song Contest 2005',
       'Luiz Ejlli - Zjarr E Ftohtë (Albania) 2006 Semi-Final',
       'Jennifer - Sense Tu (Andorra) 2006 Semi-Final',
       'André - Without Your Love (Armenia) 2006 Final',
       'Polina Smolova - Mum (Belarus) 2006 Semi-Final',
       "Kate Ryan - Je T'adore (Belgium) 2006 Semi-Final",
       'Hari Mata Hari - Lejla (Bosnia and Herzegovina) 2006 Eurovision Song Contest',
       'Mariana Popova - Let Me Cry (Bulgaria) 2006 Semi-Final',
       'Severina - Moja Š\x9atikla (Croatia) 2006 Final',
       'Annet Artani - Why Angels Cry (Cyprus) 2006 Semi-Final',
       'Sidsel Ben Semmane - Twist Of Love (Denmark) 2006 Final',
       'Sandra - Through My Window (Estonia) 2006 Semi-Final',
       'Lordi - Hard Rock Hallelujah (Finland) 2006 Eurovision Song Contest Winner',
       'Virginie Pouchin - Il était Temps (France) 2006 Final',
       'Elena Risteska - Ninanajna (F.Y.R. Macedonia) 2006 Final',
       'Texas Lightning - No, No, Never (Germany) 2006 Final',
       'Anna Vissi - Everything (Greece) 2006 Final',
       'Silvia Night - Congratulations (Iceland) 2006 Semi-Final',
       'Brian Kennedy - Every Song Is A Cry For Love (Ireland) 2006 Final',
       'Eddie Butler - Ze Hazman (Israel) 2006 Final',
       'Cosmos - I Hear Your Heart (Latvia) 2006 Final',
       'LT United - We Are The Winners (Lithuania) 2006 Final',
       'Fabrizio Faniello - I Do (Malta) 2006 Final',
       'Arsenium & Natalia Gordienko - Loca (Moldova) 2006 Final',
       'Séverine Ferrer - La Coco-dance (Monaco) 2006 Semi-Final',
       'Christine Guldbrandsen - Alvedansen (Norway) 2006 Final',
       'Ich Troje - Follow My Heart (Poland) 2006 Semi-Final',
       'Nonstop - Coisas De Nada (Portugal) 2006 Semi-Final',
       'Mihai Traistariu - Tornero (Romania) 2006 Final',
       'Dima Bilan - Never Let You Go (Russia) 2006 Eurovision Song Contest',
       'Anz\x9eej De\x9ean - Mr. Nobody (Slovenia) 2006 Semi-Final',
       'Las Ketchup - Bloody Mary (Spain) 2006 Final',
       'Carola - Invincible (Sweden) 2006 Final',
       'Six4One - If We All Give A Little (Switzerland) 2006 Final',
       'Treble - Amambanda (The Netherlands) 2006 Semi-Final',
       'Sibel Tüzün - Superstar (Turkey) 2006 Final',
       'Tina Karol - Show Me Your Love (Ukraine) 2006 Final',
       'Daz Sampson - Teenage Life (United Kingdom) 2006 Final',
       'Marija Sestic - Rijeka Bez Imena (Bosnia & Herzegovina) Live 2007 Eurovision Song Contest',
       "D'Nash - I Love You Mi Vida (Spain) Live 2007 Eurovision Song Contest",
       'Dmitry Koldun - Work Your Magic (Belarus) Live 2007 Eurovision Song Contest',
       "Dervish - They Can't Stop The Spring (Ireland) live 2007 Eurovision Song Contest",
       'Hanna Pakarinen - Leave Me Alone (Finland) Live 2007 Eurovision Song Contest',
       'Karolina Goceva - Mojot svet (Macedonia Final - Eurosong 2007) (HD)',
       'Alenka Gotar - Cvet Z Juga (Slovenia) Live 2007 Eurovision Song Contest',
       'Magdi Rúzsa - Unsubstantial Blues (Hungary) Live 2007 Eurovision Song Contest',
       '4Fun - Love Or Leave (Lithuania) Live 2007 Eurovision Song Contest',
       'Sarbel - Yassou Maria (Greece) Live 2007 Eurovision Song Contest',
       'Sopho - Visionary Dream (Georgia) Live 2007 Eurovision Song Contest',
       'The Ark - The Worrying Kind (Sweden) Live 2007 Eurovision Song Contest',
       "Les Fatals Picards - L'amour à La Française (France) Live 2007 Eurovision Song Contest",
       'Bonaparti.lv - Questa Notte (Latvia) Live 2007 Eurovision Song Contest',
       'Serebro - Song 1 (Russia) 2007 Eurovision Song Contest',
       "Roger Cicero - Frauen regier'n die Welt (Germany) 2007 Eurovision Song Contest",
       'Marija Šerifović - Molitva (Serbia) 2007 Eurovision Song Contest',
       'Verka Serduchka - Dancing Lasha Tumbai (Ukraine) 2007 Eurovision Song Contest',
       'Scooch - Flying The Flag (United Kingdom) Live 2007 Eurovision Song Contest',
       'Todomondo - Liubi, Liubi, I Love You (Eurovision Song Contest 2007)',
       'Elitsa Todorova & Stoyan Yankulov - Water (Bulgaria) Live 2007 Eurovision Song Contest',
       'Kenan Dogulu - Shake It Up Shekerim (Turkey) Live 2007 Eurovision Song Contest',
       'Hayko - Anytime You Need (Armenia) Live 2007 Eurovision Song Contest',
       'Natalia Barbu - Fight (Moldova) Live 2007 Eurovision Song Contest',
       'Teapacks - Push The Button (Israel) Live 2007 Eurovision Song Contest',
       'Evridiki - Comme Ci, Comme ça (Cyprus) Live 2007 Eurovision Song Contest',
       'Eiríkur Hauksson - Valentine Lost (Iceland) Live 2007 Eurovision Song Contest',
       'Stevan Faddy - Ajde Kroci (Montenegro) Live 2007 Eurovision Song Contest',
       'DJ BoBo - Vampires Are Alive (Switzerland) Live 2007 Eurovision Song Contest',
       'Edsilia Rombley - On Top Of The World (The Netherlands) Live 2007 Eurovision Song Contest',
       'Aida & Frederik Ndoci - Hear My Plea (Albania) Live 2007 Eurovision Song Contest',
       'DQ - Drama Queen (Denmark) Live 2007 Eurovision Song Contest',
       'Dragonfly feat. Dado Topic - Vjerujem U Ljubav (Croatia) Live 2007 Eurovision Song Contest',
       'The Jet Set - Time To Party (Poland) live 2007 Eurovision Song Contest',
       'Kabát - Malá Dáma (Czech Republic) Live 2007 Eurovision Song Contest',
       'Sabrina - Dança Comigo (vem Ser Feliz) (Portugal) Live 2007 Eurovision Song Contest',
       'Guri Schanke - Ven A Bailar Conmigo (Norway) Live 2007 Eurovision Song Contest',
       'Olivia Lewis - Vertigo (Malta) Live 2007 Eurovision Song Contest',
       'Anonymous - Salvem El Món (Andorra) Live 2007 Eurovision Song Contest',
       'Gerli Padar - Partners In Crime (Estonia) Live 2007 Eurovision Song Contest',
       "The KMG's - Love Power (Belgium) Live 2007 Eurovision Song Contest",
       'Eric Papilaya - Get A Life - Get Alive (Austria) Live 2007 Eurovision Song Contest',
       'Eurovision 2008 Semi Final 1 12 Andorra *Gisela* *Casanova 16:9',
       'Olta Boka - Zemrën E Lamë Peng (Albania) Live 2008 Eurovision Song Contest',
       'Sirusho - Qele, Qele (Armenia) Live 2008 Eurovision Song Contest',
       'Elnur & Samir - Day After Day (Azerbaijan) Live 2008 Eurovision Song Contest',
       'Laka - Pokušaj (Bosnia & Herzegovina) Live 2008 Eurovision Song Contest',
       'Eurovision 2008 Semi Final 1 06 Belgium *Ishtar* *O Julissi* 16:9 HQ',
       'Eurovision 2008 Semi Final 2 12 Bulgaria *Deepzone & Balthazar* *DJ, Take Me Away* 16:9 HQ',
       'Eurovision 2008 Semi Final 2 09 Belarus *Ruslan Alehno* *Hasta La Vista* 16:9 HQ',
       'Eurovision 2008 Semi Final 2 07 Switzerland *Paolo Meneguzzi* *Era Stupendo* 16:9 HQ',
       'Eurovision 2008 Semi Final 2 17 Cyprus *Kadi Evdokia* *Femme Fatale* 16:9 HQ',
       'Eurovision 2008 Semi Final 2 08 Czech Republic *Tereza Kerndlová* *Have Some Fun* 16:9 HQ',
       'No Angels - Disappear (Germany) Live 2008 Eurovision Song Contest',
       'Simon Mathew - All Night Long (Denmark) Live 2008 Eurovision Song Contest',
       'Eurovision 2008 Semi Final 1 03 Estonia *Kreisiraadio* *Leto Svet* 16:9 HQ',
       'Rodolfo Chikilicuatre - Baila El Chiki Chiki (Spain) Live 2008 Eurovision Song Contest',
       'Teräsbetoni - Missä Miehet Ratsastaa (Finland) Live 2008 Eurovision Song Contest',
       'Sébastien Tellier - Divine (France) Live 2008 Eurovision Song Contest',
       'Andy Abraham - Even If (United Kingdom) Live 2008 Eurovision Song Contest',
       'Diana Gurtskaya - Peace Will Come (Georgia) Live 2008 Eurovision Song Contest',
       'Kalomira - My Secret Combination (Greece) Live 2008 Eurovision Song Contest',
       'Kraljevi Ulice & 75 Cents - Romanca (Croatia) Live 2008 Eurovision Song Contest',
       'Eurovision 2008 Semi Final 2 15 Hungary *Csézy* *Candlelight* 16:9 HQ',
       'Eurovision 2008 Semi Final 1 11 Ireland *Dustin The Turkey* *Irlande Douze Pointe* 16:9 HQ',
       'Boaz - The Fire In Your Eyes (Israel) Live 2008 Eurovision Song Contest',
       'Euroband - This Is My Life (Iceland) Live 2008 Eurovision Song Contest',
       'Eurovision 2008 Semi Final 2 05 Lithuania *Jeronimas Milius* *Nomads In The Night* 16:9 HQ',
       'Pirates Of The Sea - Wolves Of The Sea (Latvia) Live 2008 Eurovision Song Contest',
       'Eurovision 2008 Semi Final 1 Moldova *Geta Burlacu* *A Century Of Love* 16:9',
       'Eurovision 2008 Semi Final 1 01 Montenegro *Stefan Filipović* *Zauvijek Volim Te* 16:9 HQ',
       'Eurovision 2008 Semi Final 2 18 FYR Macedonia *Tamara, Vrčak and Adrijan* *Let Me Love You* 16:9 HQ',
       'Eurovision 2008 Semi Final 2 16 Malta *Morena* *Vodka* 16:9 HQ',
       "Eurovision 2008 Semi Final 1 15 Netherlands *Hind* *Your Heart Belong's To Me* 16:9 HQ",
       'Maria - Hold On Be Strong (Norway) Live 2008 Eurovision Song Contest',
       'Isis Gee - For Life (Poland) Live 2008 Eurovision Song Contest',
       'Vânia Fernandes - Senhora Do Mar (Negras Águas) (Portugal) Live 2008 Eurovision Song Contest',
       'Nico & Vlad - Pe-o Margine De Lume (Romania) LIVE 2008 Eurovision Song Contest',
       'Jelena Tomašević feat. Bora Dugic - Oro (Serbia) Live 2008 Eurovision Song Contest',
       'Dima Bilan - Believe (Russia) Live 2008 Eurovision Song Contest',
       'Charlotte Perrelli - Hero (Sweden) Live 2008 Eurovision Song Contest',
       'Eurovision 2008 Semi Final 1 08 Slovenia *Rebeka Dremelj* *Vrag Naj Vzame* 16:9 HQ',
       'Eurovision 2008 Semi Final 1 05 San Marino *Miodio* *Complice* 16:9 HQ',
       'Mor ve Ötesi - Deli (Turkey) Live 2008 Eurovision Song Contest',
       'Ani Lorak - Shady Lady (Ukraine) Live 2008 Eurovision Song Contest',
       '#EurovisionAgain #StayHome\nEurovision Song Contest 2009 - Grand Final - Full Show',
       'Sasha Son - Love (Lithuania) LIVE 2009 Eurovision Song Contest',
       'Noa & Mira Awad - There Must Be Another Way (Israel) LIVE 2009 Eurovision Song Contest',
       "Patricia Kaas - Et S'il Fallait Le Faire (France) LIVE 2009 Eurovision Song Contest",
       'Malena Ernman - La Voix (Sweden) LIVE 2009 Eurovision Song Contest',
       'Igor Cukrov feat. Andrea - Lijepa Tena (Croatia) LIVE 2009 Eurovision Song Contest',
       'Flor-de-lis - Todas As Ruas Do Amor (Portugal) LIVE 2009 Eurovision Song Contest',
       'Yohanna - Is It True (Iceland) LIVE 2009 Eurovision Song Contest',

In [247]:
lista_anio = []
for song in df_YT['SONG']:
    if "2002" in song:
        lista_anio.append(2002)
    else:
        break

In [263]:
lista_anios = []

anios = [str(i) for i in range(2002,2023)]

encontrado = False

for song in df_YT['SONG']:
    
    i=0
   
    while (i < (len(anios))) and encontrado == False:
        
        if song.find(anios[i]) >= 0:
            
            lista_anios.append(anios[i])
            encontrado = True
        
        i+=1
    
    if encontrado == True:
        encontrado = False
    
    else:
        lista_anios.append('BUSCAR_A_MANITA')
        
lista_anios

['2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2002',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2003',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2004',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 'BUSCAR_A_MANITA',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2005',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2006',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2007',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2008',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 '2009',
 'BUSCAR_A_MANITA',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2010',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2011',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2012',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2013',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2014',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2015',
 '2016',
 'BUSCAR_A_MANITA',
 '2016',
 '2016',
 '2016',
 '2016',
 '2016',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 '2016',
 '2016',
 '2016',
 '2016',
 'BUSCAR_A_MANITA',
 '2016',
 '2016',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 '2016',
 'BUSCAR_A_MANITA',
 '2016',
 '2016',
 '2016',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 '2016',
 '2016',
 '2016',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 'BUSCAR_A_MANITA',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2017',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 'BUSCAR_A_MANITA',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2018',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 '2019',
 'BUSCAR_A_MANITA',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2020',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2021',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022',
 '2022']

In [264]:
df_YT['YEAR'] = lista_anios

In [268]:
lista_paises = []

paises = ['Cyprus', 'United Kingdom', 'Austria', 'Greece', 'Spain','Croatia', 'Russia', 'Estonia', 'North Macedonia', 
          'Israel','Switzerland', 'Sweden', 'Finland', 'Denmark','Bosnia', 'Belgium', 'France', 'Germany', 
          'Turkey','Malta', 'Romania', 'Slovenia', 'Latvia', 'Lithuania', 'Iceland','Ireland', 'Portugal','Ukraine', 'Norway',
          'Poland', 'Belarus', 'Andorra', 'Monaco', 'Albania','Serbia and Montenegro', 'Moldova', 'Hungary', 'Bulgaria',
          'Armenia', 'Georgia', 'Montenegro', 'Serbia', 'Czech Republic','San Marino', 'Azerbaijan', 'Slovakia', 'Italy', 
          'Australia','The Netherlands', 'Macedonia', 'Netherlands'] 
           #Arreglar luego Bosnia & Herzegovina, Netherlands, Macedonia...

encontrado = False

for song in df_YT['SONG']:
    
    i=0
   
    while (i < (len(paises))) and encontrado == False:
        
        if song.find(paises[i]) >= 0:
            
            lista_paises.append(paises[i])
            encontrado = True
        
        i+=1
    
    if encontrado == True:
        encontrado = False
    
    else:
        lista_paises.append('¡BUSCAR_A_MANITA!')
        
lista_paises

['Cyprus',
 '¡BUSCAR_A_MANITA!',
 'Austria',
 'Spain',
 'Croatia',
 'Russia',
 'Estonia',
 'Macedonia',
 'Switzerland',
 'Sweden',
 'Finland',
 'Denmark',
 'Bosnia',
 'Belgium',
 'France',
 'Germany',
 'Turkey',
 'Malta',
 'Romania',
 'Slovenia',
 'Latvia',
 'Lithuania',
 'Iceland',
 'Austria',
 'Ireland',
 'Turkey',
 'Malta',
 'Bosnia',
 'Portugal',
 'Croatia',
 'Cyprus',
 'Germany',
 'Russia',
 'Spain',
 'Israel',
 'Netherlands',
 'United Kingdom',
 'Ukraine',
 'Greece',
 'Norway',
 'France',
 'Latvia',
 'Belgium',
 'Estonia',
 'Romania',
 'Sweden',
 'Slovenia',
 'Ukraine',
 'Montenegro',
 'Greece',
 'Turkey',
 'Sweden',
 'Cyprus',
 'Albania',
 'Germany',
 'Bosnia',
 'Spain',
 'Russia',
 'Malta',
 'Croatia',
 'Macedonia',
 'France',
 'United Kingdom',
 'Poland',
 'Romania',
 'Iceland',
 'The Netherlands',
 'Austria',
 'Belgium',
 'Ireland',
 'Norway',
 'Estonia',
 'Israel',
 'Denmark',
 'Finland',
 'Portugal',
 'Lithuania',
 'Latvia',
 'Andorra',
 'Monaco',
 'Belarus',
 'Slovenia',
 'Switzerland',
 'Hungary',
 'United Kingdom',
 'Malta',
 'Romania',
 'Norway',
 'Turkey',
 'Moldova',
 'Albania',
 'Cyprus',
 'Spain',
 'Israel',
 'Serbia and Montenegro',
 'Denmark',
 'Sweden',
 'Macedonia',
 'Ukraine',
 'Germany',
 'Croatia',
 'Greece',
 'Russia',
 'Bosnia',
 'Switzerland',
 'Latvia',
 'France',
 'Austria',
 'Lithuania',
 'Portugal',
 'Monaco',
 'Belarus',
 'The Netherlands',
 'Iceland',
 'Belgium',
 'Estonia',
 'Finland',
 'Andorra',
 'Bulgaria',
 'Ireland',
 'Slovenia',
 'Poland',
 'Albania',
 'Andorra',
 'Armenia',
 'Belarus',
 'Belgium',
 'Bosnia',
 'Bulgaria',
 'Croatia',
 'Cyprus',
 'Denmark',
 'Estonia',
 'Finland',
 'France',
 'Macedonia',
 'Germany',
 'Greece',
 'Iceland',
 'Ireland',
 'Israel',
 'Latvia',
 'Lithuania',
 'Malta',
 'Moldova',
 'Monaco',
 'Norway',
 'Poland',
 'Portugal',
 'Romania',
 'Russia',
 'Slovenia',
 'Spain',
 'Sweden',
 'Switzerland',
 'The Netherlands',
 'Turkey',
 'Ukraine',
 'United Kingdom',
 'Bosnia',
 'Spain',
 'Belarus',
 'Ireland',
 'Finland',
 'Macedonia',
 'Slovenia',
 'Hungary',
 'Lithuania',
 'Greece',
 'Georgia',
 'Sweden',
 'France',
 'Latvia',
 'Russia',
 'Germany',
 'Serbia',
 'Ukraine',
 'United Kingdom',
 '¡BUSCAR_A_MANITA!',
 'Bulgaria',
 'Turkey',
 'Armenia',
 'Moldova',
 'Israel',
 'Cyprus',
 'Iceland',
 'Montenegro',
 'Switzerland',
 'The Netherlands',
 'Albania',
 'Denmark',
 'Croatia',
 'Poland',
 'Czech Republic',
 'Portugal',
 'Norway',
 'Malta',
 'Andorra',
 'Estonia',
 'Belgium',
 'Austria',
 'Andorra',
 'Albania',
 'Armenia',
 'Azerbaijan',
 'Bosnia',
 'Belgium',
 'Bulgaria',
 'Belarus',
 'Switzerland',
 'Cyprus',
 'Czech Republic',
 'Germany',
 'Denmark',
 'Estonia',
 'Spain',
 'Finland',
 'France',
 'United Kingdom',
 'Georgia',
 'Greece',
 'Croatia',
 'Hungary',
 'Turkey',
 'Israel',
 'Iceland',
 'Lithuania',
 'Latvia',
 'Moldova',
 'Montenegro',
 'Macedonia',
 'Malta',
 'Netherlands',
 'Norway',
 'Poland',
 'Portugal',
 'Romania',
 'Serbia',
 'Russia',
 'Sweden',
 'Slovenia',
 'San Marino',
 'Turkey',
 'Ukraine',
 '¡BUSCAR_A_MANITA!',
 'Lithuania',
 'Israel',
 'France',
 'Sweden',
 'Croatia',
 'Portugal',
 'Iceland',
 'Greece',
 'Armenia',
 'Russia',
 'Azerbaijan',
 'Bosnia',
 'Moldova',
 'Malta',
 'Estonia',
 'Denmark',
 'Germany',
 'Turkey',
 'Albania',
 'Norway',
 'Ukraine',
 'Romania',
 'United Kingdom',
 'Finland',
 'Spain',
 'Ireland',
 'Montenegro',
 'Belarus',
 'Andorra',
 'Switzerland',
 'Cyprus',
 'Macedonia',
 'Poland',
 'Hungary',
 'Serbia',
 'Slovenia',
 'Netherlands',
 'Slovakia',
 'Bulgaria',
 'Belgium',
 'Latvia',
 'Czech Republic',
 '¡BUSCAR_A_MANITA!',
 'Estonia',
 'Slovakia',
 'Finland',
 'Latvia',
 'Poland',
 'Malta',
 'Macedonia',
 'Lithuania',
 'Switzerland',
 'Sweden',
 'The Netherlands',
 'Slovenia',
 'Bulgaria',
 'Croatia',
 'Azerbaijan',
 'Spain',
 'Norway',
 'Moldova',
 'Cyprus',
 'Bosnia',
 'Belgium',
 'Serbia',
 'Belarus',
 'Ireland',
 'Greece',
 'United Kingdom',
 'Georgia',
 'Turkey',
 'Albania',
 'Iceland',
 'Ukraine',
 'France',
 'Romania',
 'Russia',
 'Armenia',
 'Germany',
 'Portugal',
 'Israel',
 'Denmark',
 'Poland',
 'Norway',
 'Albania',
 'Armenia',
 'Turkey',
 'Malta',
 'San Marino',
 'Croatia',
 'Portugal',
 'The Netherlands',
 'Belgium',
 'Slovakia',
 'Cyprus',
 'Bulgaria',
 'Macedonia',
 'Israel',
 'Belarus',
 'Latvia',
 'Finland',
 'Bosnia',
 'Denmark',
 'Lithuania',
 'Hungary',
 'Ireland',
 'Sweden',
 'Estonia',
 'Greece',
 'Russia',
 'France',
 'Italy',
 'Switzerland',
 'United Kingdom',
 'Moldova',
 'Germany',
 'Romania',
 'Austria',
 'Azerbaijan',
 'Slovenia',
 'Iceland',
 'Spain',
 'Ukraine',
 'Serbia',
 'Georgia',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 '¡BUSCAR_A_MANITA!',
 'Austria',
 'Slovenia',
 'Croatia',
 'Montenegro',
 'Cyprus',
 'Serbia',
 'Latvia',
 'San Marino',
 'Macedonia',
 '¡BUSCAR_A_MANITA!',
 'Israel',
 'Albania',
 'Switzerland',
 'France',
 'Lithuania',
 'Moldova',
 'Finland',
 'Spain',
 'Belgium',
 'Estonia',
 'Belarus',
 'Malta',
 'Russia',
 'Germany',
 'Armenia',
 'The Netherlands',
 'Romania',
 'United Kingdom',
 'Sweden',
 'Hungary',
 'Denmark',
 'Iceland',
 'Azerbaijan',
 'Greece',
 'Ukraine',
 'Italy',
 'Norway',
 'Georgia',
 'Ireland',
 'Latvia',
 'Estonia',
 'Albania',
 'Belgium',
 'Moldova',
 'Portugal',
 'Israel',
 'Georgia',
 'Lithuania',
 'Ireland',
 'Macedonia',
 'Ukraine',
 'Belarus',
 'Azerbaijan',
 'Iceland',
 'Norway',
 'Romania',
 'Armenia',
 'Montenegro',
 'Poland',
 'Greece',
 'Austria',
 'Germany',
 'Sweden',
 'France',
 'Russia',
 'Italy',
 'Slovenia',
 'Finland',
 'Spain',
 'Switzerland',
 'Hungary',
 'Malta',
 'Denmark',
 'The Netherlands',
 'San Marino',
 'United Kingdom',
 '¡BUSCAR_A_MANITA!',
 'The Netherlands',
 'Finland',
 'Macedonia',
 'Belarus',
 'Denmark',
 'Ireland',
 'San Marino',
 'Malta',
 'Portugal',
 'Czech Republic',
 'Iceland',
 'Switzerland',
 'Slovenia',
 'France',
 'Israel',
 'Estonia',
 'United Kingdom',
 'Armenia',
 'Lithuania',
 'Serbia',
 'Norway',
 'Sweden',
 'Cyprus',
 'Australia',
 'Belgium',
 'Austria',
 'Greece',
 'Montenegro',
 'Germany',
 'Poland',
 'Latvia',
 'Romania',
 'Spain',
 'Hungary',
 'Georgia',
 'Azerbaijan',
 'Russia',
 'Albania',
 'Italy',
 'Finland',
 'Greece',
 'Moldova',
 'San Marino',
 'Estonia',
 'Montenegro',
 'Iceland',
 'Bosnia',
 'Switzerland',
 'Belarus',
 'Ireland',
 'Macedonia',
 'Slovenia',
 'Denmark',
 'Norway',
 'Albania',
 'Belgium',
 'Czech Republic',
 'The Netherlands',
 'Azerbaijan',
 'Hungary',
 'France',
 'Israel',
 'Bulgaria',
 'Sweden',
 'Germany',
 'France',
 'Poland',
 'Australia',
 'Cyprus',
 'Serbia',
 'Lithuania',
 'Croatia',
 'Russia',
 'Spain',
 'Latvia',
 'Ukraine',
 'Malta',
 'Georgia',
 'Austria',
 'United Kingdom',
 'Armenia',
 'Georgia',
 'Albania',
 'Montenegro',
 'Finland',
 'Iceland',
 'Czech Republic',
 'Slovenia',
 'Latvia',
 'Serbia',
 'Macedonia',
 'Malta',
 'Ireland',
 'San Marino',
 'Switzerland',
 'Lithuania',
 'Estonia',
 'Israel',
 'Poland',
 'Belarus',
 'Austria',
 'Armenia',
 'The Netherlands',
 'Moldova',
 'Hungary',
 'France',
 'Denmark',
 'Portugal',
 'Azerbaijan',
 'Croatia',
 'Australia',
 'Greece',
 'Spain',
 'Norway',
 'United Kingdom',
 'Cyprus',
 'Romania',
 'Germany',
 'Ukraine',
 'Belgium',
 'Sweden',
 'Bulgaria',
 'France',
 'Ukraine',
 'Spain',
 'Slovenia',
 'Lithuania',
 'Austria',
 'Estonia',
 'Norway',
 'Portugal',
 'Serbia',
 'Germany',
 'Albania',
 'France',
 'Czech Republic',
 'Denmark',
 'Australia',
 'Finland',
 'Bulgaria',
 'Moldova',
 'Sweden',
 'Hungary',
 'Israel',
 'The Netherlands',
 'Ireland',
 'Cyprus',
 'Italy',
 'United Kingdom',
 'Azerbaijan',
 'Iceland',
 'Belgium',
 'Belarus',
 'Macedonia',
 'Croatia',
 'Greece',
 'Armenia',
 'Switzerland',
 'Romania',
 'San Marino',
 'Russia',
 'Georgia',
 'Poland',
 'Malta',
 'Latvia',
 'Montenegro',
 'Montenegro',
 'Finland',
 'Poland',
 'Hungary',
 'Belgium',
 'Georgia',
 'Portugal',
 'Armenia',
 'Ireland',
 'Moldova',
 'Latvia',
 'Romania',
 'Austria',
 'Croatia',
 'Lithuania',
 'Malta',
 'Albania',
 'Czech Republic',
 'Germany',
 'Russia',
 'Denmark',
 'San Marino',
 'North Macedonia',
 'Sweden',
 'Slovenia',
 'Cyprus',
 'The Netherlands',
 'Greece',
 'Israel',
 'Norway',
 'United Kingdom',
 'Iceland',
 'Estonia',
 'Belarus',
 'Azerbaijan',
 'France',
 'Italy',
 'Serbia',
 'Switzerland',
 'Australia',
 'Spain',
 '¡BUSCAR_A_MANITA!',
 'France',
 'Czech Republic',
 'Armenia',
 'Italy',
 'Russia',
 'Denmark',
 'Estonia',
 'Romania',
 'Azerbaijan',
 'Albania',
 'Greece',
 'Portugal',
 'Moldova',
 'Malta',
 'Serbia',
 'Poland',
 'San Marino',
 'North Macedonia',
 'Iceland',
 'Finland',
 'Sweden',
 'Cyprus',
 'Slovenia',
 'Bulgaria',
 'Ireland',
 'Austria',
 'Israel',
 'The Netherlands',
 'Switzerland',
 'Latvia',
 'Georgia',
 'Germany',
 'Belarus',
 'Lithuania',
 'Croatia',
 'United Kingdom',
 'Ukraine',
 'Spain',
 'Belgium',
 'Norway',
 'Australia',
 'Slovenia',
 'Australia',
 'North Macedonia',
 'Ireland',
 'Croatia',
 'Romania',
 'Estonia',
 'Czech Republic',
 'Austria',
 'Poland',
 'Georgia',
 'Latvia',
 'Denmark',
 'Cyprus',
 'Albania',
 'Israel',
 'Belgium',
 'Russia',
 'Malta',
 'Portugal',
 'Serbia',
 'United Kingdom',
 'Greece',
 'Switzerland',
 'Iceland',
 'Spain',
 'Moldova',
 'Germany',
 'Finland',
 'Bulgaria',
 'Lithuania',
 'Ukraine',
 'France',
 'Azerbaijan',
 'Norway',
 'The Netherlands',
 'Italy',
 'Sweden',
 'San Marino',
 'Estonia',
 'Serbia',
 'Poland',
 'United Kingdom',
 'Australia',
 'Sweden',
 'Moldova',
 'Iceland',
 'Greece',
 'Belgium',
 'Azerbaijan',
 'Lithuania',
 'Germany',
 'Ukraine',
 'Netherlands',
 'Spain',
 'Italy',
 'Armenia',
 'Norway',
 'France',
 'Switzerland',
 'Finland',
 'Portugal',
 'Romania',
 'Czech Republic',
 'Cyprus',
 'Israel',
 'North Macedonia',
 'Georgia',
 'San Marino',
 'Ireland',
 'Malta',
 'Montenegro',
 'Albania',
 'Austria',
 'Denmark',
 'Croatia',
 'Latvia',
 'Slovenia',
 'Bulgaria']

In [269]:
df_YT['COUNTRY'] = lista_paises

In [270]:
df_YT

,SONG,VIEWS,LIKES,YEAR,COUNTRY
0,Eurovision 2002 01 Cyprus *One* *Gimme* 16:9 HQ,186.656,962,2002,Cyprus
1,Eurovision 2002 02 UK *Jessica Garlic* *Come B...,91.376,546,2002,¡BUSCAR_A_MANITA!
2,Eurovision 2002 03 Austria *Manuel Ortega* *Sa...,68.501,290,2002,Austria
3,Eurovision 2002 05 Spain *Rosa* *Europe's Livi...,23.995,148,2002,Spain
4,Eurovision 2002 06 Croatia *Vesna Pisarović* *...,86.321,505,2002,Croatia
...,...,...,...,...,...
812,REDDI - The Show - LIVE - Denmark 🇩🇰 - First S...,364.088,8552,2022,Denmark
813,Mia Dimšić - Guilty Pleasure - LIVE - Croatia ...,832.624,14.078,2022,Croatia
814,Citi Zēni - Eat Your Salad - LIVE - Latvia 🇱🇻 ...,1.296.619,29.043,2022,Latvia
815,LPS - Disko - LIVE - Slovenia 🇸🇮 - First Semi-...,612.721,15.579,2022,Slovenia
816,Intelligent Music Project - Intention - LIVE -...,313.306,5805,2022,Bulgaria

In [272]:
df_YT.to_excel(r'/Users/Usuario/Desktop/IronHack/Bootcamp/Proyectos/3 - Proyecto ETL/Youtube_Views_Likes_2002_2022.xlsx.xlsx', index = False)

### Calculamos nuevas variables

In [4]:
df_letras = pd.read_excel('./Letras_2002_2022.xlsx')

In [5]:
df_letras

,Country,Artist,Song,Language,Eurovision_Number,Year,Host_Country,Host_City,Lyrics,Lyrics translation,Lyrics_Long,Lyrics_words,key
0,North Macedonia,Vlatko Ilievski,Rusinka (Русинкa),Macedonian/English (Russian),56,2011,Germany,Düsseldorf,"Кожа бела, нежна како снегот\nНов, неизгазен\n...","\nPure and white, her skin is so inviting\nLik...",789,44,412011
1,France,Patricia Kaas,Et s'il fallait le faire,French,54,2009,Russia,Moscow,S'il fallait le faire\nJ'arrêterais la Terre\n...,& If I had to do it\nI would stop the earth\nI...,1208,122,262009
2,Spain,Rosa,Europe's Living a Celebration,Spanish (title English),47,2002,Estonia,Tallinn,"(Celebration, celebration)\n\n(Celebration, ce...","(Celebration, celebration) (Celebration, celeb...",1355,102,522002
3,Montenegro,Who See,Igranka (Игранка),Montenegrin,58,2013,Sweden,Malmö,"[Intro: Nina Žižić]\nVodim te na igranku, na-n...","(I'm taking you to the dance, to-to-to-to the ...",2058,190,402013
4,North Macedonia,Karolina (2),Mojot svet (Мојот свет),Macedonian/English,52,2007,Finland,Helsinki,"Najna najna, nanana najna\nNajna najna, nanana...",[Intro]\nPlay this record as frequently as pos...,896,49,412007
...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,France,Amir,J'ai cherché,French/English,61,2016,Sweden,Stockholm,"[Couplet 1]\nYou, you\nJ’ai cherché un sens à ...",You-ou-ou-ou-ou\nYou-ou-ou-ou-ou I was looking...,1727,109,262016
813,Serbia,Nevena Božović,Kruna (Круна),Serbian (English),64,2019,Israel,Tel Aviv,[Verse 1]\nPogled mili\nJedini dušu smiri\nO v...,Your dear eyes\nAre the only thing that calms ...,544,57,482019
814,Latvia,Bonaparti.lv,Questa notte,Italian,52,2007,Finland,Helsinki,Il sorriso dolce da bambina che mi canta\nE mi...,Your smile of a little girl is what enchants m...,851,68,352007
815,Belgium,Urban Trad,Sanomi,Imaginary,48,2003,Latvia,Riga,Sanomi Helé\nManilla Keranu\nAliya Irema Nia L...,NaN,723,22,172003
816,Belgium,Ishtar,O Julissi,Imaginary,53,2008,Serbia,Belgrade,O julissi na jalyni\nO julissi na dytini\nO bu...,NaN,878,48,172008

In [10]:
df_letras.groupby('Year').agg({'Lyrics_Long':'mean', 'Lyrics_words':'mean'})

      Lyrics_Long  Lyrics_words
Year
2002  1165.791667     84.250000
2003  1117.115385     77.307692
2004  1151.027778     80.305556
2005  1199.641026     82.512821
2006  1294.891892     84.270270
2007  1188.452381     87.214286
2008  1058.558140     80.209302
2009  1126.261905     81.690476
2010  1117.230769     79.179487
2011  1222.697674     88.767442
2012  1116.261905     80.476190
2013  1075.512821     84.000000
2014  1306.864865     91.567568
2015  1172.125000     87.625000
2016  1254.738095     86.690476
2017  1259.333333     87.142857
2018  1328.255814     92.000000
2019  1318.365854     88.585366
2020  1113.268293     78.878049
2021  1201.641026     93.179487
2022  1216.550000     91.250000

In [13]:
df_letras.groupby('Year').agg({'Country':'count'})

      Country
Year
2002       24
2003       26
2004       36
2005       39
2006       37
2007       42
2008       43
2009       42
2010       39
2011       43
2012       42
2013       39
2014       37
2015       40
2016       42
2017       42
2018       43
2019       41
2020       41
2021       39
2022       40

In [37]:
iterable = df_letras[['Year', 'Country']].sort_values('Year')

In [38]:
iterable

     Year    Country
44   2002     Sweden
52   2002  Lithuania
43   2002    Estonia
51   2002     Latvia
50   2002    Romania
..    ...        ...
602  2022    Ireland
604  2022     Latvia
792  2022   Slovenia
588  2022    Armenia
603  2022     Israel

[817 rows x 2 columns]

In [142]:
list(iterable[iterable['Year']==2002]['Country'])

['Sweden',
 'Lithuania',
 'Estonia',
 'Latvia',
 'Romania',
 'Malta',
 'Germany',
 'Israel',
 'Belgium',
 'Switzerland',
 'Denmark',
 'Finland',
 'Cyprus',
 'United Kingdom',
 'North Macedonia',
 'France',
 'Austria',
 'Slovenia',
 'Turkey',
 'Bosnia and Herzegovina',
 'Greece',
 'Croatia',
 'Spain',
 'Russia']

In [158]:
countries_year = {}
for i in range(2002, 2023):
    countries_year[i] = list(iterable[iterable['Year']==i]['Country'])

In [165]:
countries_year[2022] == list(iterable[iterable['Year']==2022]['Country'])

True

In [169]:
df_vecinos=pd.read_clipboard(header=None, names=['num','pais','km','mi','fronteras','fronteras2','vecinos'])
df_vecinos

,,,,num,pais,km,mi,fronteras,fronteras2,vecinos
5,Andorra,120,75,2,2.0,France:,56.6,km,(35.2,mi)
Spain:,63.7,km,(39.6,mi),NaN,None,NaN,None,None,None

In [359]:
fronteras = pd.read_excel('./Fronteras.xlsx')
fronteras.head()

,Km,Pais2,Fronteras,Fronteras2,Vecinos
0,382.000,Abkhazia,2,2,Russia: 241 km (150 mi)
1,NaN,Abkhazia,NaN,NaN,Georgia: 141 km (88 mi)
2,5.529,Afghanistan,6,6,People's Republic of China: 76 km (47 mi)
3,NaN,Afghanistan,NaN,NaN,Iran: 935 km (581 mi)
4,NaN,Afghanistan,NaN,NaN,"Pakistan: 2,430 km (1,510 mi)"

In [360]:
lista_corregida = []
for pais in fronteras['Vecinos']:
    lista_corregida.append((str(pais).strip().split(':')[0]).split()[0])
fronteras['Vecinos'] = lista_corregida

In [361]:
lista_corregida = []
for pais in fronteras['Pais2']:
    lista_corregida.append(pais.strip().split('[')[0])
fronteras['Pais2']=lista_corregida

In [362]:
vecinos = fronteras.groupby('Pais2').apply(lambda x: list(x.Vecinos))
df_vecinos = pd.DataFrame(vecinos, columns=['vecinos']).reset_index()
df_vecinos.head()

         Pais2                                            vecinos
0     Abkhazia                                  [Russia, Georgia]
1  Afghanistan  [People's, Iran, Pakistan, Tajikistan, Turkmen...
2      Albania                [Greece, Kosovo, North, Montenegro]
3      Algeria  [Libya, Mali, Mauritania, Morocco, Niger, Tuni...
4      Andorra                                    [France, Spain]

In [364]:
# df_vecinos.to_excel('./Vecinos_bien.xlsx')

In [365]:
esc_country = []
for pais in df_vecinos['Pais2']:
    if pais in list(df_letras['Country'].unique()):
        esc_country.append(True)
    else:
        esc_country.append(False)

df_vecinos['ESC'] = esc_country

In [367]:
df_vecinos = df_vecinos[df_vecinos['ESC']==True]

In [264]:
countries_year

{2002: ['Sweden',
  'Lithuania',
  'Estonia',
  'Latvia',
  'Romania',
  'Malta',
  'Germany',
  'Israel',
  'Belgium',
  'Switzerland',
  'Denmark',
  'Finland',
  'Cyprus',
  'United Kingdom',
  'North Macedonia',
  'France',
  'Austria',
  'Slovenia',
  'Turkey',
  'Bosnia and Herzegovina',
  'Greece',
  'Croatia',
  'Spain',
  'Russia'],
 2003: ['Iceland',
  'Ireland',
  'Belgium',
  'Malta',
  'Bosnia and Herzegovina',
  'Austria',
  'Portugal',
  'France',
  'Slovenia',
  'Sweden',
  'Romania',
  'Estonia',
  'Latvia',
  'Norway',
  'Greece',
  'Ukraine',
  'United Kingdom',
  'The Netherlands',
  'Cyprus',
  'Turkey',
  'Germany',
  'Israel',
  'Poland',
  'Croatia',
  'Russia',
  'Spain'],
 2004: ['Albania',
  'Cyprus',
  'North Macedonia',
  'Slovenia',
  'Croatia',
  'Denmark',
  'Bosnia and Herzegovina',
  'The Netherlands',
  'Norway',
  'Germany',
  'Ukraine',
  'Belgium',
  'Russia',
  'Iceland',
  'Ireland',
  'Poland',
  'United Kingdom',
  'Turkey',
  'Romania',
  'Sweden',
  'France',
  'Greece',
  'Lithuania',
  'Switzerland',
  'Belarus',
  'Israel',
  'Finland',
  'Portugal',
  'Latvia',
  'Andorra',
  'Monaco',
  'Serbia and Montenegro',
  'Austria',
  'Estonia',
  'Malta',
  'Spain'],
 2005: ['Germany',
  'Malta',
  'Cyprus',
  'Albania',
  'United Kingdom',
  'Denmark',
  'Ireland',
  'Sweden',
  'Greece',
  'Portugal',
  'France',
  'Turkey',
  'Serbia and Montenegro',
  'Hungary',
  'Poland',
  'Bosnia and Herzegovina',
  'Russia',
  'Switzerland',
  'Croatia',
  'North Macedonia',
  'Bulgaria',
  'Romania',
  'Monaco',
  'Andorra',
  'Finland',
  'Belgium',
  'Slovenia',
  'Austria',
  'Lithuania',
  'Spain',
  'Latvia',
  'Belarus',
  'The Netherlands',
  'Iceland',
  'Estonia',
  'Norway',
  'Ukraine',
  'Moldova',
  'Israel'],
 2006: ['Portugal',
  'Denmark',
  'Romania',
  'United Kingdom',
  'Greece',
  'Andorra',
  'Monaco',
  'Norway',
  'Israel',
  'France',
  'Albania',
  'Turkey',
  'Croatia',
  'Spain',
  'Germany',
  'Moldova',
  'Latvia',
  'Armenia',
  'Bulgaria',
  'Slovenia',
  'Belarus',
  'Belgium',
  'Ireland',
  'Cyprus',
  'North Macedonia',
  'Malta',
  'Russia',
  'Poland',
  'Sweden',
  'Switzerland',
  'Iceland',
  'Estonia',
  'Ukraine',
  'Lithuania',
  'Bosnia and Herzegovina',
  'The Netherlands',
  'Finland'],
 2007: ['Ukraine',
  'France',
  'Croatia',
  'Slovenia',
  'Andorra',
  'Cyprus',
  'Serbia',
  'Czech Republic',
  'Bulgaria',
  'Sweden',
  'Russia',
  'Moldova',
  'The Netherlands',
  'Albania',
  'Denmark',
  'Poland',
  'Norway',
  'Malta',
  'Hungary',
  'United Kingdom',
  'Estonia',
  'Turkey',
  'Austria',
  'Ireland',
  'Finland',
  'Lithuania',
  'Greece',
  'Germany',
  'Armenia',
  'Belgium',
  'Georgia',
  'Switzerland',
  'Portugal',
  'Latvia',
  'North Macedonia',
  'Montenegro',
  'Spain',
  'Bosnia and Herzegovina',
  'Romania',
  'Iceland',
  'Belarus',
  'Israel'],
 2008: ['Portugal',
  'Turkey',
  'Armenia',
  'Cyprus',
  'Finland',
  'Serbia',
  'Romania',
  'Estonia',
  'San Marino',
  'Montenegro',
  'Slovenia',
  'Croatia',
  'Spain',
  'Switzerland',
  'Bosnia and Herzegovina',
  'Albania',
  'Israel',
  'Moldova',
  'Belgium',
  'France',
  'Germany',
  'United Kingdom',
  'North Macedonia',
  'Malta',
  'Hungary',
  'Georgia',
  'Denmark',
  'Bulgaria',
  'Latvia',
  'Belarus',
  'Czech Republic',
  'Ukraine',
  'Sweden',
  'Iceland',
  'Lithuania',
  'Greece',
  'Azerbaijan',
  'Norway',
  'Ireland',
  'Andorra',
  'The Netherlands',
  'Poland',
  'Russia'],
 2009: ['Switzerland',
  'Russia',
  'Armenia',
  'Sweden',
  'Albania',
  'Belgium',
  'Czech Republic',
  'Montenegro',
  'France',
  'Slovakia',
  'Spain',
  'Serbia',
  'Croatia',
  'North Macedonia',
  'Moldova',
  'Portugal',
  'Latvia',
  'Bosnia and Herzegovina',
  'Turkey',
  'Andorra',
  'Israel',
  'Ukraine',
  'Belarus',
  'Lithuania',
  'Bulgaria',
  'Greece',
  'Azerbaijan',
  'Estonia',
  'Hungary',
  'Slovenia',
  'Denmark',
  'United Kingdom',
  'Norway',
  'Cyprus',
  'Ireland',
  'Malta',
  'Finland',
  'Germany',
  'Romania',
  'The Netherlands',
  'Iceland',
  'Poland'],
 2010: ['Israel',
  'Belarus',
  'Slovakia',
  'Switzerland',
  'The Netherlands',
  'Albania',
  'Malta',
  'Belgium',
  'Moldova',
  'Serbia',
  'Latvia',
  'North Macedonia',
  'Estonia',
  'Russia',
  'Iceland',
  'Croatia',
  'France',
  'Bosnia and Herzegovina',
  'Lithuania',
  'Ukraine',
  'Finland',
  'Spain',
  'Poland',
  'Greece',
  'Bulgaria',
  'Slovenia',
  'Portugal',
  'Germany',
  'United Kingdom',
  'Armenia',
  'Turkey',
  'Norway',
  'Cyprus',
  'Ireland',
  'Romania',
  'Azerbaijan',
  'Sweden',
  'Denmark',
  'Georgia'],
 2011: ['Poland',
  'France',
  'Serbia',
  'Portugal',
  'Bulgaria',
  'Spain',
  'Cyprus',
  'Italy',
  'North Macedonia',
  'Azerbaijan',
  'Hungary',
  'Iceland',
  'Croatia',
  'San Marino',
  'Finland',
  'Georgia',
  'Lithuania',
  'Switzerland',
  'Turkey',
  'Armenia',
  'Albania',
  'Norway',
  'Israel',
  'Germany',
  'Russia',
  'Greece',
  'Malta',
  'Bosnia and Herzegovina',
  'United Kingdom',
  'Ireland',
  'Denmark',
  'Belarus',
  'Estonia',
  'Romania',
  'Slovenia',
  'Sweden',
  'Latvia',
  'Ukraine',
  'Slovakia',
  'Belgium',
  'The Netherlands',
  'Austria',
  'Moldova'],
 2012: ['Latvia',
  'San Marino',
  'Israel',
  'Croatia',
  'Greece',
  'North Macedonia',
  'France',
  'Slovenia',
  'Spain',
  'Belgium',
  'Finland',
  'Austria',
  'Serbia',
  'Switzerland',
  'Iceland',
  'Bulgaria',
  'Cyprus',
  'Romania',
  'Denmark',
  'Estonia',
  'Moldova',
  'Albania',
  'Bosnia and Herzegovina',
  'Hungary',
  'Germany',
  'Azerbaijan',
  'Italy',
  'United Kingdom',
  'Portugal',
  'Lithuania',
  'Norway',
  'Russia',
  'Slovakia',
  'Turkey',
  'Montenegro',
  'Georgia',
  'The Netherlands',
  'Sweden',
  'Malta',
  'Ireland',
  'Belarus',
  'Ukraine'],
 2013: ['Moldova',
  'Ireland',
  'Belgium',
  'Croatia',
  'Latvia',
  'Azerbaijan',
  'Finland',
  'Malta',
  'Albania',
  'Armenia',
  'Norway',
  'Georgia',
  'Switzerland',
  'Romania',
  'Germany',
  'Bulgaria',
  'United Kingdom',
  'Sweden',
  'Cyprus',
  'Belarus',
  'The Netherlands',
  'Israel',
  'Serbia',
  'Spain',
  'Iceland',
  'France',
  'North Macedonia',
  'San Marino',
  'Lithuania',
  'Montenegro',
  'Estonia',
  'Italy',
  'Austria',
  'Slovenia',
  'Denmark',
  'Russia',
  'Ukraine',
  'Hungary',
  'Greece'],
 2014: ['Montenegro',
  'Portugal',
  'Italy',
  'Armenia',
  'Latvia',
  'Albania',
  'Estonia',
  'Denmark',
  'Spain',
  'Germany',
  'Romania',
  'Slovenia',
  'Greece',
  'Switzerland',
  'North Macedonia',
  'Belarus',
  'Ireland',
  'Finland',
  'Lithuania',
  'Austria',
  'Georgia',
  'Norway',
  'Israel',
  'Malta',
  'Hungary',
  'The Netherlands',
  'San Marino',
  'Moldova',
  'Belgium',
  'Ukraine',
  'Azerbaijan',
  'Russia',
  'United Kingdom',
  'France',
  'Iceland',
  'Poland',
  'Sweden'],
 2015: ['San Marino',
  'Iceland',
  'Sweden',
  'Switzerland',
  'Italy',
  'Cyprus',
  'Finland',
  'Slovenia',
  'United Kingdom',
  'Portugal',
  'Australia',
  'Austria',
  'Germany',
  'Spain',
  'Montenegro',
  'France',
  'Poland',
  'Azerbaijan',
  'Romania',
  'Israel',
  'Ireland',
  'Lithuania',
  'Georgia',
  'Albania',
  'Denmark',
  'Russia',
  'Belarus',
  'Latvia',
  'Malta',
  'North Macedonia',
  'Hungary',
  'Greece',
  'The Netherlands',
  'Belgium',
  'Armenia',
  'Moldova',
  'Norway',
  'Czech Republic',
  'Estonia',
  'Serbia'],
 2016: ['Italy',
  'France',
  'North Macedonia',
  'Austria',
  'Greece',
  'Bosnia and Herzegovina',
  'Azerbaijan',
  'Spain',
  'Malta',
  'Latvia',
  'Germany',
  'Sweden',
  'Belgium',
  'Poland',
  'Albania',
  'Switzerland',
  'Iceland',
  'Israel',
  'Serbia',
  'Ireland',
  'Lithuania',
  'Australia',
  'Georgia',
  'Slovenia',
  'Bulgaria',
  'Denmark',
  'Belarus',
  'Ukraine',
  'Norway',
  'United Kingdom',
  'Finland',
  'Moldova',
  'Hungary',
  'Croatia',
  'The Netherlands',
  'Montenegro',
  'San Marino',
  'Armenia',
  'Czech Republic',
  'Cyprus',
  'Estonia',
  'Russia'],
 2017: ['Slovenia',
  'Latvia',
  'Serbia',
  'Armenia',
  'Cyprus',
  'Czech Republic',
  'Austria',
  'Iceland',
  'Croatia',
  'Israel',
  'Moldova',
  'Malta',
  'Romania',
  'The Netherlands',
  'France',
  'Denmark',
  'Ireland',
  'San Marino',
  'Portugal',
  'Estonia',
  'Lithuania',
  'Norway',
  'Belarus',
  'Switzerland',
  'North Macedonia',
  'Poland',
  'Australia',
  'Azerbaijan',
  'Hungary',
  'Ukraine',
  'Greece',
  'Italy',
  'Germany',
  'United Kingdom',
  'Spain',
  'Bulgaria',
  'Albania',
  'Finland',
  'Belgium',
  'Georgia',
  'Montenegro',
  'Sweden'],
 2018: ['Ukraine',
  'Iceland',
  'Sweden',
  'Latvia',
  'Malta',
  'Russia',
  'Poland',
  'Azerbaijan',
  'Australia',
  'United Kingdom',
  'France',
  'The Netherlands',
  'Moldova',
  'Germany',
  'Austria',
  'Belgium',
  'Croatia',
  'North Macedonia',
  'Bulgaria',
  'Belarus',
  'Israel',
  'Finland',
  'Portugal',
  'Denmark',
  'Italy',
  'Switzerland',
  'Ireland',
  'Greece',
  'Czech Republic',
  'Norway',
  'Romania',
  'Lithuania',
  'Cyprus',
  'San Marino',
  'Hungary',
  'Montenegro',
  'Slovenia',
  'Armenia',
  'Georgia',
  'Spain',
  'Serbia',
  'Albania',
  'Estonia'],
 2019: ['Serbia',
  'North Macedonia',
  'Moldova',
  'Hungary',
  'Germany',
  'Israel',
  'Albania',
  'Georgia',
  'United Kingdom',
  'Poland',
  'The Netherlands',
  'Iceland',
  'Spain',
  'Italy',
  'Slovenia',
  'Norway',
  'Ireland',
  'Lithuania',
  'Armenia',
  'Switzerland',
  'San Marino',
  'Greece',
  'Estonia',
  'Croatia',
  'Australia',
  'Belgium',
  'Belarus',
  'Czech Republic',
  'Finland',
  'Russia',
  'Azerbaijan',
  'Romania',
  'Malta',
  'Austria',
  'France',
  'Cyprus',
  'Sweden',
  'Latvia',
  'Montenegro',
  'Portugal',
  'Denmark'],
 2020: ['Switzerland',
  'Croatia',
  'Italy',
  'Israel',
  'Iceland',
  'Ukraine',
  'Slovenia',
  'Serbia',
  'Czech Republic',
  'San Marino',
  'Bulgaria',
  'United Kingdom',
  'The Netherlands',
  'Sweden',
  'Russia',
  'Romania',
  'Poland',
  'Norway',
  'Belgium',
  'North Macedonia',
  'Austria',
  'Australia',
  'Armenia',
  'Moldova',
  'Albania',
  'Azerbaijan',
  'Lithuania',
  'Denmark',
  'Estonia',
  'Finland',
  'Malta',
  'Portugal',
  'Spain',
  'Cyprus',
  'France',
  'Germany',
  'Belarus',
  'Greece',
  'Ireland',
  'Latvia',
  'Georgia'],
 2021: ['Georgia',
  'Germany',
  'Greece',
  'Iceland',
  'Latvia',
  'Israel',
  'Lithuania',
  'Finland',
  'Moldova',
  'Ireland',
  'Serbia',
  'Switzerland',
  'Italy',
  'Czech Republic',
  'Cyprus',
  'Denmark',
  'Croatia',
  'Bulgaria',
  'Belgium',
  'Azerbaijan',
  'Austria',
  'Australia',
  'North Macedonia',
  'Estonia',
  'Norway',
  'Romania',
  'Portugal',
  'France',
  'Albania',
  'Russia',
  'Ukraine',
  'Poland',
  'Spain',
  'Malta',
  'United Kingdom',
  'The Netherlands',
  'Sweden',
  'Slovenia',
  'San Marino'],
 2022: ['Norway',
  'Poland',
  'Sweden',
  'Switzerland',
  'United Kingdom',
  'San Marino',
  'Albania',
  'Ukraine',
  'Cyprus',
  'Italy',
  'Portugal',
  'Romania',
  'Lithuania',
  'Spain',
  'France',
  'North Macedonia',
  'Montenegro',
  'Serbia',
  'Malta',
  'Moldova',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Belgium',
  'Bulgaria',
  'Croatia',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'The Netherlands',
  'Georgia',
  'Germany',
  'Greece',
  'Iceland',
  'Ireland',
  'Latvia',
  'Slovenia',
  'Armenia',
  'Israel']}

In [382]:
df_letras.head(2)

,Country,Artist,Song,Language,Eurovision_Number,Year,Host_Country,Host_City,Lyrics,Lyrics translation,Lyrics_Long,Lyrics_words,key
0,North Macedonia,Vlatko Ilievski,Rusinka (Русинкa),Macedonian/English (Russian),56,2011,Germany,Düsseldorf,"Кожа бела, нежна како снегот\nНов, неизгазен\n...","\nPure and white, her skin is so inviting\nLik...",789,44,412011
1,France,Patricia Kaas,Et s'il fallait le faire,French,54,2009,Russia,Moscow,S'il fallait le faire\nJ'arrêterais la Terre\n...,& If I had to do it\nI would stop the earth\nI...,1208,122,262009

In [462]:
df_vecinos = pd.read_excel('./Vecinos_bien.xlsx')
df_vecinos.head()

   Columna1      Pais2                                            vecinos
0         2    Albania  ['Greece', 'Kosovo', 'North Macedonia', 'Monte...
1         4    Andorra                                ['France', 'Spain']
2         8    Armenia        ['Azerbaijan', 'Georgia', 'Iran', 'Turkey']
3         9  Australia                                              NADIE
4        10    Austria  ['Czech', 'Germany', 'Hungary', 'Italy', 'Liec...

In [402]:
df_vecinos.vecinos[36].replace("'",'').strip('][').split(', ')

['Azerbaijan',
 'Belarus',
 '"China"',
 'Estonia',
 'Finland',
 'Georgia',
 'Kazakhstan',
 'North Macedonia',
 'Latvia',
 'Lithuania',
 'Mongolia',
 'Norway',
 'Poland',
 'Ukraine']

In [403]:
df_vecinos['vecinos'].unique()

array(["['Greece', 'Kosovo', 'North Macedonia', 'Montenegro']",
       "['France', 'Spain']",
       "['Azerbaijan', 'Georgia', 'Iran', 'Turkey']", 'NADIE',
       "['Czech', 'Germany', 'Hungary', 'Italy', 'Liechtenstein', 'Slovakia', 'Slovenia', 'Switzerland']",
       "['Armenia', 'Georgia', 'Iran', 'Russia', 'Turkey']",
       "['Latvia', 'Lithuania', 'Poland', 'Russia', 'Ukraine']",
       "['France', 'Germany', 'Luxembourg', 'The Netherlands']",
       "['Croatia', 'Montenegro', 'Serbia']",
       "['Greece', 'North Macedonia', 'Romania', 'Serbia', 'Turkey']",
       "['Bosnia and Herzegovina', 'Hungary', 'Montenegro', 'Serbia', 'Slovenia']",
       "['Austria', 'Germany', 'Poland', 'Slovakia']", "['Germany']",
       "['Latvia', 'Russia']", "['Norway', 'Sweden', 'Russia']",
       "['Andorra', 'Belgium', 'Brazil', 'Germany', 'Italy', 'Luxembourg', 'Monaco', 'Sint', 'Spain', 'Suriname', 'Switzerland']",
       "['Armenia', 'Azerbaijan', 'Russia', 'Turkey', 'Abkhazia', 'South']",
       "['Austria', 'Belgium', 'Czech', 'Denmark', 'France', 'Luxembourg', 'Netherlands', 'Poland', 'Switzerland']",
       "['Albania', 'Bulgaria', 'Turkey', 'North Macedonia']",
       "['Austria', 'Croatia', 'Romania', 'Serbia', 'Slovakia', 'Slovenia', 'Ukraine']",
       "['United Kingdom']",
       "['Egypt', 'Gaza', 'Jordan', 'Lebanon', 'Syria', 'West']",
       "['Austria', 'France', 'San Marino', 'Slovenia', 'Switzerland', 'Vatican']",
       "['Belarus', 'Estonia', 'Lithuania', 'Russia']",
       "['Belarus', 'Latvia', 'Poland', 'Russia']",
       "['Romania', 'Ukraine']", "['France']",
       "['Albania', 'Bosnia and Herzegovina', 'Croatia', 'Kosovo', 'Serbia']",
       "['Albania', 'Bulgaria', 'Greece', 'Kosovo', 'Serbia']",
       "['Finland', 'Sweden', 'Russia']",
       "['Belarus', 'Czech', 'Germany', 'Lithuania', 'Russia', 'Slovakia', 'Ukraine']",
       "['Spain']",
       "['Bulgaria', 'Hungary', 'Moldova', 'Serbia', 'Ukraine']",
       '[\'Azerbaijan\', \'Belarus\', "China", \'Estonia\', \'Finland\', \'Georgia\', \'Kazakhstan\', \'North Macedonia\', \'Latvia\', \'Lithuania\', \'Mongolia\', \'Norway\', \'Poland\', \'Ukraine\']',
       "['Italy']",
       "['Bosnia and Herzegovina', 'Bulgaria', 'Croatia', 'Hungary', 'Kosovo', 'Montenegro', 'North Macedonia', 'Romania']",
       "['Austria', 'Czech Republic', 'Hungary', 'Poland', 'Ukraine']",
       "['Austria', 'Croatia', 'Italy', 'Hungary']",
       "['Andorra', 'France', 'Gibraltar', 'Portugal', 'Morocco']",
       "['Finland', 'Norway']",
       "['Austria', 'France', 'Italy', 'Liechtenstein', 'Germany']",
       "['Belgium', 'Germany', 'Saint']",
       "['Armenia', 'Azerbaijan', 'Bulgaria', 'Georgia', 'Greece', 'Iran', 'Iraq', 'Syria']",
       "['Belarus', 'Hungary', 'Moldova', 'Poland', 'Romania', 'Russia', 'Slovakia']",
       "['Ireland', 'Cyprus', 'Ireland', 'Spain']"], dtype=object)

In [463]:
lista_corregida = []
for lista in df_vecinos['vecinos']:
    if lista == 'NADIE':
        lista_corregida.append('SIN_VECINOS')
    else:
        lista_corregida.append(lista.replace("'",'').strip('][').split(', '))
df_vecinos['vecinos'] = lista_corregida

In [412]:
df_letras.head(2)

,Country,Artist,Song,Language,Eurovision_Number,Year,Host_Country,Host_City,Lyrics,Lyrics translation,Lyrics_Long,Lyrics_words,key
0,North Macedonia,Vlatko Ilievski,Rusinka (Русинкa),Macedonian/English (Russian),56,2011,Germany,Düsseldorf,"Кожа бела, нежна како снегот\nНов, неизгазен\n...","\nPure and white, her skin is so inviting\nLik...",789,44,412011
1,France,Patricia Kaas,Et s'il fallait le faire,French,54,2009,Russia,Moscow,S'il fallait le faire\nJ'arrêterais la Terre\n...,& If I had to do it\nI would stop the earth\nI...,1208,122,262009

In [414]:
df_vecinos.head(2)

   Columna1    Pais2                                        vecinos
0         2  Albania  [Greece, Kosovo, North Macedonia, Montenegro]
1         4  Andorra                                [France, Spain]

In [454]:
len(df_letras)

817

In [467]:
num_vecinos = []

for i,e in enumerate(df_letras['Country']):
    
    setPart = set(countries_year[df_letras['Year'][i]]) # Llamo al dicionario de participantes del año de la canción que entra
    setVecis = set(list(df_vecinos[df_vecinos['Pais2']==e]['vecinos'])[0]) # Llamo a la lista de vecinos
    
    num_vecinos.append(len(setVecis.intersection(setPart)))

df_letras['Vecinos_Participantes'] = num_vecinos

In [469]:
df_letras.to_excel('./Letras_2002_2022_new.xlsx')

### Sacando más datos

In [15]:
df_influence = pd.read_clipboard(header=None, names=['Ranking', 'Country', 'Region', 'Score'])
df_influence

    Ranking               Country               Region  Score
0         1         United States        North America  98.53
1         2                 China       Asia & Pacific  98.39
2         3                Russia               Europe  98.28
3         4               Germany               Europe  95.71
4         5                France               Europe  95.26
5         6        United Kingdom               Europe  94.87
6         7                 Japan       Asia & Pacific  89.67
7         8                 India       Asia & Pacific  89.11
8         9                 Italy               Europe  86.60
9        10                Israel               Europe  86.38
10       11                Canada        North America  86.02
11       12          Saudi Arabia          Middle east  85.08
12       13                 Spain               Europe  78.72
13       14           South Korea       Asia & Pacific  78.49
14       15  United Arab Emirates          Middle east  77.95
15       16           Switzerland               Europe  77.94
16       17             Australia       Asia & Pacific  77.75
17       18           Netherlands               Europe  73.16
18       19                Brazil  South/Latin America  73.08
19       20                Sweden               Europe  73.05
20       21                 Egypt          Middle east  72.95
21       22               Austria               Europe  72.74
22       23                Norway               Europe  72.57
23       24                Greece               Europe  72.33
24       25                Mexico  South/Latin America  72.03
25       26               Denmark               Europe  72.03
26       27                Turkey               Europe  71.78
27       28              Portugal               Europe  68.04
28       29        Czech Republic               Europe  67.16
29       30               Finland               Europe  66.39
30       31             Singapore       Asia & Pacific  66.06
31       32           New Zealand       Asia & Pacific  65.27
32       33          South Africa               Africa  64.14
33       34              Thailand       Asia & Pacific  63.20
34       35             Argentina  South/Latin America  61.30
35       36                Poland               Europe  60.97
36       37             Indonesia       Asia & Pacific  60.66
37       38              Malaysia       Asia & Pacific  60.25
38       39                  Iran          Middle east  59.85
39       40               Vietnam       Asia & Pacific  59.65
40       41                Jordan          Middle east  58.80
41       42               Ukraine               Europe  58.59
42       43               Croatia               Europe  58.37
43       44           Philippines       Asia & Pacific  58.10
44       45               Belgium               Europe  57.96
45       46               Hungary               Europe  57.30
46       47               Ireland               Europe  57.12
47       48                Kuwait          Middle east  56.55
48       49              Slovenia               Europe  56.49
49       50                  Oman          Middle east  55.97
50       51              Bulgaria               Europe  55.55
51       52                 Qatar          Middle east  55.05
52       53               Belarus               Europe  55.04
53       54                Cyprus               Europe  55.00
54       55               Romania               Europe  54.87
55       56              Pakistan       Asia & Pacific  54.60
56       57              Slovakia               Europe  54.53

In [10]:
df_letras = pd.read_excel('./Letras_2002_2022_(19.09.2022).xlsx')

In [22]:
esc_countries = list(df_letras['Country'].unique())

In [32]:
estan = [e for e in esc_countries if e in list(df_influence['Country'])]
drop_rows = [p for p in df_influence['Country'] if p not in estan]

In [50]:
df_UEinfluence = df_influence[~df_influence['Country'].isin(drop_rows)].reset_index().drop('index', axis=1)
df_UEinfluence['Ranking'] = [i+1 for i in range(len(df_UEinfluence))]
df_UEinfluence

    Ranking         Country          Region  Score
0         1          Russia          Europe  98.28
1         2         Germany          Europe  95.71
2         3          France          Europe  95.26
3         4  United Kingdom          Europe  94.87
4         5           Italy          Europe  86.60
5         6          Israel          Europe  86.38
6         7           Spain          Europe  78.72
7         8     Switzerland          Europe  77.94
8         9       Australia  Asia & Pacific  77.75
9        10          Sweden          Europe  73.05
10       11         Austria          Europe  72.74
11       12          Norway          Europe  72.57
12       13          Greece          Europe  72.33
13       14         Denmark          Europe  72.03
14       15          Turkey          Europe  71.78
15       16        Portugal          Europe  68.04
16       17  Czech Republic          Europe  67.16
17       18         Finland          Europe  66.39
18       19          Poland          Europe  60.97
19       20         Ukraine          Europe  58.59
20       21         Croatia          Europe  58.37
21       22         Belgium          Europe  57.96
22       23         Hungary          Europe  57.30
23       24         Ireland          Europe  57.12
24       25        Slovenia          Europe  56.49
25       26        Bulgaria          Europe  55.55
26       27         Belarus          Europe  55.04
27       28          Cyprus          Europe  55.00
28       29         Romania          Europe  54.87
29       30        Slovakia          Europe  54.53

In [51]:
df_UEinfluence.to_excel('./Ranking_Influencia_UE.xlsx')

In [65]:
df_reputation = pd.read_clipboard(header=None, names=['Ranking', 'Country', 'Science_Tec', 'Culture', 'Peace_Security', 'WorldOrder', 'Planet_Climate', 'Prosp_Equal', 'Health_Well-being'])
df_reputation

,Ranking,Country,Science_Tec,Culture,Peace_Security,WorldOrder,Planet_Climate,Prosp_Equal,Health_Well-being
0,1,Netherlands,8,2,27,3,19,4,9
1,2,Switzerland,11,4,44,10,2,5,6
2,3,Denmark,4,6,64,9,14,2,3
3,4,Finland,7,13,52,8,6,9,12
4,5,Germany,21,15,37,2,18,14,7
...,...,...,...,...,...,...,...,...,...
158,159,Chad,124,135,127,145,131,126,140
159,160,Yemen,108,155,157,128,125,137,119
160,161,Iraq,162,156,158,115,87,153,135
161,162,Libya,150,163,145,112,154,97,156
162,163,Afghanistan,159,115,152,135,155,140,131

In [60]:
df_reputation.columns

Index(['Ranking', 'Country', 'Science_Tec', 'Culture', 'Peace_Security',
       'WorldOrder', 'Planet_Climate', 'Prosp_Equal', 'Health_Well-being'],
      dtype='object')

In [74]:
df_reputation['Country'] = [e.strip() for e in df_reputation['Country']]

In [83]:
lista_corregida = []
for e in df_reputation['Country']:
    if e == 'Netherlands':
        lista_corregida.append('The Netherlands')
    else:
        lista_corregida.append(e)
        
df_reputation['Country'] = lista_corregida

In [92]:
df_reputation = df_reputation[df_reputation['Country'].isin(esc_countries)].reset_index(drop=True)
df_reputation.head()

,Ranking,Country,Science_Tec,Culture,Peace_Security,WorldOrder,Planet_Climate,Prosp_Equal,Health_Well-being
0,1,The Netherlands,8,2,27,3,19,4,9
1,2,Switzerland,11,4,44,10,2,5,6
2,3,Denmark,4,6,64,9,14,2,3
3,4,Finland,7,13,52,8,6,9,12
4,5,Germany,21,15,37,2,18,14,7

In [93]:
df_reputation.to_excel('./Reputation_UE.xlsx')

### Corrigiendo Cuenta de Palabras

In [127]:
df_letras = pd.read_excel('./Letras_2002_2022_(19.09.2022).xlsx')

In [128]:
df_letras['Lyrics'][404]

"[Verse 1]\nWe can never let the word be unspoken\nWe will never let our loving go, come undone\nEverything we had is staying unbroken, oh\nYou will always be the only one\nYou're the only one\n\n[Pre-Chorus]\nWon't ever give up cause you're still somewhere out there\nNothing or no one's gonna keep us apart\nBreaking it down but I'm still getting nowhere\nWon't stop, hold on\n\n[Chorus]\nThunder and lightning, it's getting exciting\nLights up the skyline to show where you are\nMy love is rising, the story's unwinding\nTogether we'll make it and reach for the stars\n\nYou're the only one, you're my only one\nYou're my life, every breath that I take\nUnforgettable, so unbelievable\nYou're the only one, my only one\n\n[Verse 2]\nI could have told you to slow down and stay down\nI could have told you a secret, won't you keep it now?\nThinking of making a showdown when love is found\nThinking of waiting till you're around\n\n[Pre-Chorus]\nWon't ever give up cause you're still somewhere out there\nNothing or no one's gonna keep us apart\nBreaking it down but I'm still getting nowhere\nWon't stop, hold on\n\n[Chorus]\nThunder and lightning, it's getting exciting\nLights up the skyline to show where you are\nMy love is rising, the story's unwinding\nTogether we'll make it and reach for the stars\n\nYou're the only one, you're my only one\nYou're my life, every breath that I take\nUnforgettable, so unbelievable\nYou're the only one, my only one\n\n[Bridge]\nYou're my only one\n\n[Chorus]\nThunder… (and lightning)\n(It's getting exciting) It's getting excitin\nLights up the skyline to show where you are\nTo show where you are…\n\n( You're the only one) You're my only one\nYou're my life, every breath that I take\nUnforgettable, so unbelievable\nYou're the only one, my only one"

In [132]:
# CÓDIGO PARA lONGITUD LETRA

%%time
lista_corregida = []
for i,string in enumerate(df_letras['Lyrics']):
    lista_corregida.append(len(re.sub(' +', ' ', df_letras['Lyrics'][i].replace('\n'," ").replace('(',"").replace(')',"").replace('.',"").replace(',',"").replace('-',"").replace('[Verse 1]',"").replace('[Verse 2]',"").replace('[Verse 3]',"").replace('[Chorus]',"").replace('[Bridge]',"").replace('PreChorus',"").replace('[',"").replace(']',"").strip())))

df_letras['Lyrics_Long'] = lista_corregida

CPU times: total: 125 ms
Wall time: 222 ms

In [164]:
# CÓDIGO PARA PALABRAS ÚNICAS

%%time
lista_corregida = []
for i,string in enumerate(df_letras['Lyrics']):
    lista_corregida.append(len(set(re.sub(' +', ' ', df_letras['Lyrics'][i].lower().replace('\n'," ").replace('(',"").replace(')',"").replace('.',"").replace(',',"").replace('-',"").replace('[Verse 1]',"").replace('[Verse 2]',"").replace('[Verse 3]',"").replace('[Chorus]',"").replace('[Bridge]',"").replace('PreChorus',"").replace('[',"").replace(']',"").strip()).split(" "))))

df_letras['Lyrics_words'] = lista_corregida

CPU times: total: 188 ms
Wall time: 205 ms

In [207]:
idiomas = df_letras.Language.value_counts()
idiomas[(idiomas==1)].index

Index(['Greek/English (Pontic Greek)', 'Danish', 'Ukrainian/English (6 other)',
       'French (Tahitian)', 'French/English (Franglais)', 'Mühlviertel German',
       'Latvian', 'Finnish (title Karelian dialect)', 'German/Polish/ Russian',
       'Italian (English)', 'French/Spanish', 'Corsican', 'Võro',
       'Hungarian (Romani) (title Latin)', 'Macedonian/Romani',
       'Udmurt (English)', 'Czech', 'English/Portuguese', 'Polish',
       'French (English/Spanish)', 'English/Polish', 'Russian/Ukrainian',
       'Norwegian', 'Serbian (German/Finnish)', 'Romanian/Italian',
       'Spanish (Andalusian)', 'Bulgarian/English',
       'Serbian (Torlakian dialect)', 'Styrian German',
       'English/Amharic/Hebrew/Arabic', 'Greek (title English)',
       'Slovene (Portuguese)', 'Bulgarian (10 other)',
       'Hebrew/English (Gr./Fr./Sp.)', 'German', 'Breton', 'Polish/Russian',
       'Lithuanian', 'Italian (Arabic)', 'Macedonian/English (Russian)',
       'French/English (Sign language)', 'English/Macedonian',
       'English/Hebrew/ Arabic', 'English (title Turkish)', 'English (Romani)',
       'English (Catalan)', 'English (Fr./Germ./It./Sp.)',
       'English/It./Sp./ Russ./Fr./Rom.', 'English (title partly Turkish)',
       'English/French/ Hebrew', 'English (Spanish)', 'English/Imaginary',
       'English/Pol./ Germ./Russ./Sp.', 'English (title French)',
       'English (Swahili)', 'English (Romanian)', 'English/Turkish',
       'English/Ukrainian', 'Russian (English)', 'Armenian', 'Georgian',
       'Portuguese/English (French/Spanish)', 'Swedish',
       'Italian (English/ Sanskrit/Ancient Greek)', 'Macedonian/English',
       'Spanish (title English)', 'English/Russian',
       'English (French/ Sign language)', 'Albanian (title Latin)',
       'English/French (German/Danish)', 'Greek (title French)',
       'German/English/ Ukrainian/Russian', 'Serbian/English',
       'Georgian (Abkhaz)', 'Croatian (Italo-Dalmatian)',
       'French (title partly Spanish)', 'German/English',
       'English/Sranan Tongo', 'English/Czech', 'English/Azerbaijani',
       'English (Sami)', 'English (Turkish)', 'English (Bosnian)',
       'English (Icelandic)', 'English (Hebrew/Japanese)',
       'English (Lithuanian)', 'English/Crimean Tatar', 'English (Bulgarian)',
       'English (Latvian)', 'English/Georgian', 'English (title Romanian)',
       'English (Arabic)', 'English (Italian)',
       'English (German/ Montenegrin)', 'Serbian (English)'],
      dtype='object')

In [208]:
df_letras[df_letras.Language == 'English (Fr./Germ./It./Sp.)']['Lyrics']

176    Oh, I come from a nation\nWhat knows how to wr...
Name: Lyrics, dtype: object

In [209]:
df_letras['Lyrics'][176]

"Oh, I come from a nation\nWhat knows how to write a song\nOh Europe, where oh where did it all go wrong?\nCome on!\n\nIrlande douze points\n\nDrag acts and bad acts and Terry Wogan's wig\nMad acts and sad acts, it was Johnny Logan's gig\n\nShake your feathers and bop your beak\nShake 'em to the west and to the east\nWave euro hands and euro feet\nWiggle in the air to the turkey beat\n\nIrlande douze points\nIrlande douze points\nIrlande douze points\nDo the funky beat\nCome on\n\nD O B double B L E, yeah...\n\nHello Abba, hello Bono, hello Helsinki\nOla Prague, hello sailor, c'est la vie\nAuf Wiedersehen, Mama Mia, and God save the Queen\nBonjour Serbia, good day Austria\nYou know what I mean\n\nShake your feathers and bop your beak\nShake 'em to the west and to the east\nWave euro hands and euro feet\nWiggle in the air to the turkey beat\n\nShake your feathers and bop your beak\nShake 'em to the west and to the east\nWave euro hands and euro feet\nWiggle in the air to the turkey beat\n\nIrlande douze points\nIrlande douze points\nIrlande douze points\n\nIrlande douze points\nIrlande douze points\nIrlande douze points\nDo the funky beat\nCome on\n\nGive us another chance, we're sorry for riverdance\nSure Flately, he's a yank\nAnd the Danube flows through France\nBlock vote, shock vote\nGive your twelve today\nYou're all invited to Dublin, Ireland\nAnd we'll party the Shamrock way\n\nIrlande douze points - Irlande douze points\nIrlande douze points - Irlande douze points\nIrlande douze points - Irlande douze points\nIrlande douze points - do the funky beat\nCome on\n\nIrlande douze points, Irlande douze points\n\nEastern Europe, we love you\nDo you like Irish stew?\nOr goulash as it is to you?\n(Irlande douze points, Irlande douze points)\n\nListen Bulgaria, we love you\nBelarus, Georgia, Montenegro\nMoldovia, Albania, Croatia\nPoland, Russia, Ukraine\nMacedonia, love you Turkey\nHungary, Estonia, Slovakia\nArmenia, Bosnia-Herzegova\nAnd don't forget the Swiss"

In [ ]:
# Cambios para el idioma:
# Reemplazar ( por /
# Donde (title ****) == Split y 2ª Columna
# Donde / == Split y 2ª columna

In [252]:
idioma_bien = []
for i in df_letras.Language:
    idioma_bien.append(i.replace('(','/').replace(')',"").replace('title',"").replace(" ","").replace('Fr.','French').replace('Pol.', 'Polish').replace('Germ.','German').replace('It.','Italian').replace('Sp.','Spanish').replace('Russ.', 'Russian').replace('Rom.','Romanian').replace('Romani','Romanian').replace('Romanianan','Romanian').replace('partly',""))
    
df_letras['idioma_bien'] = idioma_bien

In [253]:
num_idiomas = []
for i in idioma_bien:
    num_idiomas.append(len(i.split('/')))
    
df_letras['num_idiomas'] = num_idiomas

In [254]:
idioma_principal = []
for i in idioma_bien:
    idioma_principal.append(i.split('/')[0])

df_letras['idioma_principal'] = idioma_principal

In [255]:
for i in idioma_bien:
    print((i.split('/')))

['Macedonian', 'English', 'Russian']
['French']
['Spanish', 'English']
['Montenegrin']
['Macedonian', 'English']
['Spanish', 'English']
['Spanish']
['Slovene']
['Albanian']
['Macedonian']
['Romanian']
['Hebrew']
['Hebrew']
['Slovene']
['Hebrew', 'English']
['French']
['French']
['Hebrew', 'English']
['Italian', 'English', 'Sanskrit', 'AncientGreek']
['Albanian']
['Swedish']
['Montenegrin']
['Portuguese', 'English', 'French', 'Spanish']
['Spanish', 'English']
['French']
['Russian']
['Spanish', 'English']
['Georgian']
['Armenian']
['Russian', 'English']
['Spanish', 'English']
['Dutch']
['Italian']
['Serbian']
['Bosnian']
['Bosnian']
['Serbian']
['English']
['English']
['English']
['English', 'Greek']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Spanish']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Ukrainian']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Turkish']
['English']
['English']
['English']
['English']
['English', 'Spanish']
['English']
['English']
['English']
['English']
['English', 'Spanish']
['English']
['English', 'Romanian']
['English', 'Signlanguage']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Greek']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'French']
['English']
['English']
['English', 'Macedonian']
['English', 'Polish', 'German', 'Russian', 'Spanish']
['English']
['English']
['English']
['English', 'Imaginary']
['English', 'French']
['English']
['English']
['English']
['English']
['English', 'Spanish']
['English']
['English']
['English']
['English']
['English', 'Italian']
['English']
['English']
['English', 'French', 'Hebrew']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Albanian']
['English']
['English']
['English', 'Spanish']
['English']
['English']
['English']
['English']
['English', 'Turkish']
['English']
['English']
['English']
['English']
['English', 'Greek']
['English']
['English']
['English']
['English', 'Italian', 'Spanish', 'Russian', 'French', 'Romanian']
['English', 'Armenian']
['English']
['English']
['English']
['English']
['English', 'French', 'German', 'Italian', 'Spanish']
['English', 'Catalan']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Spanish']
['English']
['English']
['English']
['English']
['English', 'Hungarian']
['English', 'Russian']
['English']
['English']
['English']
['English', 'French']
['English']
['English', 'Romanian']
['English']
['English']
['English', 'French']
['English', 'Armenian']
['English']
['English', 'Turkish']
['English', 'Hebrew', 'Arabic']
['English']
['English']
['English']
['English']
['English']
['English', 'Latin']
['English']
['English']
['English']
['English']
['English', 'Slovene']
['English']
['English']
['English']
['English', 'Russian']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'French']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Swahili']
['English', 'Albanian']
['English']
['English']
['English', 'Russian']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Hungarian']
['English', 'French', 'Signlanguage']
['English']
['English', 'Greek']
['English', 'Bosnian']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'German', 'Montenegrin']
['English']
['English']
['English']
['English']
['English']
['English', 'Hebrew']
['English', 'Italian']
['English']
['English', 'Arabic']
['English']
['English', 'Romanian']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Georgian']
['English']
['English']
['English']
['English']
['English']
['English', 'Italian']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Latvian']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Hebrew']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Slovene']
['English']
['English']
['English', 'Spanish']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Signlanguage']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Latin']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Bulgarian']
['English']
['English', 'CrimeanTatar']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Italian']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Lithuanian']
['English', 'Hebrew', 'Japanese']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Spanish']
['English']
['English']
['English']
['English', 'Icelandic']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Turkish']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'French', 'German', 'Danish']
['English']
['English']
['English']
['English']
['English']
['English', 'Sami']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['French', 'English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Spanish']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Azerbaijani']
['English']
['English']
['English', 'Croatian']
['English']
['English', 'Czech']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'Hebrew']
['English']
['English']
['English', 'French']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English', 'SrananTongo']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['English']
['German', 'English']
['French']
['French', 'Spanish']
['French']
['Croatian']
['Russian']
['Polish', 'English']
['Croatian', 'Italo-Dalmatian']
['English', 'Armenian']
['Georgian', 'Abkhaz']
['Albanian']
['Serbian', 'English']
['Spanish']
['Italian', 'English']
['Romanian', 'English']
['German', 'English', 'Ukrainian', 'Russian']
['Greek', 'French']
['English', 'Albanian']
['Albanian']
['Serbian']
['Albanian', 'Latin']
['Montenegrin']
['Belarusian']
['Finnish']
['Finnish']
['French', 'English', 'Signlanguage']
['Polish']
['Bosnian']
['Belarusian']
['Portuguese']
['Italian']
['Croatian']
['Portuguese']
['Croatian', 'English']
['Greek']
['Corsican']
['Italian']
['Slovak']
['Dutch']
['Italian', 'English']
['English', 'Croatian']
['Catalan']
['Bulgarian']
['Catalan', 'English']
['Bosnian']
['Slovene']
['Spanish']
['Catalan']
['Portuguese']
['Italian']
['French', 'English', 'Franglais']
['Montenegrin']
['Estonian']
['Greek']
['Portuguese']
['Portuguese']
['Croatian']
['French']
['Hebrew', 'English']
['Icelandic']
['Udmurt', 'English']
['German', 'Polish', 'Russian']
['English', 'Portuguese']
['Bosnian']
['French']
['Portuguese']
['Portuguese']
['Greek']
['Catalan']
['Albanian']
['Serbian']
['Italian']
['French']
['Spanish']
['Portuguese']
['Portuguese']
['Romanian', 'English']
['Catalan', 'English']
['French']
['Serbian']
['Italian', 'Arabic']
['Italian', 'English']
['English', 'Spanish']
['Lithuanian']
['Portuguese']
['Polish', 'Russian']
['French']
['Breton']
['French']
['Slovene']
['Spanish', 'English']
['Hungarian']
['Slovenian']
['Montenegrin']
['Croatian']
['French']
['Estonian']
['Macedonian']
['Macedonian']
['French', 'English']
['Serbian']
['Spanish', 'English']
['Portuguese']
['Portuguese', 'English']
['English', 'Greek']
['Ukrainian']
['Hungarian']
['Hungarian']
['Slovene', 'Portuguese']
['Serbian']
['Hebrew', 'English']
['Turkish']
['English', 'Amharic', 'Hebrew', 'Arabic']
['Croatian', 'English']
['Ukrainian']
['Ukrainian']
['Serbian', 'Torlakiandialect']
['Hungarian']
['Bulgarian', 'English']
['Slovene']
['Croatian']
['Spanish', 'Andalusian']
['Serbian']
['Bulgarian']
['Bulgarian']
['Norwegian']
['Hebrew', 'English']
['Greek']
['Spanish']
['Russian', 'Ukrainian']
['English', 'Polish']
['Montenegrin']
['Turkish']
['Italian', 'English']
['Croatian']
['Czech']
['Spanish']
['French', 'English', 'Spanish']
['Spanish']
['Portuguese', 'English']
['Spanish']
['Spanish']
['Turkish', 'English']
['Serbian', 'German', 'Finnish']
['Turkish', 'English']
['English']
['Romanian', 'Italian']
['French']
['Portuguese', 'English']
['Slovene']
['French']
['StyrianGerman']
['Croatian', 'English']
['Greek', 'English']
['Italian']
['Estonian']
['Icelandic']
['Croatian']
['Montenegrin']
['Bulgarian', '10other']
['Romanian']
['Macedonian']
['Portuguese']
['Hebrew', 'English', 'Gr.', 'French', 'Spanish']
['Italian']
['Italian']
['Spanish']
['Italian']
['Polish', 'English']
['German']
['Danish']
['Hebrew', 'English']
['Ukrainian', 'English', '6other']
['French']
['Serbian']
['Icelandic']
['French', 'Tahitian']
['MühlviertelGerman']
['Greek', 'English', 'PonticGreek']
['Slovenian']
['Spanish']
['Serbian']
['Finnish', 'Kareliandialect']
['Serbian']
['Slovak']
['Latvian']
['Slovene']
['Serbian']
['French']
['Spanish']
['French', 'Spanish']
['Võro']
['Macedonian']
['French', 'English']
['French']
['Italian']
['Hungarian', 'Romanian', 'Latin']
['Albanian']
['Macedonian', 'Romanian']
['French', 'English']
['Serbian', 'English']
['Italian']

In [256]:
idioma_secundario = []
for i in idioma_bien:
    if len(i.split('/')) == 2:
        idioma_secundario.append(i.split('/')[1])
    elif len(i.split('/')) > 2:
        idioma_secundario.append('VARIOS')
    else:
        idioma_secundario.append(None)

df_letras['idioma_secundario'] = idioma_secundario

In [264]:
idiomas_variosSecundarios = []
for i in idioma_bien:
    if len(i.split('/')) > 2:
        idiomas_variosSecundarios.append(i.split('/')[1:])
    else:
        idiomas_variosSecundarios.append(None)
df_letras['idiomas_variosSecundarios'] = idiomas_variosSecundarios

In [266]:
df_letras.drop(['Columna1', 'Language', 'Columna2'], axis=1, inplace=True)

In [270]:
df_letras['idiomas_variosSecundarios'].value_counts()

[English, Russian]                               1
[English, Ukrainian, Russian]                    1
[English, PonticGreek]                           1
[English, 6other]                                1
[English, Gr., French, Spanish]                  1
[German, Finnish]                                1
[English, Spanish]                               1
[Amharic, Hebrew, Arabic]                        1
[Polish, Russian]                                1
[English, Franglais]                             1
[English, Signlanguage]                          1
[French, German, Danish]                         1
[English, Sanskrit, AncientGreek]                1
[Hebrew, Japanese]                               1
[German, Montenegrin]                            1
[French, Signlanguage]                           1
[Hebrew, Arabic]                                 1
[French, German, Italian, Spanish]               1
[Italian, Spanish, Russian, French, Romanian]    1
[French, Hebrew]                                 1
[Polish, German, Russian, Spanish]               1
[English, French, Spanish]                       1
[Romanian, Latin]                                1
Name: idiomas_variosSecundarios, dtype: int64

### Sacando Variable de %Puntos sobre Máximo

In [280]:
df_puntos = pd.read_excel('./Puntos_2002_2022.xlsx')

In [277]:
dictio_particip = dict(df_letras.groupby('Year').count()['Country'])

In [279]:
dictio_particip[2002]

24

In [304]:
propo_puntosMax = []
for i,e in enumerate(df_puntos['Puntos_Corregidos']):
    maxim = (dictio_particip[df_puntos['Anio'][i]])*12
    propo = e / maxim
    propo_puntosMax.append(propo)
    
df_puntos['propo_maximPuntos'] = propo_puntosMax

In [308]:
df_puntos[df_puntos['propo_maximPuntos']>0.7]

,Orden Act.,Pais,Cantante,Cancion,Idioma,Idioma1,Idioma2,Puntos,Lugar,Anio,País,Key,Puntos_Corregidos,propo_maximPuntos
171,20,Norway,Alexander Rybak,Fairytale,English,English,NaN,387,1,2009,NORWAY,422009,387,0.767857
246,17,Sweden,Loreen,Euphoria,English,English,NaN,372,1,2012,SWEDEN,532012,372,0.738095
324,10,Sweden,Måns Zelmerlöw,Heroes,English,English,NaN,365,1,2015,SWEDEN,532015,365,0.760417
377,11,Portugal,Salvador Sobral,Amar pelos dois,Portuguese,Portuguese,NaN,758,1,2017,PORTUGAL,442017,379,0.751984

In [309]:
df_puntos.rename(columns={"Idioma1": "Idioma2", "Idioma2": "Idioma3"})

,Orden Act.,Pais,Cantante,Cancion,Idioma,Idioma2,Idioma3,Puntos,Lugar,Anio,País,Key,Puntos_Corregidos,propo_maximPuntos
0,23,Latvia,Marie N,I Wanna,English,English,NaN,176,1,2002,LATVIA,352002,176,0.611111
1,20,Malta,Ira Losco,7th Wonder,English,English,NaN,164,2,2002,MALTA,372002,164,0.569444
2,2,United Kingdom,Jessica Garlick,Come Back,English,English,NaN,111,3,2002,UNITED KINGDOM,582002,111,0.385417
3,8,Estonia,Sahlene,Runaway,English,English,NaN,111,3,2002,ESTONIA,242002,111,0.385417
4,17,France,Sandrine François,Il faut du temps,French,French,NaN,104,5,2002,FRANCE,262002,104,0.361111
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,1,Czech Republic,We Are Domi,Lights Off,English,English,NaN,38,22,2022,CZECH REPUBLIC,222022,19,0.039583
502,4,Finland,The Rasmus,Jezebel,English,English,NaN,38,21,2022,FINLAND,252022,19,0.039583
503,18,Iceland,Systur,Með hækkandi sól,Icelandic,Icelandic,NaN,20,23,2022,ICELAND,312022,10,0.020833
504,6,France,Alvan and Ahez,Fulenn,Breton,Breton,NaN,17,24,2022,FRANCE,262022,9,0.018750
505,13,Germany,Malik Harris,Rockstars,English,English,NaN,6,25,2022,GERMANY,282022,3,0.006250

In [310]:
df_puntos.head()

,Orden Act.,Pais,Cantante,Cancion,Idioma,Idioma1,Idioma2,Puntos,Lugar,Anio,País,Key,Puntos_Corregidos,propo_maximPuntos
0,23,Latvia,Marie N,I Wanna,English,English,NaN,176,1,2002,LATVIA,352002,176,0.611111
1,20,Malta,Ira Losco,7th Wonder,English,English,NaN,164,2,2002,MALTA,372002,164,0.569444
2,2,United Kingdom,Jessica Garlick,Come Back,English,English,NaN,111,3,2002,UNITED KINGDOM,582002,111,0.385417
3,8,Estonia,Sahlene,Runaway,English,English,NaN,111,3,2002,ESTONIA,242002,111,0.385417
4,17,France,Sandrine François,Il faut du temps,French,French,NaN,104,5,2002,FRANCE,262002,104,0.361111

In [312]:
df_puntos.to_excel('./Puntos_2002_2022.xlsx')

### Intentando sacar estructuras

In [381]:
df_letras['Lyrics translation'][310].split('\n')

['When hurt is all you’re feeling your heart is slowly bleeding',
 'The only memories to hold on to',
 'When you almost stop believing, you’re cold, alone and freezing',
 'You think you’re lost and don’t know where to go',
 'Look up to the startling sky, relight the fire',
 '',
 'You will shine, shine and fight the shadows in the sky',
 'You will shine, I see the light in your eyes',
 'You will shine, shine and fight the shadows in the sky',
 'Oh you will fly up high, the light is in your eyes',
 'Trust me, you will shine',
 '',
 'Time is always healing and answers are revealing',
 'Sometimes they’re simply right before your eyes',
 'But when you’re down here kneeling there is no chance to see it',
 'You can when all these dark clouds disappear',
 'Look up to the startling sky, relight the fire',
 '',
 'You will shine, shine and fight the shadows in the sky',
 'You will shine, I see the light in your eyes',
 'You will shine, shine and fight the shadows in the sky',
 'Oh you will fly up high, the light is in your eyes',
 'Trust me, you will shine',
 '',
 'Still alive and breathing',
 'Still alive and breathing',
 'Still alive and breathing, still alive and breathing',
 'Still alive and breathing',
 '',
 'You will shine, shine and fight the shadows in the sky',
 'You will shine, I see the light in your eyes',
 'You will shine, shine and fight the shadows in the sky',
 'Oh you will fly up high, the light is in your eyes',
 '',
 'Oh you will fly up high, the light is in your eyes',
 'Trust me, you will shine']

In [402]:
lista_frases = []    
acum_frases = []

for frase in df_letras['Lyrics translation'][388].split('\n'):
    if frase != '':
        acum_frases.append(frase.lower().replace(' ','').replace(',','').replace('.',''))
    else:
        lista_frases.append(''.join(acum_frases))
        acum_frases = []
lista_frases

# estructura = []
# bag_elementos = []
# num_versos = 0
# for i,lf in enumerate(lista_frases):
#     if lf not in bag_elementos:
#         estructura.append('Verso')
#         num_versos = len(lf)
#         bag_elementos.append(lf)
        
#     else:
#         estructura.append('Estribillo')
#         num_versos = len(lf)
#         bag_elementos.append(lf)

["[verse1]don'ttellthegodsileftamessican'tundowhathasbeendonelet'srunforcoverwhatifi'mtheonlyheroleftyoubetterfireoffyourgunonceandforeverhesaidgodryyoureyesandliveyourlifelikethereisnotomorrowsonandtelltheotherstogosingitlikeahummingbirdthegreatestanthemeverheard",
 "[chorus1]wearetheheroesofourtimebutwe'redancingwiththedemonsinourmindswearetheheroesofourtimehero-oh-o-o-oeso-uh-o-o-ohwe'redancingwiththedemonsinourmindshero-uh-o-o-oo-oh-o-o-ohwearetheheroesofourtimehero-oh-o-o-oeso-uh-o-o-ohwe'redancingwiththedemonsinourmindshero-oh-o-o-oeso-uh-o-o-oh",
 "[verse2]thecricketssingasongforyoudon'tsayaworddon'tmakeasoundit'slife'screationimakewormsturnintobutterflieswakeupandturnthisworldaroundinappreciationhesaidineverleftyoursidewhenyouwerelostifollowedrightbehindwasyourfoundationnowgosingitlikeahummingbirdthegreatestanthemeverheard",
 "[chorus1]wearetheheroesofourtimehero-uh-o-o-oeso-uh-o-o-ohwe'redancingwiththedemonsinourmindshero-oh-o-o-oeso-uh-o-o-oh(wekeepdancingwiththedemons)(youcouldbeahero)",
 '[bridge]nowgosingitlikeahummingbirdthegreatestanthemeverheardnowsingtogether',
 "[chorus2]wearetheheroesofourtime(hero-oh-o-o-oeso-uh-o-o-oh)butwe'redancingwiththedemonsinourminds(hero-oh-o-o-oeso-uh-o-o-oh)wearetheheroesofourtime(wekeepdancingwiththedemons)(youcouldbeahero)hero-oh-o-o-oeso-uh-o-o-ohbutwe'redancingwiththedemonsinourminds(wekeepdancingwiththedemons)(youcouldbeahero)hero-oh-o-o-oeso-uh-o-o-oh"]

In [401]:
lista_frases[1] == lista_frases[3]

False

In [358]:
estructura_bien = ['A']
for i,e in enumerate(estructura_mal):
    if e != estructura_mal[i-1] and i>0:
        estructura_bien.append(e)
estructura_bien

['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B', 'A']

In [352]:
df_letras[df_letras['Song']=='Heroes']

,Country,Artist,Song,Eurovision_Number,Year,Host_Country,Host_City,Lyrics,Lyrics translation,Lyrics_Long,Lyrics_words,key,Vecinos_Participantes,idioma_bien,num_idiomas,idioma_principal,idioma_secundario,idiomas_variosSecundarios
388,Sweden,Måns Zelmerlöw,Heroes,60,2015,Austria,Vienna,[Verse 1]\nDon't tell the gods I left a mess\n...,[Verse 1]\nDon't tell the gods I left a mess\n...,1593,111,532015,2,English,1,English,None,None

In [ ]:
# IMPOSIBLE HACERLO CON LAS LETRAS.... UN MÍNIMO CAMBIO EN UNA PALABRA O UN SIMPLE "OH" QUE AÑADA ALGUNA "O" MÁS YA ME
# DESAJUSTA LA SIMILITUD Y NO PUEDO CREAR UN PATRÓN QUE DETECTE LA ESTRUCTURA... PROBAREMOS CON PYCHORUS...

### Pequeña investigación de Canciones perdidas

In [1]:
### Sanomi 2003

letra_sanomi = '''Sanomi helé, manilla keranu
Aliya irema nia lago, ture madilé
Sanomi helé, manilla keranu
Aliya irema nia madilé

Kenatu narilé, lakenatu narilé
Pasema niamo ture saro, delamaoré
Kenatu narilé, lakenatu narilé
Pasema niamo ture sanisi

Sanomi helé, manilla keranu
Aliya irema nia lago, ture madilé
Sanomi helé, manilla keranu
Aliya irema nia madilé

Kenatu narilé, lakenatu narilé
Pasema niamo ture saro, delamaoré
Kenatu narilé, lakenatu narilé
Pasema niamo ture sanisi

Léala, léala, sorimana, sorimana
Léala, léala, sorimanao
Léala, léala, sorimana, sorimana
Léala, léala, sorimana soléo

Sanomi helé, manilla keranu
Aliya irema nia madilé

Léala, léala, sorimana, sorimana
Léala, léala, sorimanao
Léala, léala, sorimana, sorimana
Léala, léala, sorimana soléo'''

In [10]:
import re
sanomi_long = len(re.sub(' +', ' ', letra_sanomi.replace('\n'," ").replace('(',"").replace(')',"").replace('.',"").replace(',',"").replace('-',"").replace('[Verse 1]',"").replace('[Verse 2]',"").replace('[Verse 3]',"").replace('[Chorus]',"").replace('[Bridge]',"").replace('PreChorus',"").replace('[',"").replace(']',"").strip()))
unics_sanomi = len(set(re.sub(' +', ' ', letra_sanomi.lower().replace('\n'," ").replace('(',"").replace(')',"").replace('.',"").replace(',',"").replace('-',"").replace('[Verse 1]',"").replace('[Verse 2]',"").replace('[Verse 3]',"").replace('[Chorus]',"").replace('[Bridge]',"").replace('PreChorus',"").replace('[',"").replace(']',"").strip()).split(" ")))
sanomi_long, unics_sanomi

(723, 22)

In [19]:
from collections import Counter
dict_sanomi = {k: v for k, v in sorted(dict(Counter(letra_sanomi.replace('\n',"").lower().split(" "))).items(), key=lambda item: item[1], reverse=True)}
list(dict_sanomi)[:5]

['léala,', 'ture', 'helé,', 'manilla', 'keranualiya']

In [20]:
julissi = '''O julissi na jalini
O julissi na ditini
O bulo diti non slukati
Sestrone dina katsu
 
O julissi na ti buku
O julissi na katinu
Dvoranu mojani bidna
Marusi naja otcha tu
 
(Pokoli sestro moja kona) Moja kona
(Pokoli meni dita boja) Dita boja
(Jalina pitsu marusinja) Marusinja
(Kolosali) krokodili
 
O julissi na jalini
O julissi na ditini
O bulo diti non slukati
Sestrone dina katsu
 
O julissi na ti buku
O julissi na katinu
Dvoranu mojani bidna
Marusi naja otcha tu
 
(Pokoli sestro moja kona) Moja kona
(Pokoli meni dita boja) Dita boja
(Jalina pitsu marusinja) Marusinja
(Kolosali) krokodili
 
O julissi na jalini
O julissi na ditini
O bulo diti non slukati
Sestrone dina katsu
 
O julissi na slukati
O julissi na kotchali
Od nu je dvorian ne si bili
Precko sti budo najali
 
O julissi na ja
O julissi na jalini
O julissi na ditini
O bulo diti non slukati
Sestrone dina katsu
 
O julissi na jalini
O julissi na ditini
O bulo diti non slukati
Sestrone dina katsu
https://lyricstranslate.com/es/ishtar-o-julissi-lyrics.html'''

In [21]:
julissi_long = len(re.sub(' +', ' ', julissi.replace('\n'," ").replace('(',"").replace(')',"").replace('.',"").replace(',',"").replace('-',"").replace('[Verse 1]',"").replace('[Verse 2]',"").replace('[Verse 3]',"").replace('[Chorus]',"").replace('[Bridge]',"").replace('PreChorus',"").replace('[',"").replace(']',"").strip()))
unics_julissi = len(set(re.sub(' +', ' ', julissi.lower().replace('\n'," ").replace('(',"").replace(')',"").replace('.',"").replace(',',"").replace('-',"").replace('[Verse 1]',"").replace('[Verse 2]',"").replace('[Verse 3]',"").replace('[Chorus]',"").replace('[Bridge]',"").replace('PreChorus',"").replace('[',"").replace(']',"").strip()).split(" ")))
julissi_long, unics_julissi

(986, 48)

In [22]:
dict_julissi = {k: v for k, v in sorted(dict(Counter(julissi.replace('\n',"").lower().split(" "))).items(), key=lambda item: item[1], reverse=True)}
list(dict_julissi)[:5]

['julissi', 'na', 'o', 'jalinio', 'ditinio']

In [1]:
import pandas as pd

In [3]:
mastertabla = pd.read_excel('../Excels/MASTERTABLA.xlsx')

In [4]:
apuestas = pd.read_excel('../Excels/Apuestas_TOTAL.xlsx')

In [6]:
apuestas.drop('Columna1', axis=1, inplace=True)

In [8]:
mastertabla.drop('Unnamed: 0', axis=1, inplace=True)

In [10]:
apuestas.rename(columns = {'codigo':'key'}, inplace = True)

In [12]:
apuestas.drop('country', axis=1, inplace=True)
mastertabla = mastertabla.merge(apuestas, on='key', how='left')
mastertabla

,key,country_id,country,artist,song,year,lyrics_long,unic_words,vecinos_participantes,love_song,...,influ_score,reput_ranking,reput_sci_tech,reput_cult,reput_peace_secur,reput_world_order,reput_planet_climate,reput_props_equal,reput_health_wellbeing,bet_mean
0,412011,41,North Macedonia,Vlatko Ilievski,Rusinka (Русинкa),2011,789,44,4,Yes,...,NaN,46.0,19.0,55.0,135.0,54.0,65.0,74.0,34.0,550.000000
1,262009,26,France,Patricia Kaas,Et s'il fallait le faire,2009,1208,122,5,Yes,...,95.26,11.0,24.0,14.0,53.0,16.0,3.0,17.0,23.0,26.000000
2,522002,52,Spain,Rosa,Europe's Living a Celebration,2002,1355,102,1,Yes,...,78.72,18.0,40.0,30.0,70.0,15.0,9.0,34.0,22.0,15.000000
3,402013,40,Montenegro,Who See,Igranka (Игранка),2013,2058,190,3,Yes,...,NaN,71.0,48.0,61.0,128.0,41.0,91.0,71.0,134.0,550.000000
4,412007,41,North Macedonia,Karolina (2),Mojot svet (Мојот свет),2007,896,49,4,Yes,...,NaN,46.0,19.0,55.0,135.0,54.0,65.0,74.0,34.0,21.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
812,262016,26,France,Amir,J'ai cherché,2016,1727,109,5,Yes,...,95.26,11.0,24.0,14.0,53.0,16.0,3.0,17.0,23.0,24.950000
813,482019,48,Serbia,Nevena Božović,Kruna (Круна),2019,544,57,5,Yes,...,NaN,69.0,105.0,78.0,80.0,74.0,83.0,15.0,138.0,225.764706
814,352007,35,Latvia,Bonaparti.lv,Questa notte,2007,851,68,4,Yes,...,NaN,41.0,13.0,17.0,104.0,70.0,42.0,80.0,70.0,100.000000
815,172003,17,Belgium,Urban Trand,Sanomi,2003,723,22,3,No,...,57.96,13.0,9.0,1.0,109.0,13.0,22.0,7.0,16.0,28.000000
816,172008,17,Belgium,Ishtar,O julissi,2008,986,48,3,No,...,57.96,13.0,9.0,1.0,109.0,13.0,22.0,7.0,16.0,550.000000

In [17]:
mastertabla.to_excel('../Excels/Data_to_visualization.xlsx')